nmstate/nmstate

libnmstate/schema.py, libnmstate/schemas/interfaces.json, libnmstate/validator.py, requirements.txt, tests/lib/schema_validation_test.py, tox.ini
A basic schema is introduced, defined in json-schema[1] and implemented
by jsonschema[2] python implementation.
The full/partial definition for the nmstate schema will be introduced in
a seperate patch.
[1] http://json-schema.org
[2] https://github.com/Julian/jsonschema
=> Introduce a basic schema with validation tests

libnmstate/netapplier.py
Non physical devices may now be removed by stating 'absent' in the iface
admin state.
=> libnmstate: Support software interface removal

libnmstate/netapplier.py, libnmstate/netinfo.py, libnmstate/nm/__init__.py, libnmstate/nm/applier.py, libnmstate/nm/bond.py, libnmstate/nm/device.py, libnmstate/nm/translator.py, tests/lib/netinfo_test.py
The NM package should include all the logic on how to access NM.
The translator needs to include all the translation logic between the formats while the individual NM modules (which represents the NM API structure) should provide access to NM API.
=> Decouple nm provider

libnmstate/netinfo.py, libnmstate/nm/connection.py, libnmstate/nm/ipv4.py, tests/lib/netapplier_test.py, tests/lib/netinfo_test.py, tests/lib/nm/ipv4_test.py
These are the current active values on an active connection profile.
Based on #28
DHCP will be added in a future patch.
Signed-off-by: Till Maas <till@redhat.com>
Signed-off-by: Edward Haas <edwardh@redhat.com>
=> libnmstate: Support IPv4 info reporting

nmstatectl/nmstatectl.py
Log everything to stderr. More configuration will be allowed later. Output is a little messy, if not redirected, command output and logging is mixed.
Example output:
```
2018-06-27 12:18:37,066 root         DEBUG    This is a debug message
2018-06-27 12:18:37,067 root         ERROR    This is an exception message
File "/home/phoracek/Code/nmstate/env/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 34, in main
a = 1/0
ZeroDivisionError: integer division or modulo by zero
```
=> add basic logging initialization

README.md, nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py
Since the network state file is always requirer/not optional, specify it
as an argument, not as an option.
=> Do not require "-f/--file" to specify state

libnmstate/netapplier.py, tests/lib/netapplier_test.py
This might be related to the missing GLib.MainLoop.
=> netapplier: Apply settings twice to get it to work

libnmstate/netapplier.py, tests/lib/netapplier_test.py
In a scenario where an existing slave is specified under a new master in
the desired state, but not removed from the current master, the outcome
desired state (through the metadata) should point to the new master.
This patch fixes a bug where such slaves pointed to the previous master
in the calculated desired state.
=> netapplier: Reflect correctly slave master even when reused

libnmstate/netapplier.py, libnmstate/netinfo.py, libnmstate/nm/ovs.py, libnmstate/validator.py
Introduce the OVS capability in the report and avoid processing the OVS
interface types when it is missing.
Capabilities are now reported at the top level report under
'capabilities'.
By default, it is not included in the 'nmstatectl show' report, just
used internally.
=> libnmstate: Process OVS only if the capability exists

libnmstate/netapplier.py, libnmstate/nm/connection.py, libnmstate/nm/device.py, libnmstate/nmclient.py, tests/lib/netapplier_test.py, tests/lib/nm/connection_test.py, tests/lib/nm/device_test.py
The NM provider is executing libnm async funtions.
For proper operation and in order to serialize the actions, GLib
main-loop use has been embedded through a mainloop object.
The async funtions against libnm are registered to the mainloop object
and then executed one after the other from that queue.
The callback functions for each async command are responsible to execute
the next action in the mainloop object queue.
=> NM mainloop

libnmstate/nmclient.py
Before this patch, if the last action in the mainloop queue failed, it
got ignored.
With this patch, the mainloop run exists with an error if the last
action failed and the transaction is able to kick in.
=> mainloop: If the last action fails, exit correctly

libnmstate/netapplier.py, libnmstate/nm/applier.py, tests/lib/netapplier_test.py
The mainloop is run in two steps, once for addition and a second time
for editing.
The split is introduced because after the addition, the current state
needs to be refreshed and be based on the addition step. This implies
that the addition should finish completely (running all the actions).
It is now possible to create a new master (ovs-bridge) to use a slave
that is already used by a different master. The slave will "move" to the
new master correctly.
=> libnmstate: Refresh current state before the edit step

libnmstate/netapplier.py, libnmstate/nm/applier.py, libnmstate/nm/device.py, tests/lib/netapplier_test.py, tests/lib/nm/applier_test.py, tests/lib/nm/device_test.py
This patch is handling the following points:
- A slave iface state which is not mentioned in the desired state,
is determined based on the master state.
This way, the state of the master can define the slaves or can remove
them with the master.
- The 'down' state should be handled as 'absent' for the time being,
specifically for the NM provider implementation. The current mapping
between 'down' and 'deactivate' in NM terms causes connection profiles
to be left on the system unused.
- The device.delete functionality is now using a safer async wrapper,
which is handled through the mainloop. When a deletion is requested,
it is performed only if the device still exists, otherwise it is
skipped.
In several cases, the deletion of a connection profile is triggered by
more than one source. Due to …
=> libnmstate: Fix handling of iface edition and deletion

libnmstate/nm/applier.py, tests/lib/nm/applier_test.py
When there are bonds or OVS bridges, the current admin-state handling may execute an activation/deactivation multiple times on a single iface (on slaves in particular).
We should avoid this and perform the action once per device.
=> Set admin state once when master/slave interfaces are involved

libnmstate/nm/wired.py
It seems to be reported when speed setting is not supported.
=> wired: Do not report speed 0

libnmstate/netapplier.py, nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py, tests/lib/netapplier_test.py
The verify-change flag is introduced, causing an assertion between the
desired and current state to occur at the end of the transaction.
In case the desired state is not (fully) part of the current state, the
transaction fails and the configuration is reverted to the original
state.
=> libnmstate.apply: Introduce verify-change flag

libnmstate/nm/wired.py, tests/lib/nm/wired_test.py
When auto-negotiation is enabled and speed/duplex are not explicitly
specified, reset them to allow them to be fully auto-negotiated. Also
use props to set the properties to match the other modules and simplify
testing.
=> Reset speed and duplex when enabling auto-negotiation

libnmstate/nm/translator.py
When NetworkManager-ovs package is missing, the report execution failed
by raising an exception.
nmstate should not fail in such cases. It is sufficient to ignore OVS
related interfaces.
=> nm: Reporting should not fail if ovs plugin is missing

automation/run-integration-tests.sh
automation: Run the integration tests from an existing image
In order to stabilize the running tests and enable faster execution,
the docker image is pulled from the hub instead of recreating it
every execution.
Locally the execution takes several seconds now.
=> Use an existing docker image

libnmstate/netinfo.py, libnmstate/nm/applier.py, libnmstate/nm/ipv6.py, tests/integration/nmstatectl_show_test.py, tests/lib/netapplier_test.py, tests/lib/netinfo_test.py, tests/lib/nm/ipv6_test.py
Example:
```json
{
"interfaces": [
{
"ipv4": {
"address": [
{
"ip": "192.168.32.11",
"prefix-length": 24
}
],
"enabled": true
},
"ipv6": {
"address": [
{
"ip": "fe80::8097:51a0:9ff4:c7a1",
"prefix-length": 64
}
],
"enabled": true
},
"mtu": 1500,
"name": "wlp3s0",
"state": "up",
"type": "unknown"
}
]
}
```
=> Add support of static IPv6.

libnmstate/netapplier.py, libnmstate/nm/wired.py, tests/lib/nm/wired_test.py
When auto-negotiation is enabled, duplex and speed ethernet settings
should not be merged from the current state to be able to distinguish
whether a user specified the settings or not.
=> Do not merge duplex and speed for auto-negotiation

libnmstate/netapplier.py, tests/lib/netapplier_test.py
Since we are going to change this for nmstatectl, it makes sense for the API as well IMHO.
=> netapplier: Verify state by default

automation/Dockerfile
Including the `ip` toolset in the image for debugging and possible test usage.
=> automation: Add the iproute package to the docker image

tox.ini
Use older version of urllib3: 1.23
The error seen on CI:
File
"/home/travis/build/nmstate/nmstate/.tox/coveralls/local/lib/python2.7/
site-packages/requests/compat.py",
line 48, in <module>
from urllib3.packages.ordered_dict import OrderedDict
=> tox: coverall fails to run due to urllib3 new version

tox.ini
When running the tests using pytest, debug level logging helps debug
failing tests.
With this patch, when tests fail, the debug logs are included in the
report.
=> tox: Explicitly define pytest log level to DEBUG

automation/README.md, automation/run-integration-tests.sh
Adding 2 additional links to the running docker (3 in total) to allow
complex test configurations to be supported.
=> automation: Connect 2 additional networks to docker

libnmstate/netapplier.py, libnmstate/nm/wired.py
nmstate is processing the desired state of an interface and adds base
information for the 'ethernet' properties (auto-negotiation, speed and
duplex).
The 'ethernet' properties are relevant only for ethernet type interfaces
and not for virtual ones. In addition, the base values used in the
sanitize step may cause the post apply verification to fail.
The interface ethernet state sanitize is now limited to ethernet type
interfaces and special handling has been added in the verification step
to allow proper comparison between the desired and the current state.
=> libnmstate: Interface desire state sanitize adjustment

automation/Dockerfile, automation/run-integration-tests.sh
automation: Drop tox usage
Instead of using tox, install all the dependencies
in the container image.
This approach should reduce the instability due to dns connectivity
problems from inside the container to the outside world.
Depends on #100
=> Drop tox from the integ tests

nmstatectl/nmstatectl.py, nmstatectl/prettystate.py, tests/ctl/nmstatectl_test.py, tests/integration/nmstatectl_show_test.py
When showing or editing a state, show the interface name first. This makes it easier to find a specific interface state or to edit the state in yaml, since the interface name now appears after the dash instead of other options that one might want to remove.
=> Show interface name first

automation/run-integration-tests.packages, automation/run-integration-tests.sh, libnmstate/netapplier.py
If all ethernet properties are ignored, the 'ethernet' subtree needs to
be removed from the desired state.
=> libnmstate: Fix ignore unspecified ethernet settings

automation/run-integration-tests.sh
DNS instability still exists when running the test script in CI.
It has been observed that the docker container changes the resolv.conf
when additional networks are added. Therefore, this patch changes the
steps taken in the deploy script such that nmstate is installed from
source *before* the additional networks are added.
In addition, for modularity and ease of reading, a refactoring has been
applied, mainly by extracting commands into functions.
=> automation: Refactor the deploy script and change oper orders

automation/run-integration-tests.sh, tests/integration/conftest.py, tests/integration/static_ip_address_test.py, tests/integration/testlib/__init__.py, tests/integration/testlib/assertlib.py, tests/integration/testlib/statelib.py
Configuring a static IPv4 address on an interface.
The assertion is embedded in the transaction verification,
which is on by default.
=> tests: Add an integ lib test for adding static IPv4

automation/Dockerfile
Do not create generated connections automatically on all devices in the
container.
=> automation: Docker - Enable no-auto-default on all devices

libnmstate/nm/applier.py, tests/lib/nm/applier_test.py
When the iface state is set to `down` or `absent` it is not enough to delete the connection profile. The device needs to be deactivated so NM will not re-trigger an auto connection creation.
=> Nm deactivate device

.gitignore, automation/run-integration-tests.sh
Collect the journalctl output and cores in case they exists.
The oVirt STDCI will save these for a limited period under the job
artifacts.
=> automation: Collect artifacts for the CI to save

libnmstate/netapplier.py
This makes verification work with actual Ethernet devices that properly report Ethernet settings.
=> Ethernet cleanup

automation/run-integration-tests.sh
This should fix the random CI failures due to the dbus service too slow to come up.
=> automation: Wait for the dbus service to come up in the container

tests/integration/static_ip_address_test.py
Two new tests were added to the ethernet integration tests:
- remove static ipv4
- edit static ipv4 address and prefix
=> tests integ: Adding ethernet ipv4 tests

automation/README.md, automation/run-integration-tests.sh
Make it possible to enter a shell in the integration test docker image
before it would exit. This makes it easier to debug/develop integration
tests.
=> Docker: Allow to start shell with variable

tests/integration/ethernet_mtu_test.py
The following scenarios are added to the ehternet integration tests:
(Relative to the mtu default value of 1500)
- Increase mtu
- Decrease mtu
- Increase mtu to the upper jambo limit
- Increase mtu to be bigger than jambo upper limit
- Decrease mtu to zero
- Decrease mtu to negative value
- Decrease mtu to lower than min limit
=> tests integ: Adding ethernet mtu tests

libnmstate/netapplier.py, tests/integration/testlib/assertlib.py, tests/integration/testlib/statelib.py
The link-aggregation slaves are now sorted (by name) in order to pass
the verification step (comparison between the desired and current
state).
This should fix now bond creation.
=> netapplier: Sort LAG slaves on verification

libnmstate/nm/applier.py, libnmstate/nm/wired.py, tests/lib/nm/wired_test.py
* Fix NULL interface name of NMSettingConnection.
* Fix `unknown` duplex mode of virt-net.
=> Misc fixes for running nmstatectl edit on Fedora.

automation/run-integration-tests.sh, libnmstate/iplib.py, libnmstate/netapplier.py, libnmstate/nm/ipv6.py, tests/integration/ethernet_mtu_test.py, tests/integration/static_ip_address_test.py, tests/integration/testlib/statelib.py, tests/lib/netapplier_test.py, tests/lib/nm/ipv6_test.py
~~* Raise exception when user try to flip IPv6 status(enable/disable).~~
Other Design not been chose:
* Option A: Use sysctl to disable/enable IPv6.
* Pros:
* Works as expected for IPv6 disable and enable.
* Cons:
* Need to parse multiple localtion of sysctl.d(/run, /etc,
/usr/lib, /user/local, ....)
* Need to handle when user disable/enable IPv6 using their own
file of sysctl.conf.
* Docker does not allow sysctl inside.
* Option B: Hide IPv6 link local address.
* Pros:
* No hack required to support IPv6 enable/disable via
NetworkManager.
* Cons
* We does not showing the precise current network state.
* Ordering the IP addresses before verify comparison of `netapplier.apply()`.
~~ * Raise `MissingIPv6LinkLocalAddressError` when no IPv6 link local address.~~
* Ignore IPv6 link-local …
=> Misc fixes for applying IPv6  static address.

automation/run-integration-tests.sh
It has been seen that some containers (locally and on CI) do not come up with IPv6 enabled and it causes the tests to fail.
Basically, IPv6 is not enabled if it was never configured (the case for many tests, so it depends on test run order).
=> automation: Explicitly enable IPv6 on test container

libnmstate/prettystate.py
Show more context when diffing the state to make it easier to identify
differences for non-unique settings such as `enabled` which appears both
for ipv4 and ipv6.
=> State diff: Show three lines context

automation/Dockerfile
This PR is all about removing the special NetworkManager.conf setting which makes sure to avoid creating a connection profile automatically on interfaces.
nmstate should be able to handle this without special config.
NOTE: Tests show (with #98 ) that it is not working as expected yet. There are from time to time timeouts on waiting for the activation callback. Further investigation is needed.
Nevertheless, the changes merit a proper review.
NOTE2: The last commit needs to be removed before merging, in parallel to the creation of a new image.
=> Nm disable no auto default

tests/integration/ethernet_mtu_test.py
New test aimed to check that mtu value cannot be decreased lower than
1280
=> integ test: Decrease ipv6 iface mtu to lower then min

automation/run-integration-tests.sh
This allows to pass extra arguments to pytest via the
`nmstate_pytest_extra_args` variable:
nmstate_pytest_extra_args="--pdb -x" ./automation/run-integration-tests.sh
=> Integration tests: Allow passing extra arguments to pytest

tests/integration/nm/vlan_test.py
Remove the sleep introduced in previous patched and add an NM client
refresh.
While outside the mainloop, the client needs to be re-created in order
to retrieve updated information form NM.
=> tests integ: Fix nm VLAN tests by refreshing nm client

libnmstate/netapplier.py, tests/integration/bond_test.py, tests/integration/ethernet_mtu_test.py, tests/integration/iface_admin_state_test.py, tests/integration/static_ip_address_test.py
Copying the dict in apply function assures that the caller data is not
modified by nmstate.
Signed-off-by: Sveta Haas <sveta.haas@gmail.com>
=> Integ tests: Move deepcopy of desired state into the apply func

libnmstate/ethtool.py, nmstatectl/nmstatectl.py
* Python 3 does not print help message any more when no sub command
provided. Fix would be check the length of argument list.
* Fix the string encoding.
=> nmstatectl: Fix running on Python 3.

libnmstate/netapplier.py, libnmstate/nm/applier.py, libnmstate/nm/device.py, tests/integration/bond_test.py, tests/integration/nm/vlan_test.py, tests/lib/netapplier_test.py, tests/lib/nm/device_test.py
NMState supports several virtual interfaces, all having a master-slave
relationship (bond, ovs-bridge). The master interface has been activated
so far by its slaves (which automatically perform such an activation
when they are activated).
With the introduction of VLAN interfaces, it is now required for the
virtual interface to be explicitly activated.
Activating a new interface is now supported by executing an activation
command on the (remote) connection profile. Existing interfaces are
still activated using their device object.
=> nm: Activate new virtual interfaces

tests/integration/bond_test.py, tests/integration/conftest.py, tests/integration/ethernet_mtu_test.py, tests/integration/iface_admin_state_test.py, tests/integration/nm/vlan_test.py, tests/integration/static_ip_address_test.py
Refactor integration tests global fixtures.
The final intent is to optimize the individual interface cleanup/setup by need only.
Depends on #156
=> Integ tests eth1 eth2

automation/Dockerfile
The CentOS version mentioned in the Dockerfile is now pointing to a
specific build (7.5.1804) instead of 'latest'.
The current 'latest' image has been found not to work well with NM.
=> automation: Fix CentOS version in Dockerfile

libnmstate/nm/applier.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, tests/integration/nm/vlan_test.py, tests/integration/preserve_ip_config_test.py, tests/lib/nm/ipv4_test.py, tests/lib/nm/ipv6_test.py
* With this fix `netapplier.apply()` will not discard all IP configurations(DNS, route, etc) but keep existing  one except IP addresses.
~~This PR is based on #107 , please review it first.~~
=> Preserve other existing IP configurations when apply()

.gitignore, automation/Dockerfile, automation/run-integration-tests.sh, packaging/make_rpm.sh, packaging/nmstate.py2.spec.in, packaging/nmstate.py3.spec.in
* Contains a fix for running nmstatectl in python3.
* Contains patch for removing pbr dependent.
* `packaging/make_rpm.sh` to make rpm for RHEL 7/8 and Fedora 28+.
* Change the integration test to use compiled rpm instead of `pip install`.
Extra notes:
* The script `make_rpm.sh` is designed to build rpm from git HEAD, it's not designed to release.
* For RHEL/Centos 7, it requires EPEL repo enabled.
* ~~RHEL 8 beta is not supported yet as we are missing `python3-pbr` there. 
I will add patch to remove dependency of pbr in this PR soon.~~
=> Fedora/RHEL RPM

MANIFEST.in
Add README.md and LICENSE to MANIFEST.in to make sure they are
included in the tarball created by `python setup.py sdist`.
=> Include README.md and LICENSE in tarball.

setup.py
Reference: https://packaging.python.org/guides/making-a-pypi-friendly-readme/
=> Setup.py: Set content type for long description

packaging/make_rpm.sh
When we have tagged version, the generated VERSION is incorrect.
It should be ${VERSION} instead of $(VERSION).
=> make_rpm.sh: Fix trivial syntax error.

tests/integration/preserve_ip_config_test.py
* Issue:
The integration test case `test_reapply_preserve_ip_config` will
fail showing ipv4 is disabled.
* Root cause
After commit 4e34009a828ded98e2a7b14b8cb009c7f0b6cf08, nmstate
will goes to verification stage once network manager indicate a
profile is activated. The NetworkManager does not wait on
ipv4.dad-timeout for marking a profile is activated. This makes
nmstate got no IPv4 address during duplicate address detection
stage, which then mark ipv4 as disabled.
* Fix
Change ipv4.dad-timeout in `test_reapply_preserve_ip_config` to 0
which is no wait on duplicate address detection.
=> Integration test: Change ipv4.dad-timeout.

automation/run-integration-tests.sh
Making pytest verbose makes it show full diffs for state comparisons.
=> Integration tests: Make pytest verbose

automation/Dockerfile, automation/run-integration-tests.sh, packaging/make_rpm.sh
By pre-installing all required rpms in docker image, the
integration test does not require network access anymore,
This also save a lot of test time as `run-integration-tests.sh`
does not depend on any yum/dnf command anymore.
=> Integration test: don't require network access.

libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py
Only preserving existing IP configurations when IPv4/6 is enabled.
Fixes: #188
=> Don't copy existing config when disabling IPv4/v6

automation/Dockerfile, libnmstate/netapplier.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/validator.py, tests/integration/dhcp_test.py, tests/integration/testlib/statelib.py, tests/lib/nm/ipv4_test.py, tests/lib/nm/ipv6_test.py
The sample output of `nmstatectl show` for DHCP:
"ipv4": {
"address": [
{
"ip": "192.0.2.251"
"prefix-length": 24
}
],
"dhcp": true,
"enabled": true
},
"ipv6": {
"address": [
{
"ip": "fe80::1",
"prefix-length": 64
},
{
"ip": "2001:db8:1::1",
"prefix-length": 64
}
],
"autoconf": true,
"dhcp": true,
"enabled": true
},
Will raise InvalidIPv6OptionError exception if user are asking
IPv6 'dhcp: false' and 'autoconf: true'.
=> Add support of IPv4/IPv6 DHCP.

libnmstate/netapplier.py, libnmstate/schema.py, tests/integration/vlan_test.py
Currently, when in the desired state a virtual interface is set as
`down`, it is removed (treated as `absent`).
When the verification step occurs, checking that the desired state is
included in the current state, these virtual interfaces should be
treated like the `absent` ones.
=> netapplier: Ignore `down` state (for virt iface) in verification step

libnmstate/nm/device.py
DEVICE_DISCONNECTED is a attribute of `ActiveConnectionStateReason` (not
`ActiveConnectionState`).
=> NM/device: Fix AttributeError

libnmstate/nm/device.py, tests/lib/nm/device_test.py
When a connection is activated, the user data for the active connection
callback does not contain a device object. Therefore report the
connection ID instead of the device instead.
fixes #198
=> NM/device: Handle activation failures for connections

libnmstate/nm/nmclient.py
The logging of the action function arguments is not helpful, makes it
difficult to follow the logs, therefore, they are removed.
=> nm: Reduce noise when logging actions execution

libnmstate/nm/checkpoint.py
In case an exception occurs in a contextmanager, python will re-raise
the exception automatically after the __exit__ method is processed.
Raising from within __exit__ is not required in this case.
=> nm: Do not raise explcitly within the checkpoint context

.copr/Makefile, packaging/get_version.sh, packaging/make_rpm.sh, packaging/make_spec.sh, packaging/make_srpm.sh, packaging/nmstate.py2.spec, packaging/nmstate.py3.spec
Break up the rpm building process in individual scripts that accept the
COPR environment variables `spec` and `outdir` and add a Makefile for
COPR automated building. Rename the spec files to have a spec suffix
because COPR requires this to specify them.
I suggest to create two new COPRs for this for the nmstate user:
nmstate-git-python2 (for EPEL7)
nmstate-git-python3 (for Fedora and EPEL8 eventually)
They would be automatically rebuilt as soon as changes are pushed to master. I tested it with my branch here:
https://copr.fedorainfracloud.org/coprs/till/tyll-nmstate-fedora/builds/
=> packaging: Prepare automated COPR packaging

packaging/nmstate.py2.spec, packaging/nmstate.py3.spec
@cathay4t I noticed that the Fedora spec uses Suggests instead of Recommends for NetworkManager. IMHO Recommends is better since by default nmstate needs to run on the same system as NetworkManager and Suggests are currently ignored by DNF.
=> RPM packaging: Sync back changes from Fedora packaging

automation/run-integration-tests.sh
The integration CI test might fail with NetworkManager service not
started, hence we do a polling on waiting NetworkManager started with
60 seconds timeout.
=> Integration test: Wait NetworkManager service

automation/Dockerfile.fedora, automation/README.md, automation/docker_enable_systemd.sh, automation/docker_sys_config.sh
Fedora CI image has been uploaded to docker hub as `nmstate/fedora-nmstate-dev`.
=> Adding Fedora CI docker image.

nmstatectl/nmstatectl.py
The yaml state ends with a newline, therefore print() should not be used
as is to avoid an empty line at the end of the state.
Use sys.stdout.write() for Python 2/3 compatibility.
=> nmstatectl: Remove extra newline from yaml output

packaging/nmstate.py2.spec, packaging/nmstate.py3.spec
nmstatectl needs python-setuptools to import `pkg_resources`:
```
File "/usr/bin/nmstatectl", line 5, in <module>
from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```
=> RPMs: Require python-setuptools

libnmstate/prettystate.py, nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py, tests/integration/nmstatectl_test.py
YAML output is more concise and easier to edit, therefore prefer it.
=> nmstatectl: Output yaml by default

.stdci.yml
stdci is using `mock` (using chroot) to deploy the distribution. The
runtime OS may be a totally different distribution which may cause
issues when the tests touch OS related services.
Marking the stdci configuration to make sure and run both the mock and
the slave with the same distribution.
We are seeing recently some crashes on the CI and suspect this is the problem (seen on VDSM tests as well a week back).
=> stdci: Sync runtime slave distribution with the mock

tox.ini
Currently, CI requires an extra service to make the coverage data
humanly readable. By outputting the coverage data to the terminal, it
is directly available in the logs.
=> tox: Output coverage data also to terminal

automation/run-integration-tests.sh
Changes the hard coded python site path to use rpm macro output by check
whether we are running on Fedora or Centos.
Let the Fedora docker instance run both integration tests and tox tests
in order to gather all code coverage reports.
=> Improve code coverage CI to support Fedora python3

automation/README.md, automation/run-integration-tests.sh
Introduce --pytest-args and --debug-shell to run-integration-tests.sh to
make it easier to use these features with sudo since sudo does not pass
untrusted environment variables.
=> automation: Add support for getopts

automation/Dockerfile, automation/Dockerfile.fedora
This is Gris' commit from #254 to fix the docker image and thus the CI by merging this. I amended the commit message a little bit to add missing words.
=> Centos CI docker image: Upgrade pytest to 4.2.1

libnmstate/netapplier.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/schemas/operational-state.yaml, tests/integration/dhcp_test.py, tests/integration/testlib/statelib.py, tests/lib/nm/ipv4_test.py, tests/lib/nm/ipv6_test.py
Added these options to ipv4 and ipv6 section:
* ignore-auto-routes:  Ignore all DHCP/autoconf routes(including gateway).
* ignore-auto-gateway: Ignore the DHCP/autoconf gateway.
* ignore-auto-dns:     Ignore the DNS provided by DHCP.
=> Add option for ignoring auto DNS and routes

packaging/nmstate.py3.spec, requirements.txt
- setuptools dependency was missing in requirements.txt
- python-gobject-base dependency can now be auto-generated from requirements.txt since #248
=> Cleanup RPM and python dependencies

tox.ini
Contains two patches:
* Remove duplicate lines in `tox.ini` for requirements and pytest arguments.
* Enable python 3.7 for unit test in `tox.ini`.
=> Enable unit test on Python 3.7

automation/Dockerfile.fedora
Since we included PyGObject into `requirements.txt`, the tox unit tests
will try to install PyGObject which will fail in Fedora docker CI image.
=> Fedora CI docker image: Add dependencies for unit test

README.md, automation/Dockerfile, packaging/Dockerfile.centos7-nmstate, packaging/Dockerfile.centos7-nmstate-base, packaging/README-dockerhub.md, packaging/docker_enable_systemd.sh, packaging/docker_sys_config.sh
This is based on the feedback from #241 but limited to CentOS7 for now to avoid the complexity for the several Fedora releases. Before it can be merged we need to setup the builds in docker hub to avoid breaking the CI image.
=> Package nmstate for CentOS7 as container image

automation/run-integration-tests.sh
The live-log option creates a lot of noise while running the
integration tests with no special added value.
Only when a failure occurs, the logs need to be examined.
=> automation: Disable pytest live-log

libnmstate/netinfo.py, libnmstate/nm/device.py
Usage of the NM client object should be limited in most cases to a
single instance.
In particular, during a mainloop run, only a single instance of the
client should be used due to its cached data.
This change is limited in scope, fixing issues seen with current
integration tests. A follow up change will organize the client object
lifetime in a more systematic manner.
=> nmclient: Explicitly create a new client object only in netinfo

libnmstate/error.py, libnmstate/netapplier.py, libnmstate/nm/applier.py, libnmstate/nm/bond.py, libnmstate/nm/device.py, libnmstate/nm/ipv6.py, libnmstate/nm/nmclient.py, libnmstate/nm/ovs.py, libnmstate/nm/user.py, libnmstate/validator.py, tests/integration/bond_test.py, tests/integration/dhcp_test.py, tests/integration/ethernet_mtu_test.py, tests/integration/vlan_test.py, tests/lib/netapplier_test.py, tests/lib/nm/bond_test.py, tests/lib/validator_test.py
Moving all exceptions into 'error.py' to provide stable API on
error path -- `libnmstate.error.<Exception_Name>`.
The base exception is NmstateError which could be used by application
which want to catch all exceptions in Nmstate.
=> Unify the exception to NmstateError

.travis.yml
The test type should be `lint` instead of `unit_code_style`.
=> Travis CI: Fix the incorrect test type of lint

packaging/Dockerfile.centos7-nmstate-base
The latest docker CentOS has fixed the dbus issue, no need to
do hard coded version anymore.
=> CentOS CI image: Use latest docker image

tests/integration/linux_bridge_test.py
Refactor the Linux bridge tests and show that it supports two ports attached to it.
=> Linux bridge test (with two ports)

.travis.yml
In order to ease the investigation of the integration tests instability,
exit the test run on the first failing test.
=> travis-ci: Exit on first error or failed integration test

automation/Dockerfile.fedora, packaging/Dockerfile.centos7-nmstate-base
The python2-ipaddress will be need by route support.
For Python 3, the ipaddress module is included in CPython 3.3+.
=> Docker CI image: Add python2-ipaddress package

automation/docker_sys_config.sh, packaging/docker_sys_config.sh
Do not create generated connections automatically on all devices in the
test env.
This configuration has been re-introduced due to:
https://bugzilla.redhat.com/1687937
=> automation: Enable no-auto-default on all devices

libnmstate/schema.py, nmstatectl/nmstatectl.py, tests/integration/bond_test.py, tests/integration/examples_test.py, tests/integration/linux_bridge_test.py, tests/integration/ovs_test.py
PyYaml 5.1 has deprecated the usage of yaml.load(input) with the default
loader. It has been accompanied by a message warning.
As the usage of yaml in nmstate is for external input, the loader has
been explicitly set to SafeLoader.
Ref: https://msg.pyyaml.org/load
https://github.com/yaml/pyyaml/commit/0cedb2a0697b2bc49e4f3841b8d4590b6b15657e
=> yaml.load: Explicitly set yaml loader to SafeLoader

tests/integration/bond_test.py
The bond rollback test is set to create a bond successfully and then
fail at the verification step on an unsupported parameter.
The test first reads the current state, applies the desired state and
then checks that the new current state is equal to the old current
state.
With the addition of the routes entries, this test now fails frequently
on the default IPv6 route metric change [1].
1. https://nmstate.atlassian.net/browse/NMSTATE-162
=> integ tests: Skip route versification while testing bonds

automation/Dockerfile.fedora, packaging/Dockerfile.centos7-nmstate-base
This is needed for #307 to ensure that python-dbus is avilable in the containers.
=> Container dbus

libnmstate/error.py, libnmstate/netapplier.py, libnmstate/nm/checkpoint.py, tests/integration/nm/checkpoint.py
Not destroying other checkpoints will make checkpoint creation fail if
there is already a checkpoint for all devices. This prevents other users
to use another instance of Nmstate to change the state while a state
change is in progress.
=> nm/checkpoint: Do not destroy other checkpoints

libnmstate/netinfo.py, libnmstate/nm/dns.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/dhcp_test.py, tests/lib/netinfo_test.py, tests/lib/schema_validation_test.py
Add support of querying DNS client settings
The example output would be:
```yaml
---
dns-resolver:
config:
server:
- 2001::8
- 8.8.8.8
search:
- example.com
- example.org
running:
servers:
- 2001::8
- 8.8.8.8
search:
- example.com
- example.org
```
=>  Add support of querying DNS client settings

libnmstate/netapplier.py, libnmstate/nm/checkpoint.py, nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py, tests/integration/examples_test.py, tests/integration/nm/checkpoint.py, tests/integration/nmstatectl_test.py, tests/integration/testlib/examplelib.py
To help other reviewer, below lines are added by @cathay4t:
This PR introduce a way to allow user commit or rollback a checkpoint manually.
API:
* `libnmstate.netapplier.apply()` support new optional argument `commit=False`.
If set, the function will return a checkpoint object. The checkpoint object could be used for
`libnmstate.netapplier.commit()` or `libnmstate.netapplier.rollback()`
CLI:
* `nmstatectl set <yaml_file> --no-commit` which will print a checkpoint dbus object path.
*  `nmstatctl commit <checkpoint_dbus_obj_path>` or `nmstatctl rollback <checkpoint_dbus_obj_path>`
=> Support manual state verification

packaging/nmstate.py2.spec, packaging/nmstate.py3.spec
Nmstate needs at least libnm 1.12 for checkpoint support.
=> spec files: Require libnm 1.12 or newer

packaging/Dockerfile.centos7-nmstate-base
The NetworkManager cannot manager any interfaces when using CentOS 7.6
docker image.
=> Revert back to CentOS 7.5 due to CI failure

libnmstate/nm/route.py
The `_get_cfg_default_route_table_id()` function is not required as
`ip_profile` is always valid at that point hence the function always
return `ip_profile.props.route_table`.
=> nm/route: Remove unneeded function

tests/integration/testlib/assertlib.py
Currently, all the test cases does not required to check on DNS and
route configuration, hence it should be removed in `assert_state()`.
The route and DNS assertion will be done in their own test cases.
Waits on PR #329 #327 #328
=> Integration test: Ignore route and DNS in assert_state()     

README.md, automation/Dockerfile.fedora, packaging/Dockerfile.centos7-nmstate-base
libibverbs does not seem to be required for openvswitch anymore,
therefore do not install or mention it.
=> packaging: Remove libibverbs dependency

automation/Dockerfile.fedora, automation/run-tests.sh
Udev has stopped working in the Fedora dev image.
It seems that the source is related to a missing systemd-udev package.
The container dockerfile has been updated to include systemd-udev.
In addition, an update has been included to confirm with the systemd
container enablement instructions:
https://hub.docker.com/r/fedora/systemd-systemd/
systemd-udevd is also being started when the container is run and NM is
restarted in order to confirm it loads with udev activated already.
=> automation: Fix Fedora29 dev image

libnmstate/nm/wired.py
Dependent on #325 
nm.wired: Return existing setting instead of nothing
The wired setting is affecting the reapply action when it is missing
from the connection profile [1].
In order to adjust to this behaviour, in cases where no new wired
parameters are mentioned in the desired state and an existing profile
exists, the current wired setting is returned.
1. https://bugzilla.redhat.com/1703960
=> Nm wired return existing

libnmstate/state.py, tests/lib/netapplier_test.py, tests/lib/state_test.py
Complement IPv{4,6} keys in the interface state and assume they are there when processing the state.
The same question should not be asked multiple times.
=> Canonicalize ip subtree

packaging/Dockerfile.fedora-nmstate-dev
Since Fedora 30 was released recently and we did not test it, yet, just
use Fedora 29 for now.
I did a quick manual test, F30 will break the CI:
- The python2 dbus package seems to have gone (at least the lint tests fail because they cannot compile the pypi dbus package)
- The integration tests just failed (aborted after 7 tests)
=> fedora container: Pin to Fedora 29

libnmstate/netapplier.py
netapplier: Optimize new and existing interface processing
The desired state is processed to determine which interfaces are new and
which ones need editing.
This change optimizes the setup flow by not including the new interfaces
in the editation step.
=> Netapplier: Optimize add and edit processing

libnmstate/schema.py, tests/integration/nm/bond_test.py
Use the new constants in the integration bond_test module.
Note: Bond options have not been specified in this change. It is left
for a following change.
=> schema constants: Introduce Bond and BondMode

libnmstate/metadata.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/nm/route.py, libnmstate/schema.py, tests/lib/nm/route_test.py
Support adding non-gateway route via nm/ipv4.py and nm/ipv6.py.
Test case included.
=> Support adding non-gateway route in libnmstate.nm

libnmstate/schema.py, libnmstate/state.py, tests/lib/state_test.py
The `state.RouteEntry` class is intend to be used inside `state.py`
for deduplicating the desire route entires and removing
absent route entries.
=> Add state.RouteEntry class

libnmstate/nm/connection.py, libnmstate/nm/device.py, libnmstate/nm/nmclient.py, tests/integration/nm/ipv4_test.py, tests/integration/nm/testlib.py, tests/integration/nm/wired_test.py
Reapply operation is introduced in the nm provider.
It includes a fallback to a profile activation in case the reapply fails.
Integration into nmstate core is planned in a separate PR.
Dependent on PR #325
=> Introduce nm.device.reapply

libnmstate/metadata.py, libnmstate/netapplier.py, tests/integration/route_test.py, tests/lib/metadata_test.py, tests/lib/netapplier_test.py
Allows adding route entry to existing state with limitations:
* Not support route removal yet.
* Any interface referred as route next hop interface should be
defined interfaces section of desired state.
Example is included at `examples/eth1_add_route.yml`
=> Add support of route addition

.copr/Makefile
This finally fixes the Copr SRPM build, see https://copr.fedorainfracloud.org/coprs/till/nmstate-git-fedora/build/921236/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/373)
=> copr: Detect python version for SRPM deps

.travis.yml
Remove the test instances of CentOS 7 using NetworkManager copr build
which turn out to be time wasting as no one is checking their failures.
=> CI: Remove CentOS 7 copr repo tests

libnmstate/nm/connection.py, libnmstate/nm/device.py, tests/integration/nm/wired_test.py
Introduce a new nm.device operation: `modify`.
Unlike the existing libnm `activate` and `reapply`, this operation is a libnmstate.nm abstraction, introducing a device modification using `reapply` with a fallback to `activate`.
Depends on #332
=> Nm device modify

tests/integration/linux_bridge_test.py
Test that when a Linux bridge is added over an interface,
by default it uses interface's MAC address.
=> tests integ: Test Linux bridge uses port's MAC

tests/integration/nm/ipv4_test.py, tests/integration/testlib/iproutelib.py
Link state monitoring is used to detect link state changes while
executing apply changes. In particular, to detect links that change to
anything but UP.
In order to allow simpler usage in selected tests, a decorator is
introduced in addition to the existing context-manager.
Note: six is used to overcome functools.wraps limitations with pytest
(https://github.com/pytest-dev/pytest/issues/2782)
=> tests integ: Introduce a link state monitor decorator

libnmstate/prettystate.py
With python3 pylint 2.3.1, it will complain about unicode not defined
in `libnmstate/prettystate.py`.
It's a false alarm as when using unicode, the code already checked with
`if six.PY2:`.
To fix this false alarm, just change it to `six.text_type`.
=> pylint: Fix a false alarm

libnmstate/state.py, tests/lib/state_test.py
Introduce `state.verify_dns()` to verify desire DNS configurations with
current.
=> state: Verify DNS configuration

libnmstate/netinfo.py, libnmstate/nm/dns.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py
Use existing generators from the ip modules to fetch the DNS
configuration and by that removing the existing dependency.
=> dns: Remove dns module dependency on ipv{4,6} modules

libnmstate/metadata.py, libnmstate/nm/dns.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, tests/lib/nm/dns_test.py
The DNS configuration will be saved in `metadata.DNS_METADATA` key.
Additional key `metadata.DNS_PRIORITY` is introduced to enforce the DNS
server order(for example, [8.8.8.8, 2606:4700:4700::1111] need DNS
priority to enforce IPv4 server is listed before IPv6 server).
=> nm: Add support of DNS editing

libnmstate/validator.py, tests/lib/validator_test.py
Supporting 3 name server is too complex to implement via libnm:
https://nmstate.atlassian.net/browse/NMSTATE-220
Test case included.
=> validator: Only support up to two DNS name servers.

libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/nm/route.py
The metadata module only required for route metadata string,
saving that string in `nm/route.py` will remove the metadata dependency.
=> nm: Remove ipv{4,6} module dependency on metadata module

libnmstate/nm/dns.py, libnmstate/nm/route.py
Add `nm.dns.get_dns_config_iface_names()` to get a list of interface
names which is currently hold static DNS configurations.
=> nm: Query interface names which hold DNS config

libnmstate/nm/dns.py, libnmstate/nm/route.py, tests/lib/nm/dns_test.py
Choose interface for IPv4/IPv6 default gateway for desired DNS configuration via `nm.dns.choose_interfaces_for_dns_conf()`.
=> nm: Choose interface with default gateway for DNS configuration

libnmstate/__init__.py, nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py, tests/integration/bond_test.py, tests/integration/conftest.py, tests/integration/dhcp_test.py, tests/integration/ethernet_mtu_test.py, tests/integration/iface_admin_state_test.py, tests/integration/linux_bridge_test.py, tests/integration/ovs_test.py, tests/integration/preserve_ip_config_test.py, tests/integration/route_test.py, tests/integration/static_ip_address_test.py, tests/integration/testlib/assertlib.py, tests/integration/testlib/examplelib.py, tests/integration/testlib/statelib.py, tests/integration/vlan_test.py
Moved these public classes and functions to libnmstate module top level:
* The 'show()' function of 'netinfo.py'.
* The 'apply()', 'commit', 'rollback' functions of 'netapplier.py'.
* The exception classes defined in 'error.py' as exposed as
'libnmstate.error'
* The 'PrettyState' class defined in 'prettystate.py' which is used by
nmstatectl.
* The schema classes are exposed as 'libnmstate.schema'.
The integration test cases and nmstatctl has been updated to use this
new public interface.
=> API: Move public staff to libnmstate module top level

examples/dns_edit_eth1.yml, examples/dns_remove.yml, libnmstate/metadata.py, libnmstate/netapplier.py, tests/integration/conftest.py, tests/integration/dns_test.py, tests/integration/examples_test.py, tests/lib/metadata_test.py
Example has been included as `examples/dns_edit_eth1.yml` and
`examples/dns_remove.yml`.
If DNS not defined in desire state, old DNS configuration will be
perceived.
If DNS defined in desire state, old DNS configuration will be fully override
with desired state.
To remove static DNS configuration, Please use this state:
```python
{
DNS.KEY: {
DNS.CONFIG: {
DNS.SERVER: [],
DNS.SEARCH: []
}
}
}
```
Limitation: only support saving DNS configuration to state default
gateway interfaces.
Unit and integration test cases has been included.
=> Add support of DNS editing

packaging/make_srpm.sh
In RHEL/CentOS 7, the `make_srpm.sh` will fail for two reasons:
1. The `set -e` will quit script when `command -v python3` failed.
2. The `[[ -v python ]]` will be true even when `$python` is empty
string.
The fix would be:
1. Add `|| true` to silent the failure.
2. Changed to `[ -n "$python" ]`.
=> make_srpm.sh: Fix script error on EL7

tests/integration/dns_test.py
The DNS tests are using gateway routes with a non-main table.
On Centos/RHEL7 this is not working due to an existing kernel bug.
As the tests do not require the table ID, they are removed in order to
pass the tests on machines running Centos/RHEL7 kernels.
Ref: https://bugzilla.redhat.com/1535977
=> tests integ: Remove non-main table from gateway-route

automation/run-local-utests.sh, packaging/Dockerfile.centos7-nmstate-utest
The unit tests with the lint check can be executed locally
as follow: sudo ./automation/run-local-utests.sh
=> automation: Container image for CentOS7 unit tests

libnmstate/state.py, tests/lib/state_test.py
Then sorting routes containing wildcard, python 3 will raise error:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
The fix is normalize the sorting keys.
Unit test case included.
=> nm/state: Fix route sorting with wildcard routes

tests/integration/route_test.py
Use wildcard absent route to remove old gateway and then add new one:
{
Route.STATE: Route.STATE_ABSENT,
Route.NEXT_HOP_INTERFACE: 'eth1',
Route.DESTINATION: '0.0.0.0/0'
}
=> Integration: Add test case for changing gateway

tests/integration/route_test.py
Add test case for disabling IPv4 with routes in current state.
=> Integration test: Add test case for disable IPv4 with routes

tests/integration/route_test.py
New test case for bring interface down with routes in current next hop to it.
=> Integration test: Add case for bring iface down with routes

libnmstate/metadata.py, libnmstate/netapplier.py, libnmstate/state.py, tests/lib/metadata_test.py, tests/lib/state_test.py
This PR is an attempt to structure the routing handling into individual steps.
Existing handling is overloading the merging operation with route entries merging, touching the interfaces and validating the routes.
The existing route integration tests have allowed a safer refactoring and have not been changed. Unit tests have been introduces with the new merge, metadata and validation changes.
Depends on #411
=> Route refactor

automation/run-tests.sh
Current code is passing copr repo string as `copr_repo` instead of
`$copr_repo`.
=> CI test script: Fix test using copr repo.

tests/integration/bond_test.py
Test that when one or more slaves are added, the bond interface
and its slaves have the same MAC-address. Confirm that the order
of the mentioned slaves is not affecting the MAC-address.
=> tests integ: Test bond iface and slaves have same MAC

libnmstate/metadata.py, tests/integration/dns_test.py
When applying empty state, current DNS edit code will raise exception
for not finding interface. The problem is caused by
the incorrect check on IP entablement.
The integration test case is included for this use case.
=> DNS: Preserve DNS config with empty state

tests/integration/conftest.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py
Bridge tests use `portX` as their name format, abstracting the actual
interface used.
Providing portX alias naming to such tests makes them easier to read and
write.
=> tests integ: Alias ethX_up fixtures to portX_up

libnmstate/netapplier.py, libnmstate/nm/connection.py, libnmstate/nm/nmclient.py
netapplier: Unify the two mainloop runs into one
On apply, two mainloop runs are currently executed: One for adding new
interfaces and another for editing existing ones.
The original reasoning for the separation was the assumption that once
the new interfaces are created, there is a need to refresh the current
state with the new information, serving the editation step.
It seems that the current state refresh is not needed, at least based on
the current test coverage.
Therefore, this change unifies the two mainloop runs into a single one.
In addition, the nmclient.mainloop method that executes the last action is removed
in favour of a simplified recall of the action directly.
=> Mainloop run: Unify run/s and remove execute_last_action

libnmstate/netapplier.py
The mainloop object is a singletone.
When libnmstate is used by an application which calls it multiple times
(e.g. running as a daemon), on mainloop (run) failure, the instance is kept
and reused in the following calls. Unfortunately, when the mainloop run fails,
its state may no longer be usable and may require initialization.
Therefore, to support such usages, the mainloop singletone is initialize
in case a mainloop failure is detected.
=> netapplier: Initialize mainloop global object on failure

tests/integration/bond_test.py, tests/integration/linux_bridge_test.py, tests/integration/testlib/assertlib.py, tests/integration/vlan_test.py
Adding helper function assertMacAddress(), which takes
state and a MAC-address as paramters, and internally
asserts the MAC-address against the state iface's MACs
using a generator.
=> tests integ: MAC address assert helper function

libnmstate/metadata.py, libnmstate/schema.py, libnmstate/validator.py, tests/integration/iface_admin_state_test.py
Defining a desired state for an interface required specifying its type.
When an interface is edited, there is no need to specify its type, as it
may be concluded from checking the current state.
=> state: Make interface type optional

libnmstate/nm/translator.py
The interface could be in `NM.DeviceState.IP_CONFIG` state after
profile activation succeeded.
=> nm: Treat IP_CONFIG state as InterfaceState.UP

libnmstate/nm/ipv6.py
Like DHCP/Autoconf, if IPv6 method is link local, treat it as IPv6 enabled.
=> nm/ipv6: Treat link local method as IPv6 enabled

libnmstate/metadata.py, tests/integration/bond_test.py, tests/lib/metadata_test.py
The existing metadata processing for master-slaves has not handled
correctly scenarios where the slaves are swap between masters.
This change introduces the fix and provides the relevant unit test that
covers it.
=> metadata: Slaves swap between masters

libnmstate/metadata.py, tests/lib/metadata_test.py
When a slave is removed from a master, it needs to be marked as `down`
in order to remove its configuration completly.
In case of the NM provider, its profile is removed.
=> metadata: Remove profile for detached slaves

libnmstate/netapplier.py, tests/integration/bond_test.py, tests/integration/linux_bridge_test.py, tests/lib/netapplier_test.py
Currently, netapplier will do two profile activation/deactivation:
one for new interfaces, another for edited interfaces. Doing so
could cause [newly bridge got no link due to missing slaves][1].
After patched, profiles is activated/deactivation after all profiles are
added and updated.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1723290
=> netapplier: Unify the profile activation/deactivation

libnmstate/state.py, tests/integration/linux_bridge_test.py, tests/integration/testlib/assertlib.py, tests/integration/testlib/statelib.py, tests/lib/state_test.py
When adding port into bridge without stp options, the nmstate will fail the
validation as stp-hairpin-mode and other stp options are missing.
To fix that, when stp is enabled, fill in the default value of stp
options if missing.
=> Verification: Treat missing property as wildcard

libnmstate/nm/ipv4.py, tests/integration/nm/ipv4_test.py
When an existent interface was setup to have DHCP enabled, its
'enabled' criteria was not correct, since it required the interface
to have been assigned an IP addresses.
This patch updates the criteria, setting the interface to enabled
as long as it reports back being configured via DHCP by
NetworkManager.
=> Fix DHCP enabled criteria for interfaces.

libnmstate/netapplier.py, libnmstate/sysctl.py, tests/integration/static_ip_address_test.py
NetworkManager is currently not supporting the ability to disable the
IPv6 stack on the kernel [1].
As an intermediate solution, sysfs is used to control the IPv6 stack.
[1] https://bugzilla.redhat.com/1643841
=> ipv6: Disable the IPv6 stack when explicitly requested

libnmstate/metadata.py, libnmstate/nm/applier.py, tests/integration/linux_bridge_test.py, tests/lib/metadata_test.py
Support the scenario where the master interface is removed but one of its slaves is explicitly left UP.
Currently this scenario results in the deletion of the slave and therefore the transaction fails on the verification step.
The PR solves this at both the metadata level (such slaves are not updated with master metadata) and the admin state update (not removing these slaves).
=> Delete master without slave

libnmstate/metadata.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/schema.py, libnmstate/state.py, libnmstate/validator.py, tests/integration/bond_test.py, tests/integration/conftest.py, tests/integration/dhcp_test.py, tests/integration/dns_test.py, tests/integration/linux_bridge_test.py, tests/integration/nm/ipv4_test.py, tests/integration/ovs_test.py, tests/integration/preserve_ip_config_test.py, tests/integration/route_test.py, tests/integration/static_ip_address_test.py, tests/integration/testlib/statelib.py, tests/lib/metadata_test.py, tests/lib/netapplier_test.py, tests/lib/netinfo_test.py, tests/lib/nm/dns_test.py, tests/lib/nm/ipv4_test.py, tests/lib/nm/ipv6_test.py, tests/lib/nm/route_test.py, tests/lib/state_test.py, tests/lib/validator_test.py
Three class was added:
* `schema.InterfaceIP`
* `schema.InterfaceIPv4`
* `schema.InterfaceIPv6`
=> schema: Add constants for IP subtree

libnmstate/ethtool.py
Replace `array.tostring()` by `array.tobytes()` as it is deprecated in
Python 3.
There is no six functionally helping this yet, so just check the
existence of `array.tobytes()`.
=> ethtool: Fix deprecation of array.tostring()

libnmstate/nm/vlan.py, libnmstate/schema.py, tests/integration/nm/vlan_test.py, tests/integration/vlan_test.py
Add `VLAN` class to `libnmstate.schmea` with these constants:
* `VLAN.TYPE`
* `VLAN.CONFIG_SUBTREE`
* `VLAN.ID`
* `VLAN.BASE_IFACE`
=> schema: Add interface subconfig: VLAN

tests/integration/linux_bridge_test.py
In order to avoid a fallback from reapply to activate, disable IPv6 on a
bridge interface by default.
=> tests integ: Disable IPv6 by default on the bridge

tests/integration/ovs_test.py
Due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1724901 ,
the NetworkManager OVS is not stable enough for CI test,
hence marking OVS tests xfail(allowed to fail).
=> ovs test: Allow OVS test cases to be fail

tests/integration/nm/linux_bridge_test.py
Disable STP to avoid topology changes and the consequence link change.
=> nm/linux_bridge_test: Disable STP for linux bridge test

tests/integration/nm/ovs_test.py
Due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1724901 ,
the NetworkManager OVS is not stable enough for CI test,
hence marking OVS nm tests xfail(allowed to fail).
=> nm/ovs test: Allow OVS test cases to be fail

packaging/Dockerfile.centos7-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, tests/integration/dhcp_test.py
The dnsmasq can send out extra route via RA using `dhcp-rang`,
hence there is not need to depend on radvd any more.
=> DHCP CI Test: Remove the need of radvd.

automation/run-tests.sh
The copr repo ID has changed from:
networkmanager:NetworkManager-master
to
copr:copr.fedorainfracloud.org:networkmanager:NetworkManager-master
=> Test script: Fix the incorrect copr repo ID

tests/integration/examples_test.py
Due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1724901 ,
the NetworkManager OVS is not stable enough for CI test,
hence marking OVS nm tests xfail(allowed to fail).
=> OVS example test: Allow OVS test cases to be fail

tests/integration/linux_bridge_test.py, tests/integration/testlib/vlan.py, tests/integration/vlan_test.py
Test that a VLAN interface has been sucessfully added as a
slave to the Linux bridge.
=> tests integ: VLAN as a slave of Linux bridge

libnmstate/nm/applier.py, libnmstate/schema.py, tests/integration/vlan_test.py
When both the base interface and the VLAN interface are created in one
transaction, the base interface must be activated before the vlan one,
otherwise the VLAN activation fails.
The new VLAN interfaces are now activated after all other new
interfaces.
Solves #461
=> nm.applier: Prioritize base iface activation before the vlan

tests/integration/linux_bridge_test.py
tests integ: Defining VLAN over Linux bridge interface
Test VLAN's behavior when is it defined over Linux bridge
interface.
Note: Only function `test_create_vlan_over_linux_bridge` is an addition in this PR,
rest of the code you see (inserted and deleted) is exactly same as PR #444. Opened a new branch for easier readability and changes than committing on the same branch. Also PR 444 should be merged by now (that way I won’t have to rebase.)
Thank you,
Nandan
=> VLAN over Linux bridge

automation/open_container_shell.sh, libnmstate/ipaddress_extender.py, packaging/build-container.sh
IIUC, the subnet_of function was added *only* in python 3.7, which means we'll need to stick to using the `ipaddress_extender` for a bit longer (RHEL 8 is fedora 28 based, which ships py3.6).
If we don't care about that - e.g. we want to only run on py3.7, we should update the spec file to require py3.7.
=> Relicense last files to LGPL2.1+

libnmstate/nm/active_connection.py, tests/lib/nm/active_connection_test.py
Ignore the failure:
Connection deactivation failed on nm2: error=nm-manager-error-quark: The
connection was not active.
Even we check activate connection status before deactivating, there is
still a small chance that NM deactivated the connection after we
checked.
This patch also fix the random failure of
`test_add_bond_with_slaves_and_ipv4` test when tear down:
* The tear down will delete bond99 and eth1/eth2.
* After bond99 got deleted, the connections of eth1/eth2 will be
brought down automatically by NM.
* There is a small chance(about 1 out of 10) to trigger the problem of
deactivating a non-active connection.
=> nm: Ignore not active failure when deactivate

libnmstate/nm/bond.py, libnmstate/nm/ovs.py
=> nm: Fix incorrect error string.

libnmstate/netapplier.py, tests/integration/linux_bridge_test.py
Increase the mainloop timeout from 20 seconds to 35 seconds.
When creating new bridge with ipv6 enabled with empty address,
the bridge activation will wait on link up which require 30 seconds for
STP to add first interface to the bridge.
=> nm: Increase main loop timeout

tests/integration/dhcp_test.py
Since NetworkManager 1.20, veth interface will be marked as
unmanaged by default, need explicitly set it as managed via command:
sudo nmcli device set <nic_name> managed yes
=> Integration test: Explicitly set DHCP CLI NIC as managed by NM

tests/integration/linux_bridge_test.py, tests/integration/testlib/bridgelib.py
Extract the Linux Bridge helpers from the linux_bridge_test module in
order to reuse them in other tests.
=> tests integ: Introduce the bridgelib module

tests/integration/bond_test.py, tests/integration/testlib/bondlib.py
Extract the bond creation function to a dedicated module, enabling
it to be re-used in other tests.
=> tests integ: Introduce the bondlib module

libnmstate/nm/applier.py, tests/integration/linux_bridge_test.py, tests/integration/testlib/bondlib.py, tests/integration/testlib/bridgelib.py
The master interfaces must be activated first, otherwise
NetworkManager fails with errors such as:
"""
NetworkManager[858]: <debug>
[1565960861.2223] manager: Activation of <slave> requires master
device <master device>
"""
Depends on: #491 
Fixes: https://bugzilla.redhat.com/1749314
=> nm.applier: Prioritize master interfaces activaction

libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, packaging/Dockerfile.centos7-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, packaging/docker_sys_config.sh, tests/integration/dhcp_test.py
When enslave interface to linux bridge, to ensure the bridge
get the same IPv6 address from IPv6-RA and DHCPv6, change
the 'dhcp_duid' to LL(Link-layer address, RFC 3315) and
'addr_gen_mode' to EUI64.
For DHCPv4, change the DHCP client ID to the MAC address of interface.
=> Enforce auto IP address to be based on MAC address.

tests/integration/nm/testlib.py
CI tests have been failing on timeout when running the nm bridge tests.
This may be caused by slow CI slaves.
=> tests, integ: Increase the nm test mainloop timeout

libnmstate/netapplier.py
When certain interface is marked as down or absent, we should not
try to disable its IPv6.
=> netapplier/ipv6: Don't disable IPv6 on down interface

packaging/Dockerfile.centos7-nmstate-dev
On CentOS7, the dhclient package name is `dhclient`.
=> packaging, centos7: Fix dhclient package name

tox.ini
As can be seen in the following builds, the unit tests w/ code
coverage ran with the currently defined pytest version - 4.1.0 -
are failing.
- https://travis-ci.org/nmstate/nmstate/builds/592672701
- https://travis-ci.org/nmstate/nmstate/builds/592993079
Updating the pytest version to 4.3.0 makes the unit tests pass.
The error thrown by the unit test framework is:
check-py36 runtests: commands[0] | pytest --log-level=DEBUG --durations=5 --cov=libnmstate --cov=nmstatectl --cov-report=term --cov-report=html:htmlcov-py36 lib ctl
File "/tmp/nmstate/.tox/check-py36/bin/pytest", line 10, in <module>
sys.exit(main())
File "/tmp/nmstate/.tox/check-py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 61, in main
config = _prepareconfig(args, …
=> tox: update pytest version to fix unit tests w/ html code coverage

libnmstate/netapplier.py, libnmstate/nm/ipv6.py, libnmstate/nm/nmclient.py, tests/lib/nm/ipv6_test.py
Use the SETTING_IP6_CONFIG_METHOD_DISABLED to disable IPv6.
That is only available for NM 1.19.3+.
=> nm: Support disabling IPv6 via libnm

libnmstate/nm/nmclient.py
As per issue 'NMSTATE-78', nmstatectl should provide an error that NetworkManager is required.
I left a TODO comment as probably documentation has to be edited accordingly.
I quickly tested it on my RHEL8 VM with NM not running (libnm package installed):
[root@fastvm-rhel-8-0-175 nm]# systemctl stop NetworkManager
[root@fastvm-rhel-8-0-175 nm]# 
[root@fastvm-rhel-8-0-175 nm]# nmstatectl show
2019-08-22 11:26:08,198 root         ERROR    NetworkManager is in unknown state, please make sure NetworkManager is installed and running.
Check the documentation for more information.
File "/usr/local/bin/nmstatectl", line 11, in <module>
load_entry_point('nmstate==0.0.8', 'console_scripts', 'nmstatectl')()
File …
=> nmstatectl provides an error if NetworkManager is not running

packaging/Dockerfile.centos7-nmstate-base
Fix the incorrect script path:
Wrong:      docker_sys_config
Correct:    docker_sys_config.sh
Use  copr repo `nmstate/ovs-el7` for openvswitch as it has been removed from base repo since RHEL/CentOS 7.7.
=> test: Fix centos7-nmstate-base container

packaging/Dockerfile.centos8-nmstate-dev, packaging/build-container.sh
Added the CentOS 8 test container with NetworkManager 1.20 and
openvswitch 2.11 installed from copr repo.
The travis CI test has been explained to include tests on CentOS 8.
=> test: Add CentOS 8 test container

tests/integration/nm/ovs_test.py, tests/integration/nm/testlib.py, tests/integration/nm/wired_test.py
pytest tries collect tests from `TestMainloopError` as a test case since
it starts with `Test`, possibly resulting in warnings. Therefore rename
the Exception to avoid this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/535)
=> testlib: Rename TestMainloopError to MainloopTestError

packaging/Dockerfile.centos7-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, tox.ini
The existing pytest* packages used by the container images are broken,
therefore, they are upgraded with this change to the latest (py2
compatible) version.
=> packaging, tox: Upgrade pytest and pytest-cov

pyproject.toml, tox.ini
Use pyproject.toml for Nmstate's custom black configuration to allow to
use it to automatically to re-format files without remembering the
special options.
Reference: https://black.readthedocs.io/en/stable/pyproject_toml.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/536)
=> linting: Configure black via pyproject.toml

libnmstate/netapplier.py, libnmstate/nm/ipv6.py, libnmstate/nm/nmclient.py, packaging/Dockerfile.centos7-nmstate-base, tests/integration/nm/testlib.py, tests/lib/nm/ipv6_test.py, tox.ini
Use the SETTING_IP6_CONFIG_METHOD_DISABLED to disable IPv6.
That is only available for NM 1.19.3+.
=> [stable_v0.0.8] nm: Support disabling IPv6 via libnm

.github/CODEOWNERS
Usernames need to be prefixed with at-signs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/541)
=> github: Fix CODEOWNERS syntax

libnmstate/schema.py, libnmstate/state.py, tests/integration/interface_common_test.py, tests/lib/state_test.py
Allows description removal by setting an empty description. We need to
delete the description element from the desired state after being
applied.
=> netapplier: allow description removal

.gitignore
When the unit_py37 test fails it generates the coverage under the
htmlcov-py37 directory. We do not want to track this on git.
=> gitignore: ignore htmlcov-py37 directory

automation/run-tests.sh
As we run the test in the `/tmp/nmstate` after copy `/workspace/nmstate` to
`/tmp`, the coverage files are stored in `/tmp` folder which does not
get collected to the website for report.
The fix is copy coverage files to `/workspace/nmstate` folder if in CI
environment.
=> test coverage: Fix code coverage report

libnmstate/state.py, requirements.txt, tests/integration/static_ip_address_test.py, tests/integration/testlib/statelib.py, tests/lib/state_test.py
Setting a static IP address on an interface fails, since it is reported by nmstate in the canonical format, as per [0].
The failure happens in nmstate's *verify* stage - since the desired state is expressed in the expanded notation, and the current state in the canonical notation, nmstate considers the IPs to be different, and an automatic rollback is used.
This patch addresses the aforementioned issue by canonicalizing (compressing) the static ipv6 address in the desired state.
The issue can be triggered w/ the following yaml:
```yaml
interfaces:
- name: eth1
type: ethernet
state: up
ipv4:
enabled: false
ipv6:
address:
- ip: 2001:0db8:85a3:0000:0000:8a2e:0370:7331
prefix-length: 64
enabled: true
```
Ref: https://bugzilla.redhat.com/1760800
[0] - …
=> Compress static IPv6 addresses

tests/integration/dynamic_ip_test.py, tests/integration/ethernet_mtu_test.py, tests/integration/iface_admin_state_test.py, tests/integration/preserve_ip_config_test.py, tests/integration/static_ip_address_test.py, tests/integration/testlib/assertlib.py, tests/integration/testlib/statelib.py, tests/integration/testlib/vlan.py, tests/integration/vlan_test.py
INTERFACES constant from statelib is deprecated and should not be used
anymore. Instead, use Interface.KEY from the schema module.
=> tests, integ: deprecate INTERFACES constant from statelib

packaging/Dockerfile.centos8-nmstate-dev
The rpm pytest does not works well with pip installed pytest-cov,
hence use pip to install both pytest and pytest-cov.
=> test container: Fix CentOS 8 dev container

libnmstate/nm/ipv6.py
At the verification stage when disabling IPv6, the interface might still
have running IPv6 `NM.IPConfig` attached which turn out to be shown as
```yaml
ipv6:
address: []
autoconf: false
dhcp: false
enabled: true
```
The fix is check in-config method of IPv6, if disabled, return with
disabled IPv6 information.
=> nm ipv6: Fix race problem when IPv6 is disabled

libnmstate/nm/ovs.py
The 'test_bridge_with_internal_interface' test case of 'nm/ovs_test.py'
might fail randomly on line:
assert not _get_bridge_current_state()
Where _get_bridge_current_state() should return {}.
But when OVS bridge is deleting, libnm might still have the NMDevice
object for the bridge while it has empty data in it, in that case,
we got:
{
'bridge': {
'port': [],
'options': {}
}
}
The fix is treat above data as not exists interface and return {}
instead in `get_bridge_info()` of `nm/ovs.py`
=> nm ovs: Handle race problem when OVS bridge is deleting

libnmstate/nm/bond.py
The test `test_bond_with_a_slave` of `nm/bond_test.py` will fail on
AssertionError: assert not {'options': {}, 'slaves': []}
Due to the race of doing nm/bond.py get_info() against newly deleted
bond interface.
In order to fix the above scenario, treat the data as if the interface
does not exist and return `{}`.
=> nm bond: Handle bond get_info() while deleting

tox.ini
Black formatter updates may empose new rules which require changes in
the project code.
In order to control this, the black version is fixed.
From time to time the version needs to be updated and with it adjusting
the code.
=> tox: Statically specify black version

examples/ovsbridge_create.yml, libnmstate/nm/ovs.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/nm/ovs_test.py, tests/integration/testlib/ovslib.py, tests/lib/metadata_test.py, tests/lib/nm/ovs_test.py
OVS port "type" attribute is redundant. It can be currently set to "system" or "internal", but these can be easily deduced from desired and current state. I propose we drop this attribute from the API, so we don't keep redundant information and make schema more streamlined.
No other nmstate interface type requires users to specify slave type (both bond and linux-bridge require the name only).
OVS bridge schema would change from:
```yaml
interfaces:
- name: ovs-br0
type: ovs-bridge
state: up
bridge:
port:
- name: eth3
type: system
```
To:
```yaml
interfaces:
- name: ovs-br0
type: ovs-bridge
state: up
bridge:
port:
- name: eth3
```
https://nmstate.atlassian.net/browse/NMSTATE-248
Note that no changes were needed to implement this, apart from dropping the "type" from reporting, schema and …
=> drop OVS port's "type" attribute

libnmstate/nm/device.py, libnmstate/nm/nmclient.py, tests/integration/ethernet_mtu_test.py, tests/integration/nm/wired_test.py
Support reapply on MTU changes as it is supported by NetworkManager
again.
Ref: https://bugzilla.redhat.com/1702657
=> nm.device: support reapply on MTU changes

libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, libnmstate/validator.py, tests/lib/schema_validation_test.py, tests/lib/validator_test.py
schema: add linux bridge vlan filtering
The defined model allows for setting trunk and access ports.
Furthermore, it allows defining a native vlan on a trunk port.
It is possible to independently define the trunks/access vlans per each port, and while NM / linux bridges allows it, at the moment, we will not allow setting allowed vlans on the bridge port.
It will be hardcoded with the linux bridge default: having vlan id 1 as native vlan.
Defining the schema of the uplink port will be done in a separate subsequent PR.
This patch adds to the model:
- a 'vlan' map to the bridge ports, that will hold a list trunk tag (that can be individual tags, or tag ranges), an access tag - to be used for access ports - and an 'enable-native' flag, intended to select one of the trunk tags as native vlan. …
=> schema: add linux bridge vlan filtering

tox.ini
Show the necessary diff to make black pass to make it easier to
understand why black failed and to allow contributors to fix the code
without having to run black themselves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/565)
=> tox/black: Output diff for black check

.environment.yaml
Set CI environment variable as travis did for STDCI. The run-test.sh
script uses it.
Pulled out from #543
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/564)
=> test stdci: Set CI environment variable

automation/run-tests.sh
When the script fails without running any tests, it is hard to find the
actual failure. Print a marker before the teardown starts to make it
easier to locate the last line that triggered the error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/567)
=> run-tests: Print a separator when the script fails

libnmstate/nm/device.py
When IPv6 is disabled, interface can use `reapply()`
=> nm device: Treat disabled IPv6 as OK to reapply

.travis.yml
Since the CI keeps failing on Fedora, only use CentOS 8 images for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/580)
=> Travis: Make CentOS 8 test the canonical tests

.environment.yaml, .stdci.yml, automation/run-tests.environment.yaml
Use CentOS 8 for stdci because the Fedora tests are currently
meaningless. Since CentOS 8 only supports the integration tests for now,
run only the integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/582)
=> stdci: Use CentOS 8

tox.ini
The environment was removed earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/585)
=> tox: Remove check-py27 from envlist

automation/run-tests.sh
~~The 'nmcli con' might(30% chances) hang for 10+ minutes when we dumping
network information before exit.~~
~~This fail our CI tests and the information it provides is not helpful
in most case.~~
In CI system, the `nmcli con` will use pager(less) when the text length exceeded
80 which cause the command hang for 10 minutes.
Set $PAGER environment variable as empty string will fix this.
=> test ci: Fix the hang of nmcli command

libnmstate/nm/active_connection.py, libnmstate/nm/connection.py, tests/integration/linux_bridge_test.py
Treat virtual device `IP_CONFIG` state as activation finished.
Previously, the code only hook on 'state-change' signal of
active connection which is not sufficient to track the device
state of `IP_CONFIG`. This patch add code to hook on 'state-change'
signal of device.
=> Don't block on DHCP when activating virtual device

.travis.yml, packaging/Dockerfile.fedora-nmstate-dev, tests/integration/dynamic_ip_test.py, tests/integration/linux_bridge_test.py, tests/integration/nm/ovs_test.py, tests/integration/ovs_test.py, tests/integration/testlib/env.py, tests/integration/testlib/ifacelib.py
Both Fedora 31 and CentOS 8 test image are using NetworkManager 1.20 which is the NetworkManager version we officially support.
CentOS 7 is not supported any more and hence travis CI will not run test on it.
This PR contains patches to allow CI to pass on Fedora 31 and CentOS 8 containers.
=> Upgrade travis test base to Fedora 31 and CentOS 8

libnmstate/nm/active_connection.py
The `ActiveConnection.is_activating` is overlapping
with `ActiveConnection.is_active` when master interface
in IP_CONFIG mode, overlap removed by this patch.
=> nm: Fix ActiveConnection.is_activating

libnmstate/nm/translator.py, tests/lib/nm/translator_test.py
In `nm/active_connection.py`, the `ActiveConnetion.is_active`
treat device state between IP_CONFIG and ACTIVATED as activated,
while at the query stage, the nm/translator.py only treat
IP_CONFIG and ACTIVATED as `InterfaceState.UP`, not between.
=> nm device: Fix the incorrect interface state

tests/integration/conftest.py
The `preserve_old_config` fixture fails when Nmstate reports a
configuration that it cannot set, for example a gateway together with
DHCPv6 and autoconf. If someone needs to restore a certain network state
after running the tests, they need to use a custom wrapper/script to do
so.
References:
https://lists.fedorahosted.org/archives/list/nmstate-devel@lists.fedorahosted.org/thread/XFMPA5IMYCQCDWUSSNGVDBQA7BKB2N3N/
https://nmstate.atlassian.net/browse/NMSTATE-275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/588)
=> integration tests: Remove preserve_old_config fixture

.travis.yml, automation/run-tests.sh
The first commit allows to run multiple containers at once without error messages regarding the docker networks. The other commits also prepare run-tests.sh to be used with podman.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/577)
=> Prepare run-tests.sh for podman

libnmstate/state.py, tests/lib/state_test.py
When desire contain extra IP information when IP disabled,
the verification will fail.
For example:
desire:     {'enabled': False, 'dhcp': False}
current:    {'enabled': False}
The verification should pass on the above use case.
The fix is remove the whole IP stack before verification when disabled.
A unit test case has been added for this use case.
=> nm/state: Discard IP stack when disabled for verification

libnmstate/nm/active_connection.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, tests/integration/dynamic_ip_test.py
Previously we don't block activation on DHCP/Autoconf for
master interfaces, now we expand that to all interface types.
Test case added for activating DHCP/Autoconf on dummy interface.
=> nm: Don't block activation on DHCP/Autoconf for all interface types

libnmstate/nm/applier.py, libnmstate/nm/connection.py, tests/integration/profile_test.py
When editting an interface that doesn't have an active profile we are
creating a new profile. Now, we are deleting all the inactive profiles
of an interface before creating the new one.
=> nm.device: delete inactive profiles when editting an interface

libnmstate/nm/bridge.py, tests/integration/linux_bridge_test.py
When the port vlan feature is used, raise NmstateNotImplementedError.
=> linux bridge, port vlan: raise not implemented error

libnmstate/validator.py, tests/lib/validator_test.py
Using the currently defined schema, a trunk port *must* feature
at least 2 trunk tags, otherwise, it is impossible to identify the
correct port type when reading from NetworkManager via libnm.
This patch updates the validator accordingly.
=> vlan filtering, validator: a trunk port must have at least one vlan tag

libnmstate/netinfo.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/lib/netapplier_test.py, tests/lib/netinfo_test.py, tests/lib/schema_validation_test.py
Providing basic support of routing rule support:
```yml
route-rules:
config:
- ip-from: 192.168.3.2/32
ip-to: 203.0.113.1
priority: 30000
route-table: 200
- ip-from: 2001:db8:b::/64
ip-to: 2001:db8:a::/64
priority: 30000
route-table: 200
```
Test case included also.
=> schema: Add basic support of routing rule

tests/integration/interface_common_test.py
Mark `test_take_over_virtual_interface_then_remove` as OK
to fail as current code skip the device deletion when
`NM.Device` in `DEACTIVATING` state.
Jira issue created for tracking this issue:
https://nmstate.atlassian.net/browse/NMSTATE-277
=> test: xfail test_take_over_virtual_interface_then_remove

automation/run-tests.sh
The race between `NM.Device.set_managed()` and
device activation could cause activation failure
with error:
The device 'eth1' has no connections available
for activation.
And there is no good solution tile NM 1.22 released
with `NM.Device.set_managed_async()` function.
Issue can be tracked by:
https://nmstate.atlassian.net/browse/NMSTATE-279
=> test: Explicitly set test NICs as managed by NM

libnmstate/nm/device.py, tests/integration/interface_common_test.py
Even when device is in DEACTIVATING state, still invoke
`NM.Device.delete_async()`.
=> test: Explicitly delete device even in DEACTIVATING state

libnmstate/error.py, libnmstate/nm/applier.py, libnmstate/nm/connection.py, libnmstate/nm/sriov.py, libnmstate/nm/wired.py, tests/integration/sriov_test.py
This patch adds basic SR-IOV support in nmstate. It is possible to
retrieve and set the total number of VFs per PF.
=> nm.sriov: SRIOVSetting implementation

libnmstate/nm/bridge.py, libnmstate/schema.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/testlib/bridgelib.py, tests/integration/testlib/statelib.py, tests/lib/schema_deprecation_test.py, tests/lib/schema_validation_test.py, tests/lib/validator_test.py
Move constant to LinuxBridge.Port, LinuxBridge.STP and OVSBridge.Port
classes. Create DeprecationWarnings when the old constants are used.
@EdDev this is an example about how we could change/deprecate the constants. I did this only for the LinuxBridge.Port constants for now but if you agree with this approach, it can easily be done for the other candidates as well. Also change the constants in our CI is missing and the API guide needs to be updated afterwards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/608)
=> schema: Unify schema hierarchy

libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/nm/ovs_test.py, tests/lib/schema_validation_test.py
Sync the OVS bridge port vlan schema with the one of the Linux bridge.
As the port vlan has never been implemented, this change is backward
safe and requires no production code changes.
=> schema, ovs: Change bridge VLAN schema

libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, libnmstate/validator.py, tests/integration/linux_bridge_test.py, tests/lib/schema_validation_test.py, tests/lib/validator_test.py
Most references to the vlan access/trunk term are using the
name `vlan.mode`.
Therefore, `type` is changed in this context to `mode`.
As the implementation is not yet in, this change is backward safe.
=> schema, bridge: Change vlan.type to vlan.mode

libnmstate/state.py, tests/lib/state_test.py
Add `RouteRuleEntry` class to represent an entry of routing rule and
also supports sorting and hashing.
As `RouteRuleEntry` shares many functions with `RouteEntry`, the `StateEntry` class has been created to be the parent of both.
=> state: Add RouteRuleEntry class

libnmstate/metadata.py, libnmstate/netapplier.py, libnmstate/state.py, tests/integration/route_test.py, tests/lib/metadata_test.py
Allowing changing routing rule using:
```yml
route-rules:
config:
- ip-from: 192.168.3.2/32
ip-to: 203.0.113.1
priority: 30000
route-table: 200
- ip-from: 2001:db8:b::/64
ip-to: 2001:db8:a::/64
priority: 30000
route-table: 200
```
The routing rule will be stored in the interface which contains
static routes with the same route table ID of the rule.
Limitations:
* Does not support querying running routing rule yet.
* Does not support partial editing on routing rule.
=> Add support of routing rule

.travis.yml
The NM 1.20.6 shipped in Fedora 31 is not stable enough to block CI
results.
=> test: Mark Fedora 31 integration test as optional

libnmstate/schema.py
The object inheritance was needed in the schema classes in order to
support python2. Now it is not needed anymore.
=> schema: remove object inheritance

libnmstate/nm/active_connection.py, libnmstate/nm/checkpoint.py, libnmstate/nm/connection.py, libnmstate/nm/nmclient.py, libnmstate/nm/translator.py, libnmstate/nm/wired.py, libnmstate/prettystate.py, libnmstate/state.py, tests/integration/testlib/iproutelib.py, tests/integration/testlib/ovslib.py, tests/integration/testlib/statelib.py, tests/lib/metadata_test.py, tests/lib/nm/applier_test.py, tests/lib/nm/wired_test.py, tests/lib/schema_validation_test.py, tests/lib/state_test.py, tests/lib/validator_test.py
In Python 3, all classes inherit from object implicitly. There is no
need to do this explicitly anymore.
This is a follow-up on #616
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/621)
=> Python: Do not inherit from object explicitly

libnmstate/netapplier.py, libnmstate/state.py, tests/lib/state_test.py
Skip editing on unknown type interface by introduce
`State.remove_unknown_interfaces()` function to remove interface with
unknown type.
=> nm applier: Skip editing on unknown type interface

tests/lib/netapplier_test.py
Change the desire state to use `InterfaceType.DUMMY` as unknown
interface will be removed from editing.
=> nm test: Fix test_iface_admin_state_change

tests/lib/schema_validation_test.py
The schema unit test fail on python3-jsonschema-2.6.0 with error:
assert '48000 is greater than the maximum of 4095' in "{'name':
'br0', 'state': 'up', 'type': 'ovs-bridge', 'bridge': {'port':
[{'name': 'eth1', 'vlan': {'mode': 'access', 'trunk-tags': [],
'tag': 48000}}]}} is not valid under any of the given schemas"
This is caused by python3-jsonschema-2.6.0 changed its error message.
This patch removed the assertion on jsonschema error message as we
should not assume the error message of is stable.
=> schema test: Remove assertion on jsonschema error string

.travis.yml
NetworkManager 1.22 was branched. Add it to Travis. Since the tests on
Fedora are not as stable, use CentOS 8 to test it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/630)
=> Travis: Test CentOS against NM 1.22, too

libnmstate/state.py, tests/lib/state_test.py
When comparing two state with route rules to 2+ route tables,
the `verify_route_rule()` might fail due to the unsorted keys of
indexed route rules.
Unit test case added.
=> state route rule: Fix verify_route_rule()

libnmstate/nm/device.py, tests/integration/static_ip_address_test.py
Support reapply on IPv6 changes as it is supported by NetworkManager
again. In addition, we are supporting the workaround if the
NetworkManager version is lower than 1.20.
=> nm.device: support reapply on IPv6 changes

libnmstate/nm/connection.py, libnmstate/nm/device.py, tests/integration/dynamic_ip_test.py
Current code will wait on existing NM.ActiveConnection if found which
cause nmstate cannot disable IP stack with on-going DHCP.
Since we just updated/created profile(NM.RemoteConnection), we cannot
tell whether existing NM.ActiveConnection is the using to the desired
updated profile, hence do explicit activation regardless current
activation status.
Fix bug: https://bugzilla.redhat.com/show_bug.cgi?id=1782686
=> nm activation: Do explicit activation

.travis.yml
This allows to use coveralls for integration test coverage and codecov
for everything else in the future.
=> Travis: Enable codecov

libnmstate/ethtool.py
Python 3 deprecated `array.array.tostring()`, `.tobytes()` should be
used.
=> ethtool: Remove Python2 specific code

MANIFEST.in, pyproject.toml
Fedora is going to use this information in the future.
References:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/LB3GTGGWEKBT2QWOB77XQ3WXEWN4XRUK/
https://www.python.org/dev/peps/pep-0518/#build-system-table
=> pyproject.toml: Add PEP 508 specifications

libnmstate/schemas/operational-state.yaml
Infiniband MAC addresses have the following format:
80:00:02:08:FE:80:00:00:00:00:00:00:F4:52:14:03:00:61:AA:91
This patch change the schema "mac-address" pattern in order to match
this format too.
=> schema: Fix MAC address pattern

libnmstate/nm/checkpoint.py
The checkpoint module is using dbus directly.
The current implementation uses a global dbus connection, however, if
NM service is restarted, this connection needs to be refreshed.
As the checkpoint is the only client of the dbus connection, the dbus
connection is now initialized on each instantiation of the checkpoint
object.
=> nm.checkpoint: Initialize the dbus connection per instance

libnmstate/metadata.py, libnmstate/state.py, tests/lib/metadata_test.py
When editing bridges, ports which are not managed or have an unknown
type should not be consumed by nmstate.
The issue has been observed when tap devices have been connected to the
bridge and its editation caused nmstate to implicitly define them.
=> metadata: Ignore existing unmanaged and unknown type ports

automation/run-tests.sh, packaging/Dockerfile.fedora-nmstate-dev, tox.ini
This patch introduces python 3.8 support for unit tests.
=> tests: add unit tests definitions for python 3.8

tests/integration/dynamic_ip_test.py
The `test_slave_ipaddr_learned_via_dhcp_added_as_static_to_linux_bridge`
test case will fail with no static IPv4 address assigned to bridge.
Since the `libnmstate.apply()` will return on IP_CONFIG state for DHCP,
at the time of checking slave interface DHCP IPv4 addresses, there is no
IPv4 addresses assigned to the slave interface yet, hence no static
address for assigning to bridge.
Fix by polling on DHCPv4 IPv4 address.
=> test: Polling on linux bridge DHCP address.

libnmstate/state.py, tests/lib/state_test.py
A bridge type interface state includes the `bridge` subconfig only if it
is in an UP state.
When a bridge exists on the system but has no NM profile, it will appear
with state DOWN and will miss the bridge subconfig tree.
When parsing the current bridge interfaces, ignore the ones that their
state is not UP.
=> state: Fix bridge type interface state parsing

libnmstate/nm/sriov.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/sriov_test.py, tests/lib/schema_validation_test.py
This PR is going to extend SR-IOV in order to support VF configuration with nmstate.
=> schema, nm.sr-iov: extend SR-IOV VF configuration

.stdci.yml
=> STDCI: Use Fedora 30 since 29 is EOL

tests/integration/ovs_test.py, tests/integration/testlib/ovslib.py
Now it is possible to set the mac address of an ovs-interface.
Depends on #664
=> tests: ovs interface set mac test

packaging/Dockerfile.centos8-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev
To avoid name squatting attacks/problems it is necessary to specify the
container registry when specifying a container image. Otherwise an image
with the same name from a different registry could be obtained. This
needs to be fixed in `run-tests.sh` and `.travis.yml` as well but needs
special care to ensure that rebuilding containers locally still works.
References: https://raesene.github.io/blog/2019/09/25/typosquatting-in-a-multi-registry-world/
=> Container: Specify registry for container images

tests/integration/ethernet_mtu_test.py
This bug have been already fixed. This test checks that nmstate can set
a mtu lower than 1280 when IPv6 is not enabled.
Ref: https://bugzilla.redhat.com/1753128
=> tests: set a mtu lower than 1280

.travis.yml
Codecov does not seem to properly support multiple jobs but coveralls
does. Therefore use codecov for the CentOS 8 integration tests and
coveralls for everything else.
=> Travis: Switch codecov with coveralls

README.install.md, packaging/README.release.md
Add tarball verification and install instructions in README files.
=> release, install: add tarball install verification

libnmstate/netapplier.py, libnmstate/netinfo.py, libnmstate/nm/checkpoint.py, libnmstate/nm/connection.py, libnmstate/nm/nmclient.py, tests/integration/mem_leak_test.py, tests/integration/nm/bond_test.py, tests/integration/nm/ipv4_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/nm/ovs_test.py, tests/integration/nm/route_rule_test.py, tests/integration/nm/vlan_test.py, tests/integration/nm/vxlan_test.py, tests/integration/nm/wired_test.py, tests/integration/vlan_test.py
In NM 1.22, NM.Client require explicitly clean via
`NM.Client.get_context_busy_watcher()`.
Created `class libnmstate.nm.nmclient._NmClient()` with
`__del__()` to do the proper clean up.
=> nm/nmclient: Fix the leak of NM.Client

tests/integration/mem_leak_test.py
During repeat run of test `test_libnmstae_show_fd_leak`, it might
fail on the mismatch of opened file descriptors. Add a small(0.1 second)
sleep get it pass 100 times repeat tests.
=> test memory: Wait 0.1 seconds for proc to be updated

tests/integration/dynamic_ip_test.py, tests/integration/interface_common_test.py, tests/integration/nmstatectl_edit_test.py, tests/integration/nmstatectl_test.py, tests/integration/ovs_test.py, tests/integration/preserve_ip_config_test.py, tests/integration/profile_test.py, tests/integration/testlib/cmdlib.py, tests/integration/testlib/iprule.py, tests/integration/vxlan_test.py
The `testlib.cmd` module is imported under a custom name because `cmd`
is too generic. Rename it to `cmdlib` to follow other sub libs in
`testlib`.
=> Integration tests: Rename cmd to cmdlib

packaging/Dockerfile.centos8-nmstate-dev, packaging/nmstate.spec
Since CentOS 8.1 is out, we do not need the python3-dbus workaround
anymore. It now contains a fixed package.
=> packaging: Remove python3-dbus workaround

libnmstate/nm/nmclient.py
nmclient: Remove client creation/deletion logging
The existing client logging is overloading the log.
Therefore, this change removes them.
```
2020-01-27 22:54:54 nmclient.py:249 DEBUG NM.Client created
2020-01-27 22:54:54 nmclient.py:311 DEBUG NM.Client cleaned
2020-01-27 22:54:54 nmclient.py:249 DEBUG NM.Client created
2020-01-27 22:54:54 nmclient.py:311 DEBUG NM.Client cleaned
2020-01-27 22:54:54 nmclient.py:249 DEBUG NM.Client created
```
=> nmclient: Remove client creation/deletion logging

libnmstate/nm/applier.py, libnmstate/nm/ovs.py
OVS ports and interfaces have been interpreted by parsing the current
state instead of fetching it from the NM device.
Now that the `get_slaves` function is available (from NM 1.14), the
parsing and the hard-coded port name prefix assumptions are no longer
needed.
Note: The hard-coded prefix of the ovs ports names limited changes to
their name format in the future. The current change allows future
changes to the port names, keeping backward compatibility.
=> nm, ovs: Learn the ovs bridge ports and ifaces from NM

libnmstate/nm/connection.py
Logging the connection settings is no longer useful for debugging in
most cases.
These loggings are remove to make the log easier to read and examine.
=> nm, connection: Remove logging of connection settings

.stdci.yml, automation/README.md, automation/run-tests.environment.yaml, automation/run-tests.mounts, automation/run-tests.packages
oVirt STDCI has been optional for some time now and we rarely look at
its results.
Therefore, there is no point in keeping them running.
=> stdci: Remove oVirt STDCI

nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py
Use keyword arguments for API functions in case they will become
keyword-only in the future.
=> Nmstatectl: Use keyword arguments

tests/integration/conftest.py, tests/integration/ovs_test.py
This patch is going to avoid connectivity issues during the package
installation when running tests.
=> integ: download plugin packages before running the tests

packaging/Dockerfile.fedora-nmstate-dev
As we are going to support NetworkManager 1.22 we are testing now on
Fedora rawhide instead of Fedora 31.
=> automation: upgrade fedora container image to F32

.travis.yml, automation/run-tests.sh, tox.ini
The `--sitepackages` tox argument could instruct tox to use OS installed
python site packages for nmstate dependencies instead of pip installed
one.
=> Travis: Run unit tests on CentOS 8 CI image

libnmstate/netapplier.py
CI tests have frequently failed on the `test_dhcp4_with_static_ipv6`
test, missing the IPv6 address.
This change assumes that such problems occur due to the kernel or NM
client cache not updating fast enough, therefore, a small sleep period
is added before the verification step.
=> netapplier: Wait before the verification step

libnmstate/netapplier.py, libnmstate/nm/nmclient.py
Convert the existing delay before the verification step with a delay in
the mainloop graceful termination.
=> netapplier, mainloop: Delay the exit from the mainloop run

libnmstate/nm/ipv6.py, packaging/Dockerfile.fedora-nmstate-dev, packaging/docker_sys_config.sh
Use dhcp-iaid=mac for IPv4 and IPv6 dynamic address.
=> Dynamic: Use dhcp-iaid introduced in NM 1.22

libnmstate/nm/applier.py, libnmstate/nm/ovs.py, tests/integration/ovs_test.py, tests/integration/testlib/nmlib.py, tests/integration/testlib/ovslib.py
When an interface that is connected to an OVS bridge is removed, there
is a need to remove also the ovs-port profile which implicitly exists.
This change removes the ovs-port profile toghether with the enslaved
interface.
This PR replaces #511 .
=> nm, ovs: Properly delete ovs-port profiles

.travis.yml
DockerHub currently breaks the RPM DB in our CentOS 8 container image
making the NM Copr CI jobs fail when updating NM from Copr (see #740).
Remove the jobs until a workaround is in place.
=> Travis: Remove NM Copr jobs

libnmstate/nm/connection.py
In cases where the commit operation has not included a NM device, and a
failure occurs in the callback function, the mainloop quit logging
causes a secondary error.
=> nm, connection: Fix commit callback error logging

libnmstate/nm/nmclient.py
The existing 2sec delay has a noticeable cost on tests time,
therefore reducing the delay to 0.5sec.
=> nm, nmclient: Reduce the mainloop teardown delay

tests/integration/sriov_test.py
SR-IOV tests xfail are consuming a lot of time in Travis CI.
=> tests, integ: skip SR-IOV tests in CI

libnmstate/nm/applier.py, libnmstate/nm/connection.py, tests/integration/ovs_test.py
nm, applier, ovs: Hash the OVS port device name
The OVS port device name is limited by NM to the kernel interface name
length (15 chars) even though there is no real underline interface. [1]
As a workaround, this change hashes the profile name into a max of 15 hex
characters and uses it as the profile interface/device name.
The interface name is creaded as part of the OVS port (proxy) interface
state and passed on through the setup flow by adding it as metadata to
the state.
[1] https://bugzilla.redhat.com/1788432
Depends on #717 
An alternative to #678
=> nm, applier, ovs: Hash the OVS port device name

.travis.yml, automation/run-tests.sh, packaging/Dockerfile.centos8-nmstate-dev
Change Travis to use CentOS 8 for unit test on python 3.6 instead of
Fedora.
Due to pip/setuptools bug: https://github.com/pypa/pip/issues/6264 ,
upgrade system installed python3-setuptools is required.
=> Travis: Run py36 unit test on CentOS 8 CI image

tests/integration/ovs_test.py, tests/integration/team_test.py
When using `dnf remove NetworkManager-team`, dnf may also remove all
dependent packages that have no other usages. Those packages are not
cached and may fail integration test that follow.
Using `rpm -e` will not remove dependency packages.
=> test team: Don't remove dependency rpm

tests/integration/team_test.py
In el8 we are having some issues with NM and Team interfaces.
Ref: https://bugzilla.redhat.com/1798947
=> tests, integ: add xfail to team test

libnmstate/schemas/operational-state.yaml, tests/lib/schema_validation_test.py
In some virtual interfaces like 'tun' or 'ip-tunnel' the MAC address
could be less than six octets. In order to fix that, we have modify the
minimum limitation to one octet.
If an user sets an invalid MAC address then NetworkManager is
reporting it clearly.
```
2020-02-06 14:50:20,585 root         ERROR    NM main-loop aborted:
Connection update failed: error=nm-connection-error-quark:
802-3-ethernet.cloned-mac-address: '12:BC:B9:2B' is not a valid MAC
address (7), dev=eth1/<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>
```
Ref: https://bugzilla.redhat.com/1796838
=> schema: modify MAC address minimum limitation

.travis.yml, automation/run-tests.sh, tox.ini
As run-tests.sh is now using Fedora 32, it requires to install python 3.7
to run python 3.7 unit tests.
```
GLOB sdist-make: /root/nmstate-workspace/setup.py
py37 create: /root/nmstate-workspace/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
```
=>  tox, tavis: remove python 3.7 unit tests

tests/integration/ovs_test.py
When running test_nm_ovs_plugin_missing test, the NM ovs plugin is
removed. Unfortunatly it fails to be re-installed when the test ends.
Until this issue is fixed, the test is marked not to run in the suite.
Ref: https://github.com/nmstate/nmstate/issues/759
=> tests, integ: Do not run test_nm_ovs_plugin_missing

tests/integration/nm/ovs_test.py
tests, integ, nm: Remove xfail from all ovs tests
The OVS tests have been marked with xfail because there were instability
issues when running them.
In order to proceed with the development of OVS and detect new issues,
the xfail marking is removed.
Depends on #760
=> Remove xfail from all nm ovs tests

automation/run-tests.sh, packaging/Dockerfile.centos8-nmstate-dev
The CentOS 8 tox is using latest virtualenv which is not compatible
with pip installed python3-six(when intalling pytest) due to
https://github.com/pypa/virtualenv/issues/1009 issue.
The `VIRTUALENV_NO_DOWNLOAD=1` environment variable will stop virtualenv
doing so.
Use dnf to install pytest from AppStream and pytest-cov from EPEL8 and
fixed the tox version to 3.5.3 using pip3.
Since we are using site packages in tox unit test, there is no need
for rpms from "Development Tools" group.
=> ci EL8: Fix unit test on CentOS 8

libnmstate/error.py, libnmstate/netapplier.py, libnmstate/nm/nmclient.py, tests/integration/nm/testlib.py
Instead of using return values, use exceptions to reflect the reason of
the mainloop error.
In addition, raise NmstateTimeoutError on mainloop timeout
From the existing errors reported by the mainloop it is hard to
distinguish between a timeout error and an action failure.
This change introduces a dedicated timeout exception that may be used to
identify it by callers.
The integration tests may now be more specific when xfail-ing a test.
=> nmclient: Use exceptions in mainloop.run and introduce NmstateTimeoutError

tests/integration/dynamic_ip_test.py
When running DHCP integration test repeatedly, the DHCPv4
pool will be exhausted. Do not update the lease file to fix this.
A simpler approach to address the issue from #724
=> DHCP tests: Do not use the lease database

libnmstate/nm/applier.py, libnmstate/nm/ovs.py, tests/integration/nm/ovs_test.py, tests/lib/nm/applier_test.py
The OVS {port, bridge} options translation step has no added value at the moment and
can be dropped.
Depends on #761, #760
=> nm, ovs: Remove translate {port, bridge} options step

libnmstate/netapplier.py, libnmstate/validator.py, tests/lib/validator_test.py
The current interface state is using the name property as an unique
key. Passing in duplicate interfaces names causes a failure only at the
verification step (if it is executed), making it hard to understand the
problem.
This change adds a validation for duplicate interface names, raising an
error early on.
=> validator: Validate duplicate interface names

.travis.yml, packaging/Dockerfile.centos8-nmstate-dev-nm-1.22-git
DockerHub currently breaks the RPM DB in our CentOS 8 container image
making the NM Copr CI jobs fail when updating NM from Copr (see #740).
In order to fix this, we have created a new image repository and have
built the image locally.
=> travis: run integration tests using NM-1.22-git Copr in el8

libnmstate/nm/ovs.py, libnmstate/schema.py, tests/integration/nm/ovs_test.py, tests/lib/nm/ovs_test.py
Link aggregation is implemented in the nm.ovs module, supporting both
setting and reporting the state.
The state (report) is interpreted from the NM configuration.
As part of the change, existing bond related properties (updelay and
downdelay) have been relocated to the link-aggregation subtree.
The lacp property has been integrated into the `mode` property.
Specifically, lacp is set to `active` when the lag mode is "lacp" or
"balance-tcp" and to "off" when the lag mode is "active-backup" or
"balance-slb".
The following OVS port state may be used to configure a bond:
```
name: ovs-bond1
link-aggregation:
mode: balance-slb
slaves:
- name: eth1
- name: eth2
```
Depends on #760, #761, #762
=> nm, ovs: Support link-aggregation port

libnmstate/nm/applier.py, tests/integration/ovs_test.py
When editing existing OVS interface, nmstate failed with
AttributeError: 'SimpleConnection' object has no attribute
'commit_changes_async'
The root cause is nm/applier failed to load existing profile using
the OVS port interface name when OVS port name changed to hash string.
The fix is correct the interface name before look up when facing OVS
port.
Resolves #777
=> nm ovs: Fix bug of editing existing OVS interface

libnmstate/state.py
There is not need to support Python 2 code anymore, therefore removing
leftovers like collections.Mapping/Sequence usage.
Python 3 uses collections.abc.Mapping/Sequence.
=> py3: Drop usage of collections.Mapping/Sequence

tests/integration/testlib/statelib.py
There is not need to support Python 2 code anymore, therefore removing
leftovers like collections.Mapping/Sequence usage.
Python3 uses collections.abc.Mapping/Sequence.
=> python3, statelib: drop usage of collections.Mapping/Sequence

libnmstate/netinfo.py, libnmstate/nm/connection.py, libnmstate/nm/ovs.py, libnmstate/nm/team.py, libnmstate/validator.py, tests/integration/ovs_test.py, tests/integration/team_test.py
Now it is possible to get the plugin capabilities from the NM client.
Nmstate is reporting the missing NetworkManager plugin during the
validation instead of during profile activation.
Ref: https://bugzilla.redhat.com/1785160
=> validator: report missing NM plugin during validation

libnmstate/nm/team.py
If a team interface with options is set using nmcli then "device" is not
found in the team JSON configuration because is optional.
=> nm.team: Check if "device" exists before delete it

libnmstate/appliers/team.py, libnmstate/metadata.py, libnmstate/nm/team.py, tests/integration/team_test.py
Got failure when creating team interface with slaves caused by:
* When create setting, the `create_setting()` of `nm/team.py` altered the data layout which trigger failure in `merge_interfaces` at the verification stage.
* The slave interface does not set `connection.master` and `connection.slave-type`.
Fixed and also added integration test to assert on the run time status
of team interface.
=> team: Fix failure of creating team interface with slaves

libnmstate/nm/team.py
The connection profile only contains static information. If an user
modifies the team interface using nmcli or teamd we need to reflect the
changes in nmstate.
=> nm.team: get the configuration from the device

.travis.yml, automation/README.md, automation/run-tests.sh, libnmstate/nm/checkpoint.py, libnmstate/nm/nmclient.py, tests/integration/conftest.py, tests/integration/timeout_test.py
When doing a lot of operations in a single transaction the timeout
expires and the transaction fails. Adding a timeout per action instead
of per transaction solves this issue.
=> nm.nmclient: add timeout per action

libnmstate/appliers/ovs_bridge.py, libnmstate/netapplier.py, libnmstate/state.py, tests/integration/bond_test.py, tests/integration/linux_bridge_test.py, tests/integration/ovs_test.py, tests/lib/state_test.py
When a master interface is removed, nmstate should not implicitly remove
its slaves. If such an action is desired, the user needs to explicitly
specify it.
This change scope includes the following interface types:
- Bond
- Linux Bridge
- OVS Bridge
- Team
Note: OVS internal interfaces (ovs-interface type) are an exception
here, as such interfaces may not exist without an OVS bridge. Therefore,
these are expected to get removed together with their bridge.
This is also fixing the issue reported in https://nmstate.atlassian.net/browse/NMSTATE-272.
=> libnmstate: Do not remove slaves implicitly with master

libnmstate/nm/team.py, tests/integration/team_test.py
When configuring team ports, the team may return a state like this:
`{'device': 'team0', 'ports': {}, 'runner': {'name': 'roundrobin'}}`
such a state includes the `ports` key with an empty dictionary.
The team ports reporting is adjusted to support such a report.
=> nm, team: Fix reporting of team slaves

libnmstate/nm/team.py, tests/integration/team_test.py
nm.team: fetch the slaves using NM.DeviceTeam.get_slaves()
NM.DeviceTeam configuration might contains outdated information. This
causing a verification error when setting ports in a team interface.
Using the function get_slaves() to fetch the updated information.
=> nm.team: fetch the slaves using NM.DeviceTeam.get_slaves()

.travis.yml
=> travis: do not mark integ_slow tests as allowed to fail

libnmstate/deprecation.py, libnmstate/netapplier.py, libnmstate/netinfo.py, tests/lib/netapplier_test.py, tests/lib/netinfo_test.py
Warn when keyword arguments in `libnmstate.apply()`,
`libnmstate.commit()`, `libnmstate.rollback()` and `libnmstate.show()`
are specified as positional arguments. They will become keyword-only
arguments in nmstate-0.3.
=> libnmstate: Deprecate positional arguments to be used for keyword arguments

examples/ovsbridge_bond_create.yml, libnmstate/appliers/ovs_bridge.py, libnmstate/nm/applier.py, libnmstate/nm/ovs.py, libnmstate/state.py, libnmstate/validator.py, tests/integration/examples_test.py, tests/integration/ovs_test.py, tests/integration/testlib/ovslib.py, tests/lib/metadata_ovs_test.py, tests/lib/state_test.py, tests/lib/validator_test.py
Enable support for OVS port Link Aggregation (LAG).
A user can use the following desired state to define an OVS LAG:
```
interfaces:
- name: ovs-br0
type: ovs-bridge
state: up
bridge:
options:
stp: false
port:
- name: ovs-bond1
link-aggregation:
mode: balance-slb
slaves:
- name: eth1
- name: eth2
```
=> OVS Link Aggregation

packaging/Dockerfile.centos8-nmstate-dev
By putting all dnf command inside of single `RUN`, the rpmdb corruption
gone. No idea why, but it works.
Resolves: #740
=> CI container: Fix rpmdb corruption

MANIFEST.in
In RHEL/CentOS 8.1, the 'packaging/make_srpm.sh' will fail
with error `error: Found more than one spec file`.
The fix is exclude packaging/nmstate.spec when creating tarbal using
`python setup.py sdist --format tar`.
=> automation: Fix failure of building srpm

libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, packaging/nmstate.spec, tests/integration/dynamic_ip_test.py
For virtual interface(like bond, dummy, etc), once the DHCP or IPv6-RA
timeout, the virtual interface will be removed.
To prevent that, set the DHCP and Autoconf timeout to infinity(INT32_MAX).
Two test cases added:
* Dummy interface with DHCPv4 and/or DHCPv6 enabled. Check whether
after default DHCP timeout(45 seconds) cause interface been deleted.
* Dummy interface with IPv6 autoconf and DHCPv6 enabled. Check
whether after default IPv6 RA timeout(30 seconds) cause interface
been deleted.
=> nm ip: Extend the DHCP/Autoconf timeout to infinity

tests/integration/nm/bond_test.py
Expected values belong to the right-hand side for comparisons in
assertions.
=> Integration tests/nm/bond: Fix assertion order

libnmstate/nm/bond.py, tests/integration/bond_test.py, tests/integration/nm/bond_test.py, tests/lib/nm/bond_test.py
NetworkManager has a list of supported bond options in their source
code, use that list and check `/sys/class/net/<bond_name>/bonding` folder
for in-kernel runtime bond options.
When applying bond options, ignore empty string option.
New integration test case added to set all the supported non-default
bond options. Currently with NM 1.22 and 1.20, it might fail due to
https://bugzilla.redhat.com/show_bug.cgi?id=1789437 .
=> nm/bond: Get in-kernel runtime bond options

examples/ovsbridge_vlan_port.yml, libnmstate/nm/ovs.py, libnmstate/schema.py, tests/integration/examples_test.py, tests/integration/nm/ovs_test.py, tests/integration/ovs_test.py, tests/integration/testlib/ovslib.py, tests/lib/nm/ovs_test.py
The OVS port vlan schema is:
```yml
- name: ovs-br0
type: ovs-bridge
state: up
bridge:
port:
- name: ovs0
vlan:
mode: access
tag: 2
```
Add two test cases:
* Example test against `examples/ovsbridge_vlan_port.yml`.
* Integration test: `test_ovs_vlan_access_tag`
=> nm ovs: Enforce compliance of OVS port VLAN schema

libnmstate/appliers/bond.py, libnmstate/netapplier.py, libnmstate/nm/applier.py, libnmstate/nm/bond.py, libnmstate/validator.py, tests/integration/bond_test.py, tests/integration/nm/bond_test.py, tests/lib/nm/bond_test.py, tests/lib/validator_test.py
When bond in active backup mode with fail_over_mac set to active,
the MAC address of bond interface cannot be set.
To support it:
* When MAC address defined in desired state along with active
backup mode and fail_over_mac=active, raise `NmstateValueError`.
* When MAC address defined in desired state while the current
state of bond is active backup mode with fail_over_mac=active,
raise NmstateValueError.
* When MAC address not defined in desired state while the current
state of bond is active backup mode with fail_over_mac=active.
Ignore the MAC address of current bond.
Test cases included.
=> bond: Add support of fail_over_mac=active with active backup mode

libnmstate/validator.py, tests/lib/validator_test.py
Now it is possible to apply the a DNS configuration without specifying
the interfaces or routes. e.g.
```
---
dns-resolver:
config:
search:
- example.com
- example.org
server:
- 2001:4860:4860::8888
- 8.8.8.8
```
=> validator: allow validation for states without interfaces

automation/run-tests.sh
In travis system, the dnf command failed with error:
[Errno 2] No such file or directory: '/var/cache/dnf/metadata_lock.pid'
The bug is https://bugzilla.redhat.com/show_bug.cgi?id=1581824
To work around it, remove the lock file before dnf command.
=> travis: Fix run test with copr repo

libnmstate/nm/bond.py
Except the `mode` bond option, report only the non-default option
values.
This change is avoiding an undesired merge of default values to the
desired state, which in turn causes defaults to be explicitly set on the
NM profile. Setting some defaults explicitly may cause validation errors
that are introduced by NM.
=> nm, bond: Report only non-default settings

libnmstate/appliers/bond.py, libnmstate/state.py, tests/integration/bond_test.py, tests/integration/testlib/statelib.py, tests/lib/appliers/__init__.py, tests/lib/appliers/bond_test.py
Support bond numeric options by normalizing bond options values in the verification step:
- Numeric only values are converted to integers.
- Dual named and numeric values are converted to named values.
This PR fixes:
https://bugzilla.redhat.com/1805223
=> bond: Support bond options with numeric values as input

libnmstate/nm/bond.py, tests/integration/bond_test.py
The "arp_ip_target" option format for NM is "10.1.1.2,10.1.1.3" but we
are reading the options from sysfs and the format is
"10.1.1.2 10.1.1.3".
=> verification, bond: prepare "arp_ip_target" option for verification

automation/run-tests.sh, automation/upload_test_artifacts.sh
When segfault happens in container, only the host can save the coredump.
Enable the systemd coredump in Travis host and collect the coredump
files to exported-artifacts/ folder waiting for upload.
=> test: Collect coredump when exists

libnmstate/nm/bond.py, tests/integration/bond_test.py
When applying state with default bond options explicitly set,
nmstate will fail at verification stage as default bond options
have been purged when showing to user.
To fix this, include bond options when it is explicitly set in on disk
profile.
New integration test case included.
=> nm/bond: Include bond options defined in on-disk profile

README.md
Remove nmstate-0.1 Copr repos because they are going to be removed,
soon.
=> README: Remove nmstate-0.1 Copr repos

tests/integration/ethernet_mtu_test.py
The NetworkManager patch has been included in 1.22.0 release.
Removed the xfail and fix the test case.
=> test ethernet: Remove xfail on MTU changes of VLANs

libnmstate/nm/checkpoint.py
According to GLib documentation the interval specified when using
timeout_add() is on miliseconds.
=> nm.checkpoint: fix incorrect interval when adding a timer

libnmstate/netapplier.py, libnmstate/validator.py, tests/lib/validator_test.py
The function validate_interfaces_state does not use the parameter
desired_state, therefore this patch removes it.
Signed-off-by: Elvira García Ruiz <elviragr@riseup.net>
=> validator: Drop unnused parameter at validate_interfaces_state()

examples/eth1_with_sriov.yml, libnmstate/nm/sriov.py, tests/integration/examples_test.py
When interface does not exists, the `nm.sriov._has_sriov_capability()`
will raise:
```python
def _has_sriov_capability(ifname):
dev = device.get_device_by_name(ifname)
>       if nmclient.NM.DeviceCapabilities.SRIOV & dev.props.capabilities:
E       AttributeError: 'NoneType' object has no attribute 'props'
```
Fixed by add additional check on whether device is None.
Also fixed the integration test which incorrectly using eth0 which is
not test NIC, changed to eth1.
=> nm sriov: Properly return when device not exists

.packit.yml, packaging/make_srpm.sh, packaging/nmstate.spec
Add configuration for packit-as-a-service to enable automatic Copr builds for pull requests.
We can also use this in the future to simplify updating the Fedora Rawhide package.
=> Enable Packit for automatic Copr builds

tests/integration/conftest.py
Prefer rpm version, and fallback to `libnmstate.__version__`.
=> Test: Include nmstate version in log

libnmstate/nm/active_connection.py
Handle ActiveConnection._nmdev being None. This should fix a Traceback
when the openvswitch service is not running:
File "/usr/lib/python3.6/site-packages/libnmstate/nm/connection.py", line 226, in _active_connection_callback
ac.devname, ac.reason
File "/usr/lib/python3.6/site-packages/libnmstate/nm/active_connection.py", line 171, in devname
return self._nmdev.get_iface()
AttributeError: 'NoneType' object has no attribute 'get_iface'
This also makes everything use ActiveConnection.devname
=> ActiveConnection: Handle uninitialized device

.travis.yml, automation/README.md, automation/run-tests.sh, packaging/build-container.sh
Container registry is now specified at container images in order to
avoid name squatting attacks or any other related problems.
Ref: https://raesene.github.io/blog/2019/09/25/typosquatting-in-a-multi-registry-world/
This PR fixes #785.
Signed-off-by: Elvira García Ruiz <elviragr@riseup.net>
=> automation, travis: Specify registry for container images

libnmstate/nm/connection.py
ActiveConnection.devname might be None if the activation failed for
virtual interfaces. Therefore use the interface name from the
NM.RemoteConnection for logging.
=> ConnectionProfile: Use interface name from NM.RemoteConnection

libnmstate/netapplier.py, tests/integration/dynamic_ip_test.py
During the verification sometimes ethtool is reporting 'unknown' in
duplex state. This is due a lack of time for some NICs to update the
information. We have noticed it only with Broadcom BCM57840 NetXtreme II
NIC but it could affect to other NICs.
In order to fix this, we are retrying the operation up to 5 times
sleeping 2 seconds for each retry.
Ref: https://bugzilla.redhat.com/1807034
=> netapplier: retry verification after failing

tests/integration/bond_test.py, tests/integration/dns_test.py, tests/integration/dynamic_ip_test.py, tests/integration/ethernet_mtu_test.py, tests/integration/examples_test.py, tests/integration/linux_bridge_test.py, tests/integration/mem_leak_test.py, tests/integration/ovs_test.py, tests/integration/profile_test.py, tests/integration/route_test.py, tests/integration/static_ip_address_test.py, tests/integration/team_test.py, tests/integration/timeout_test.py, tests/integration/vlan_test.py, tests/integration/vxlan_test.py
Use `tier1` marker of pytest to group a list of important integration
test cases for QE or CI gating.
=> test: Grouping important test cases as tier1

automation/run-tests.sh, packaging/Dockerfile.centos8-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev
Travis might fail with
```
error: db5 error(2) from dbenv->open: No such file or directory
error: cannot open Packages index using db5 - No such file or directory (2)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
Error: non zero exit code: 1: OCI runtime error
```
According to https://github.com/dogtagpki/pki/blob/master/travis/pki-init.sh
also need to rebuild the dnf cache.
=> travis: fix rpmdb problem

automation/run-tests.sh
Travis is only taking the contributor branch, in order to do the diff
over the packaging folder we must compare againts the upstream repository.
=> automation: compare packaging againts upstream branch

tests/integration/bond_test.py, tests/integration/testlib/bondlib.py
Add xfail test case for know issue of NetworkManager when switching
2 slaves bond from mode 1 to 5.
Fixed the testlib `bond_interface()` function to include slaves
when both `extra_iface_state` and `slaves` is defined.
=> test: Add test case for switching bond mode

libnmstate/netapplier.py, libnmstate/nm/applier.py, tests/integration/bond_test.py, tests/integration/ethernet_mtu_test.py, tests/integration/linux_bridge_test.py, tests/integration/nm/ipv4_test.py, tests/lib/netapplier_test.py
Creating ethernet configuration when user not requested will
cause two major problems:
* Adding slave to newly create bridge will cause bridge link down.
* Cannot switch bond mode from 1(active-backup) to 5(balance-tlb).
To fix the problem, only create ethernet/wired setting when user
explicitly requested.
Remove the xfail of test case for changing bond mode from 1(active-backup)
to 5(balance-tlb).
Remove the workaround in test case for adding slave to newly created
bridge without link state down.
=> nm applier: only create ethernet when explicitly

tests/integration/mem_leak_test.py
Added integration test case for checking opened file descriptor after
10 times of interface up and down via `libnmstate.apply()`.
Disable the logging during test as pytest will hold the logger which
cause false alarm on leaking opened file descriptor.
=> test: Add file descriptor leak check on libnmstate.apply()

libnmstate/nm/bond.py, tests/integration/bond_test.py
The NM will ignore the `miimon=100`(the default option) when
wired/ethernet setting not included due to bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1806549
This cause verification error when user try to set `miimon=100` on
existing bond.
To workaround that, always include `miimon` option when querying bond
options.
=> nm bond: workaround on miimon=100 option

libnmstate/nm/bond.py, tests/integration/bond_test.py
The NM will ignore the `miimon=100`(the default option) when
wired/ethernet setting not included due to bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1806549
This cause verification error when user try to set `miimon=100` on
existing bond.
To workaround that, always include `miimon` option when querying bond
options.
=> [nmstate-0.2] nm bond: workaround on miimon=100 option

libnmstate/state.py, tests/integration/testlib/bridgelib.py, tests/integration/testlib/statelib.py, tests/lib/state_test.py, tests/lib/validator_test.py
The recursive dict update is used to merge two dicts that represent
states.
When the data to-be-merge includes an empty dict as the value, it will
overwrite any existing data.
This change allows a client to overwrite a whole subtree from the existing
state.
=> state: An empty dict value is treated as an overwrite

libnmstate/state.py, tests/integration/testlib/statelib.py, tests/lib/schema_validation_test.py, tests/lib/state_test.py, tests/lib/testlib/__init__.py, tests/lib/testlib/bridgelib.py
Enable / disable vlan filtering on linux bridge interfaces via interface state merging.
This allows for a user to partially update the port configuration.
Considering the current state:
```yaml
---
interfaces:
- name: eth1
type: ethernet
state: up
- name: linux-br0
type: linux-bridge
state: up
bridge:
port:
- name: eth1
stp-hairpin-mode: false
stp-path-cost: 100
stp-priority: 32
vlan:
mode: trunk
trunk-tags:
- id: 101
- id-range:
min: 500
max: 599
tag: 100
enable-native: true
```
If the user wants to remove the port vlan configuration on port
eth1 - and as a result disable port vlan filtering on the whose
bridge - the following yaml should be used:
```yaml
---
interfaces:
- name: linux-br0
type: linux-bridge
state: up
bridge:
port:
- name: eth1
vlan: {}
```
This is part of the split from …
=> Linux bridge vlans merge bridge state

tests/integration/mem_leak_test.py
After repeat call of `libnmstate.show()` or `libnmstate.apply()`,
the opened file descriptor could be less than before as pytest might
close some file descriptor used for logging of previous test case.
=> test: Fix the memory leak test

libnmstate/nm/applier.py, tests/integration/bond_test.py, tests/lib/nm/applier_test.py
The bond or bridge will take its first slave's MAC address, hence
NetworkManager by default will activate the slaves in the order of its
interface name.
When nmstate create or editing bond/bridge, the `autoconnect` feature
will cause NetworkManager activating the slaves in unexpected order
which then generate different MAC address of bond and bridge.
To fix this problem, sort the interface creation and modification order.
New integration test case has been included.
=> [nmstate-0.2] nm applier: Sort interface creation/modification order

libnmstate/nm/checkpoint.py
According to GLib documentation the interval specified when using
timeout_add() is on miliseconds.
=> Backport: nm.checkpoint: fix incorrect interval when adding a timer

.travis.yml
[The quay.io does not provides a way to disable the build cache][1],
switching back to docker.io which can.
[1]: https://issues.redhat.com/browse/PROJQUAY-474
This reverts commit 6f55152db0f54805f2b10362615ab4063561bac5.
=> Revert "travis: use quay.io repository in travis"

libnmstate/nm/wired.py
Changing MAC address retrieved from sysfs to upper case, in order to be
consistent(using upper case) on MAC address.
=> nm ethernet: Convert mac address from sysfs to upper case

libnmstate/nm/bridge_port_vlan.py, tests/lib/nm/bridge_port_vlan_test.py
This patch implements trunk ports and access ports as per the
port vlan schema, introduced in [0].
[0] - #440
This is part of the split from PR #576 .
=> nm, linux bridge, vlan filtering: implement port vlan for linux bridges

tests/integration/linux_bridge_test.py, tests/integration/testlib/bridgelib.py
Integration tests for the port vlan functionality.
This is part of the split from PR #576 .
=> linux bridge, vlan filtering: add integ tests

tests/integration/conftest.py
Some test case like DNS/DHCP/Route tests might got impacted by host's
original network state(for example, the initial removal of eth1/eth2
configure will fail when host is configured as static DNS with dynamic
IP as libnmstate.apply() will try to preserve the DNS information).
To fix that, create a empty network state before test starts using
session level autouse fixture `test_env_setup` to:
* Setup log level
* Remove all static route
* Remove all DNS configuration
* Remove all route rule configuration
* Restore host's network states after test ended.
* Show left over network interfaces created by test cases.
=> test: Create a empty network state before test starts

tests/integration/dns_test.py
Using netapplier.apply() and netinfo.show() is a leftover from old code.
Use libnmstate.apply() and libnmstate.show() instead.
=> integ, dns: use apply() and show() from libnmstate

.travis.yml, automation/README.md, automation/run-tests.sh, tests/integration/conftest.py
This patch is introducing integ_tier1 tests and using it in travis CI.
This will allow us to run integration test quickly as both jobs, integ
and integ_tier1  are going to run at the same time.
=> tests, integ: split tier1 integration tests

examples/eth1_with_sriov.yml, libnmstate/nm/sriov.py, tests/integration/examples_test.py
When interface does not exists, the `nm.sriov._has_sriov_capability()`
will raise:
```python
def _has_sriov_capability(ifname):
dev = device.get_device_by_name(ifname)
>       if nmclient.NM.DeviceCapabilities.SRIOV & dev.props.capabilities:
E       AttributeError: 'NoneType' object has no attribute 'props'
```
Fixed by add additional check on whether device is None.
Also fixed the integration test which incorrectly using eth0 which is
not test NIC, changed to eth1.
=> Backport: nm sriov: Properly return when device not exists

libnmstate/nm/dns.py, tests/lib/nm/dns_test.py
If two interfaces are connected to the same subnet, the nameservers
which are available via this subnet should be reported only once.
Ref: https://bugzilla.redhat.com/1806969
=> nm.dns: report nameservers only once

libnmstate/metadata.py, libnmstate/nm/dns.py, tests/integration/dynamic_ip_test.py, tests/lib/nm/dns_test.py
Added the support of static DNS configuration with dynamic IP interface as
long as specified interface has `InterfaceIP.AUTO_DNS` set to False.
When choosing interface to storing DNS configuration, the interface with
static address and gateway is preferred over dynamic interface with
`InterfaceIP.AUTO_DNS` set to False.
Added Unit test cases and integration test cases.
=> dns: support static DNS with dynamic IP

libnmstate/appliers/ovs_bridge.py, libnmstate/netinfo.py, libnmstate/validator.py, tests/integration/ovs_test.py, tests/integration/testlib/servicelib.py
OVS interfaces require openvswitch service started and running. If it is
not running and the desired state contains OVS interfaces then nmstate
is going to raise an error in the validation.
=> validator: raise if the necessary services are not running

libnmstate/metadata.py, libnmstate/nm/dns.py, tests/integration/conftest.py, tests/integration/dynamic_ip_test.py, tests/lib/nm/dns_test.py
Added the support of static DNS configuration with dynamic IP interface as
long as specified interface has `InterfaceIP.AUTO_DNS` set to False.
When choosing interface to storing DNS configuration, the interface with
static address and gateway is preferred over dynamic interface with
`InterfaceIP.AUTO_DNS` set to False.
Added Unit test cases and integration test cases.
Also included the patch `test: Create a empty network state before test starts`.
=> [nmstate-0.2] dns: support static DNS with dynamic IP

tests/integration/team_test.py
As the fix is in 1.22.8, the xfails are not needed anymore.
Ref: https://bugzilla.redhat.com/1798947
=> tests, integ: remove team tests xfails

libnmstate/validator.py, tests/integration/dns_test.py
Support 3 or more IPv4/IPv6 only DNS name servers.
Still not supported 3+ IPv4 and IPv6 mixed name servers.
A warning will be emitted when 4 or more DNS name severs defined.
Integration test cases added.
=> dns: Enable support of 3+ unmixed DNS name server

libnmstate/nm/team.py
Old code include everything get from teamd json config which
include unsupported options. The option `link_watch` might disappear
from time to time in teamd json config, this fails the verification
stage as the merge process will take this unsupported option to desired
state.
To properly solve that, only show supported properties:
* `Team.Runner.NAME`
* `Team.Port.NAME`
=> nm team: Only show supported properties

libnmstate/validator.py, tests/integration/dns_test.py
Support 3 or more IPv4/IPv6 only DNS name servers.
Still not supported 3+ IPv4 and IPv6 mixed name servers.
A warning will be emitted when 4 or more DNS name severs defined.
Integration test cases added.
=> [nmstate-0.2] dns: Enable support of 3+ unmixed DNS name server

libnmstate/nm/bridge.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py
Unmanaged ports were not being shown when showing or editting the
bridge. In order to fix that, nmstate is retrieving the bridge ports
from sysfs instead of NetworkManager on-disk configuration.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1806452
=> nm.bridge: get ports from sysfs

doc/nmstatectl.8.in
Added the --version argument and version command to "nmstatectl.8.in" so
the manpage shows it.
=> doc: Update manpage with version argument and command

libnmstate/nm/applier.py, packaging/nmstate.spec, tests/integration/nm/ovs_test.py, tests/integration/ovs_test.py
With NetworkManager 1.22.10, it has removed the restriction on interface
name length on OVS port name.
Remove the need of creating hash string for OVS port.
Also include new patch to remove the xfail in OVS test cases as OVS in NM 1.22.9 is stable now.
Resolves: #805
=> nm ovs: Remove the workaround of OVS port name and xfail of test caes

libnmstate/appliers/bond.py, libnmstate/state.py, tests/integration/bond_test.py, tests/integration/testlib/assertlib.py
Got verification failure when disabling `arp_interval` of existing bond
regarding `arp_ip_target: ''` not included in new state.
This is because NetworkManager does not store `arp_ip_target: ''` in
on-disk profile when `arp_interval` is zero/disabled.
The fix is allowing backend to skip `arp_ip_target` when ARP monitoring
is disabled(`arp_interval==0`) by fix the bond option before
verification.
Added function `libnmstate.applier.bond.iface_state_pre_verify_fix()`.
Introduced `self._pre_verification_fix()` to `State.verify_interfaces()`
allowing `state.py` to delegating state modification to interface
specific function without knowing the detail.
=> state: allow missing arp_ip_target when ARP monitoring disabled

libnmstate/appliers/bond.py, libnmstate/state.py, tests/integration/bond_test.py, tests/integration/mem_leak_test.py, tests/integration/testlib/assertlib.py
Got verification failure when disabling `arp_interval` of existing bond
regarding `arp_ip_target: ''` not included in new state.
This is because NetworkManager does not store `arp_ip_target: ''` in
on-disk profile when `arp_interval` is zero/disabled.
The fix is allowing backend to skip `arp_ip_target` when ARP monitoring
is disabled(`arp_interval==0`) by fix the bond option before
verification.
Added function `libnmstate.applier.bond.iface_state_pre_verify_fix()`.
Introduced `self._pre_verification_fix()` to `State.verify_interfaces()`
allowing `state.py` to delegating state modification to interface
specific function without knowing the detail.
=> [nmstate-0.2] state: allow missing arp_ip_target when ARP monitoring disabled

tests/integration/dns_test.py
On some platforms NMCI is getting the following error:
```
state = {'dns-resolver': {'config': {'search': [], 'server':
MarkDecorator(mark=Mark(name='xfail', args=(['2001:4860:4860::888...:
'eth1'}, {'destination': '::/0', 'metric': 201, 'next-hop-address':
'2001:db8:2::f', 'next-hop-interface': 'eth1'}]}}
def validate_dns(state):
"""
Only support at most 2 name servers now:
https://nmstate.atlassian.net/browse/NMSTATE-220
"""
dns_servers = (
state.get(DNS.KEY, {}).get(DNS.CONFIG, {}).get(DNS.SERVER, [])
)
>       if len(dns_servers) > 3:
E       TypeError: object of type 'MarkDecorator' has no len()
```
In order to fix this, this patch is splitting the supported and not
supported 3+ nameserver edit tests.
=> tests, integ: fix TypeError on dns tests

tests/integration/dns_test.py
On some platforms NMCI is getting the following error:
```
state = {'dns-resolver': {'config': {'search': [], 'server':
MarkDecorator(mark=Mark(name='xfail', args=(['2001:4860:4860::888...:
'eth1'}, {'destination': '::/0', 'metric': 201, 'next-hop-address':
'2001:db8:2::f', 'next-hop-interface': 'eth1'}]}}
def validate_dns(state):
"""
Only support at most 2 name servers now:
https://nmstate.atlassian.net/browse/NMSTATE-220
"""
dns_servers = (
state.get(DNS.KEY, {}).get(DNS.CONFIG, {}).get(DNS.SERVER, [])
)
>       if len(dns_servers) > 3:
E       TypeError: object of type 'MarkDecorator' has no len()
```
In order to fix this, this patch is splitting the supported and not
supported 3+ nameserver edit tests.
=> [nmstate-0.2] tests, integ: fix TypeError on dns tests

tests/integration/conftest.py
In order to run the tests out of the containers when cleaning the state
nmstate needs to make sure that all the interfaces are using static DNS
and routes.
=> [nmstate-0.2] test, integ: clean auto_dns and auto_routes before tests

libnmstate/nm/ovs.py
In openstack `test_ovs_remove_port` is failing with the following error:
```
_____________________________ test_ovs_remove_port _____________________________
bridge_with_ports = <integration.testlib.ovslib.Bridge object at 0x7f3598880080>
@pytest.mark.xfail(
raises=NmstateLibnmError, reason="https://bugzilla.redhat.com/1724901"
)
def test_ovs_remove_port(bridge_with_ports):
for port_name in bridge_with_ports.ports_names:
nm_port_profile_name = nmlib.get_ovs_port_by_slave(port_name)
assert nmlib.list_profiles_by_iface_name(nm_port_profile_name)
libnmstate.apply(
{
Interface.KEY: [
{
Interface.NAME: port_name,
>                           Interface.STATE: InterfaceState.ABSENT,
}
]
}
)
tests/integration/ovs_test.py:203:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> [nmstate-0.2] nm.ovs: check slave profile exists before adding it

tests/integration/conftest.py
If the tests are being run out of the container it is possible to
contain interfaces with dynamic DNS configured. When that happens, the
test fails because the current state contains the dns configuration from
that interface.
In order to fix this, the test is checking the current configuration
contains the desired DNS configuration.
=> test, integ: clean auto_dns and auto_routes before tests

libnmstate/nm/ovs.py
In openstack `test_ovs_remove_port` is failing with the following error:
```
_____________________________ test_ovs_remove_port _____________________________
bridge_with_ports = <integration.testlib.ovslib.Bridge object at 0x7f3598880080>
@pytest.mark.xfail(
raises=NmstateLibnmError, reason="https://bugzilla.redhat.com/1724901"
)
def test_ovs_remove_port(bridge_with_ports):
for port_name in bridge_with_ports.ports_names:
nm_port_profile_name = nmlib.get_ovs_port_by_slave(port_name)
assert nmlib.list_profiles_by_iface_name(nm_port_profile_name)
libnmstate.apply(
{
Interface.KEY: [
{
Interface.NAME: port_name,
>                           Interface.STATE: InterfaceState.ABSENT,
}
]
}
)
tests/integration/ovs_test.py:203:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> nm.ovs: check slave profile exists before adding it

libnmstate/appliers/bond.py, libnmstate/metadata.py, libnmstate/nm/applier.py, libnmstate/state.py, tests/integration/bond_test.py, tests/lib/appliers/bond_test.py
When changing bond mode, user is required to provide all bond options
and no bond options will be merged from current state.
When changing bond mode, full deactivation is required in NetworkManager
do to bug https://bugzilla.redhat.com/show_bug.cgi?id=1819137
Procedure to fix this issue:
* Generate a metadata if bond mode changed.
* After merge, use desire bond option only if bond mode changed.
* In NM profile modification, deactivate the interface before
modification if bond mode changed.
Added integration test case and unit test cases.
=> bond: Don't merge bond options when bond mode changed

automation/run-tests.sh
The OVS logs from /var/log/openvswitch/ovsdb-server.log could be useful
for debugging OVS issues.
=> automation: export /var/log/openvswitch/ovsdb-server.log

libnmstate/appliers/bond.py, libnmstate/metadata.py, libnmstate/nm/applier.py, libnmstate/state.py, tests/integration/bond_test.py, tests/lib/appliers/bond_test.py
When changing bond mode, user is required to provide all bond options
and no bond options will be merged from current state.
When changing bond mode, full deactivation is required in NetworkManager
do to bug https://bugzilla.redhat.com/show_bug.cgi?id=1819137
Procedure to fix this issue:
* Generate a metadata if bond mode changed.
* After merge, use desire bond option only if bond mode changed.
* In NM profile modification, deactivate the interface before
modification if bond mode changed.
Added integration test case and unit test cases.
=> [nmstate-0.2] bond: Don't merge bond options when bond mode changed

libnmstate/validator.py, tests/integration/bond_test.py, tests/integration/linux_bridge_test.py, tests/integration/ovs_test.py, tests/integration/team_test.py, tests/lib/validator_test.py
When a bond interface is created, the slaves cannot have their IP
configuration enabled. In order to fix this problem, this patch
introduces a validation check to see whether the slave interfaces had
their IP enabled and if so, it raises an NmstateValueError.
Ref: https://bugzilla.redhat.com/1782674
This fixes #774 
Signed-off-by: Elvira García Ruiz <elviragr@riseup.net>
=> validator: Check IP config in bond slaves.

.github/CODEOWNERS
Since I don't have time to review everything anymore, remove myself from the codeowners.
=> Codeowners: Remove tyll

CHANGELOG
- Support Linux bridge VLAN filtering
- bond: Don't merge bond options when bond mode changed
https://bugzilla.redhat.com/1812737
- Fix the race between OVS bridge config querying and OVS interface deletion
=> CHANGELOG: Release 0.2.10-rc1

.travis.yml
We are installing podman from the opensuse repository [1], 16th April
they have updated the podman package from podman 1.8.2 to podman 1.9.0
which is broken. As the repository does not contain podman
1.8.2 anymore, we are switching to docker again temporarily.
[1] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/
=> travis: switch to docker as podman 1.9.0 is broken in Ubuntu 

.travis.yml
We are installing podman from the opensuse repository [1], 16th April
they have updated the podman package from podman 1.8.2 to podman 1.9.0
which is broken. As the repository does not contain podman
1.8.2 anymore, we are switching to docker again temporarily.
[1] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/
=> [nmstate-0.2] travis: switch to docker as podman 1.9.0 is broken in Ubuntu

libnmstate/nm/active_connection.py, libnmstate/nm/ovs.py
If any interface is marked as absent, then nmstate should wait until the
NM.ActiveConnection is deleted. This allow nmstate to do not check if
the profile exists when getting the current state eliminating all the
race conditions at that point.
=> nm.active_connection: wait until NM.ActiveConnection is deleted

libnmstate/nm/active_connection.py, libnmstate/nm/ovs.py
If any interface is marked as absent, then nmstate should wait until the
NM.ActiveConnection is deleted. This allow nmstate to do not check if
the profile exists when getting the current state eliminating all the
race conditions at that point.
=> [nmstate-0.2] nm.active_connection: wait until NM.ActiveConnection is deleted

.packit.yml
Add configuration for packit-as-a-service to enable automatic Copr
builds for pull requests.
=> [nmstate-0.2] Packit: Add packit configuration

CHANGELOG
- Support Linux bridge VLAN filtering
- bond: Don't merge bond options when bond mode changed
https://bugzilla.redhat.com/1812737
- Fix the race between OVS bridge config querying and OVS interface deletion
=> CHANGELOG: New release 0.2.10

libnmstate/nm/bond.py, tests/integration/bond_test.py
The `test_bond_switch_mode_with_conflict_option` test case will
fail in NM 1.23.2 as `lacp_rate` is still showing in incompatible bond
mode as the `NM.SettingBond.get_option_default()` is return None.
Since NM 1.23.2, the `NM.SettingBond.get_option_default()` supports
provide bond mode specific default options.
When certain option is not valid in specific bond mode, the
`get_option_default()` will return None.
The fix is query out the bond mode first, then set the bond mode in
`NM.SettingBond` which could provide default bond options of this bond
mode.
=> nm bond: Fix the bond default option getter

libnmstate/nm/bond.py, tests/integration/bond_test.py
The `test_bond_switch_mode_with_conflict_option` test case will
fail in NM 1.23.2 as `lacp_rate` is still showing in incompatible bond
mode as the `NM.SettingBond.get_option_default()` is return None.
Since NM 1.23.2, the `NM.SettingBond.get_option_default()` supports
provide bond mode specific default options.
When certain option is not valid in specific bond mode, the
`get_option_default()` will return None.
The fix is query out the bond mode first, then set the bond mode in
`NM.SettingBond` which could provide default bond options of this bond
mode.
Also promoting `test_bond_switch_mode_with_conflict_option` as tier1
test case.
=> [nmstate-0.2] nm bond: Fix the bond default option getter

.travis.yml
As Travis CI is now using docker, we must specify the registry for the
container image in the vdsm CI tests. Docker is trying to get the
container image from a private registry in dockerhub first.
=> travis: specify registry for container images in vdsm tests

README.install.md, packaging/README.release.md
The GPG public keys of maintainers are stored at
https://www.nmstate.io/nmstate.gpg
Updated README files to use this new URL.
=> nmstate.gpg: Use new URL for GPG public key

.travis.yml
As Travis CI is now using docker, we must specify the registry for the
container image in the vdsm CI tests. Docker is trying to get the
container image from a private registry in dockerhub first.
=> [nmstate-0.2] travis: specify registry for container images in vdsm tests

libnmstate/state.py, tests/integration/route_test.py, tests/integration/testlib/iprule.py
Got verification failure when specified `RouteRule.IP_FROM` or
`RouteRule.IP_TO` using host without prefix length.
Appending `/32` or `/128` before verification would fix this.
Integration test added.
=> Route rule: support host without prefix length

libnmstate/nm/nmclient.py, libnmstate/nm/vxlan.py, tests/integration/nm/vxlan_test.py
As nmstate minimum supported NM version is 1.22.10, there is no need to
check for version 1.20.6 in `nm/vxlan.py`.
Unused code removed.
=> nm vxlan: Remove unused code nm_version()

libnmstate/nm/ovs.py, tests/integration/nm/ovs_test.py
The `get_bridge_info()` in `nm/ovs.py` is not used in production code,
but test only.
Removed.
=> nm ovs: Remove unused function get_bridge_info()

automation/run-tests.sh
Added pytest option to store the logfile, if the test fails it is also
saved in the directory that is uploaded to the log storage server.
=> automation: Export pytest log when CI fails

libnmstate/appliers/sriov.py, libnmstate/nm/sriov.py, libnmstate/state.py, tests/integration/sriov_test.py
The VF mac address is being read from the sysfs, it is always in
lowercase. In order to avoid verification failures, nmstate is setting
the VF mac to lowercase in the desired state before verifying.
Ref: https://bugzilla.redhat.com/1818750
=> sriov: normalize vf mac address before verification

libnmstate/schema.py
Introduced new class `Bridge` as parent of `LinuxBridge` and
`OVSBridge` holding the shared constants:
* `Bridge.CONFIG_SUBTREE`
* `Bridge.OPTIONS_SUBTREE`
* `Bridge.PORT_SUBTREE`
* `Bridge.Port.NAME`
* `Bridge.Port.VLAN_SUBTREE`
* `Bridge.Port.Vlan.ENABLE_NATIVE`
* `Bridge.Port.Vlan.TRUNK_TAGS`
* `Bridge.Port.Vlan.MODE`
* `Bridge.Port.Vlan.TAG`
* `Bridge.Port.Vlan.Mode.ACCESS`
* `Bridge.Port.Vlan.Mode.TRUNK`
* `Bridge.Port.Vlan.Mode.UNKNOWN`
* `Bridge.Port.Vlan.TrunkTags.ID`
* `Bridge.Port.Vlan.TrunkTags.ID_RANGE`
* `Bridge.Port.Vlan.TrunkTags.MIN_RANGE`
* `Bridge.Port.Vlan.TrunkTags.MAX_RANGE`
By doing this, we could eliminated the duplicate code on merging and
metadata generation between Linux Bridge and OVS Bridge.
=> schema: New class Bridge be parent of LinuxBridge and OVSBridge

libnmstate/nm/connection.py
Some SR-IOV parameters could be not supported by the device driver.
Nmstate must return a proper error message instead of a generic one.
```
2020-05-03 12:35:19,728 root         ERROR    NM main-loop aborted:
The device=eno1 does not support one or more of the SR-IOV parameters
set.
```
Ref: https://bugzilla.redhat.com/1819588
=> sriov: raise proper exception when SR-IOV parameter is not supported

.github/ISSUE_TEMPLATE/creating-a-new-release.md, packaging/README.release.md
* Create soft link from `.github/ISSUE_TEMPLATE/creating-a-new-release.md` to `packaging/README.release.md`.
* Fix the git command for showing changes since certain version.
* Add notes for creating release tarball.
=> README.release: trivial fixes.

packaging/Dockerfile.centos8-nmstate-dev
Use `python3-tox` from EPEL8 repo instead of pip.
=> CI container: Use tox from EPEL8 repo

tests/integration/testlib/iproutelib.py, tests/integration/testlib/nmplugin.py
The flake8 3.8.1+ will raise error when using variables named 'l', 'O',
or 'I'.
Fixed by changing variable name.
=> test: Fix flake8 error: ambiguous variable name 'l'

libnmstate/nm/connection.py
All the reasons must be a string not an object.
=> nm.connection: fix reason in error message

libnmstate/nm/context.py, tests/integration/nm/checkpoint.py
When exception happens in NmContext, with `self._error` been set and
`self._cancellable` cancelled, follow up async action will fail.
This is required because the rollback action should be run in the same 
NmContext after exception happens.
Fix it by re-initiate the queue, error and cancellable in NmContext.
=> nm/context: Allowing async action to run after failure happens

libnmstate/nm/checkpoint.py
Should only assign dbus path to CheckPoint object after checked the
newly created checkpoint is not-No
=> nm/checkpoint: Only assign dbus path after creation succeeded

libnmstate/nm/context.py
The datetime.timedelta() is taking first argument as days.
Hence old code set the idle timeout as 25 days.
And the interval of idle checking is incorrectly set to 0.5 seconds.
=> nm/context: Fix the idle timeout callback

libnmstate/nm/checkpoint.py
Contain two patches:
* Should not register async action when it might not started yet. And only start refreshing the checkpoint once creation succeeded.
* Fix the incorrect use of `GLib.Error`.
=> nm/checkpoint: trivial fixes.

libnmstate/nm/applier.py, libnmstate/nm/connection.py
We are renaming the profile names to our standard which is the interface
name. If an interface has an existing profile with a non-standard
profile name, when importing the profile we should not import the
profile name because it is causing the following error:
```
2020-05-25 06:55:34,581 root         DEBUG    Async action: Create checkpoint started
2020-05-25 06:55:34,587 root         DEBUG    Checkpoint None created for all devices
2020-05-25 06:55:34,587 root         DEBUG    Async action: Create checkpoint finished
2020-05-25 06:55:34,590 root         DEBUG    Async action: Update profile: testeth0 started
2020-05-25 06:55:34,604 root         DEBUG    Async action: Update profile: testeth0 finished
2020-05-25 06:55:34,604 root         DEBUG    Async action: Reapply device config: eth0 …
```
=> nm.applier: set the profile name as the interface name

libnmstate/nm/checkpoint.py, libnmstate/nm/connection.py
Before initiate the interface rollback wait action, nmstate is checking
if the connection is already activated.
=> nm.checkpoint: check if the connection is activated

libnmstate/nm/applier.py
The team interface is a master interface so it must be activated in the
proper order. If not, nmstate could raise the following error:
```
libnmstate.error.NmstateLibnmError: Activate profile: eth1 failed:
reason=<enum NM_ACTIVE_CONNECTION_STATE_REASON_DEVICE_DISCONNECTED of type NM.ActiveConnectionStateReason>
<enum NM_DEVICE_STATE_REASON_DEPENDENCY_FAILED of type NM.DeviceStateReason>
```
=> nm.applier: team interfaces must be considered as master

tests/integration/conftest.py, tests/integration/dynamic_ip_test.py
In some platforms it is not possible to lose the connectivity during a
long time. In order to fix this, we are only cleaning auto_dns and
auto_routes in the tests when necessary.
=> test, integ: clean auto_routes and auto_dns only in the needed tests

libnmstate/nm/active_connection.py, tests/lib/nm/active_connection_test.py
The exception raise by libnm on activation is GLib.Error and
its code is NM.ManagerError as its error domain `nm-manager-error`.
Use `GLib.Error.matches()` to check on error types.
=> nm.active_connection: fix incorrect use of GLib.Error

libnmstate/dns.py
When chose IPv4 or IPv6 interface is None, the generated metadata will
contains:
{None: {Interface.IPV4: {DNS.SERVER: [], DNS.SEARCH: []}}
which is incorrect.
Only initialized for valid interface.
=> dns: Fix DNS metadata generation

libnmstate/nm/active_connection.py
Current code will treat device been deactivated when reaching
DEACTIVATING at the initial check, should wait for device been fully
deactivated in that case.
=> nm/active_connection: Wait for device been fully deactivated

libnmstate/nm/route.py
When NM.ActiveConnection is deactivating, the ActiveConnection will
not hold NM.Device hence return None on ActiveConnection.devname.
In stead of raise exception on this case, just skip querying routes from
ActiveConnection with empty interface name.
=> nm/route: Skip query on ActiveConnection without interface name

libnmstate/nm/connection.py, tests/integration/nm/vlan_test.py
The `nm.device.delete()` will delete all profiles found for certain
NM.Device. The async action ID is using device name for all of them.
When multiple profiles found, the async action ID will conflict with
existing one, then raise exception:
raise NmstateInternalError(
f"BUG: An existing actions {action} is already registered"
)
Changed to use both interface name and UUID of profile will fix this issue.
=> nm/connection: Use uuid of profile as action ID for profile deletion

libnmstate/ifaces/ifaces.py, libnmstate/nm/applier.py, tests/integration/dynamic_ip_test.py, tests/integration/profile_test.py, tests/integration/testlib/ifacelib.py
The InterfaceState.DOWN will only deactivate the profile.
The InterfaceState.ABSENT will deactivate the profile and delete the
on-disk profile.
When desire state only contains: `Interface.NAME, Interface.TYPE,
Interface.STATE:UP` or less, nmstate will activate the existing profile
without modification.
=> state: Differentiate DOWN and ABSENT state

libnmstate/netapplier.py, libnmstate/nm/checkpoint.py, libnmstate/nm/plugin.py, libnmstate/nmstate.py, tests/integration/nm/checkpoint.py, tests/integration/nm/conftest.py, tests/lib/netapplier_test.py
Moved checkpoint related functions to plugin level:
* `create_checkpoint()`
* `destroy_checkpoint()`
* `rollback_checkpoint()`
Removed these NM specific exception as plugin should raise NmstateError
only:
* `NMCheckPointError`
* `NMCheckPointCreationError`
* `NMCheckPointPermissionError`
To properly rollback when failures, context code moved to
`nmstate.py`.
=> [Plugin design] checkpoint: Move checkpoint functions to plugin level

libnmstate/nm/applier.py, libnmstate/nm/ovs.py, libnmstate/nm/plugin.py, libnmstate/nm/team.py, libnmstate/plugin.py, libnmstate/validator.py, tests/integration/nm/ovs_test.py
The nmstate top level codes should only use NetworkManagerPlugin.
This patch remove the use of `nm` internal variables in `validator.py`:
* Replace `nm.ovs.BRIDGE_TYPE` with `InterfaceType.OVS_BRIDGE`
* Replace `nm.ovs.PORT_TYPE` with `InterfaceType.OVS_PORT`
* Replace `nm.ovs.INTERNAL_INTERFACE_TYPE` with
`InterfaceType.OVS_INTERFACE`
* Replace `nm.ovs.CAPABILITY` with `NmstatePlugin.OVS_CAPABILITY`
* Replace `nm.team.CAPABILITY` with `NmstatePlugin.TEAM_CAPABILITY`
The newly added file `libnmstate/plugin.py` will hold the data only
used by nmstate plugin.
=> [Plugin design] validator: Remove the use of nm module

libnmstate/nm/checkpoint.py
The covscan report an error:
nmstate-0.3.1/libnmstate/nm/checkpoint.py:216: property_access:
Accessing a property of null-like value "nm_dev".
Fixed by checking whether NM.Device is valid.
=> nm/checkpoint: Handle NULL NM.Device when rollback

libnmstate/ifaces/ovs.py, libnmstate/plugins/nmstate_plugin_ovsdb.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, packaging/Dockerfile.centos8-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, packaging/nmstate.spec, tests/integration/ovs_test.py, tests/integration/testlib/assertlib.py, tests/integration/testlib/ovslib.py
Example:
```
interfaces:
- name: ovs0
type: ovs-interface
state: up
ovs-db:
external_ids:
NM.connection.uuid: e5b7900f-0c03-48ba-b0fe-20b93f9a395d
gris_test: foo
```
The external_ids is full editing, user have to provide full information.
If not mentioned, ovs DB will use old state without changing coming from this
plugin. If defined a `external_ids: {}`, will remove existing external
IDS except the NetworkManager internal one.
There is not checkpoint support for ovs plugin yet.
For schema, add class `OvsDB` to hold the common `OvsDB.OVS_DB_SUBTREE`
which is shared by `OVSBridge` and `OVSInterface`.
TODO:
* Test cases
* RPM SPEC
* Dockerfile
* Don't raise exception unless user ask for 'external_ids' explicitly,
allowing `python-ovs` been optional requirements.
=> ovs db plugin: add support of external_ids

libnmstate/ifaces/bridge.py, libnmstate/nm/applier.py, libnmstate/nm/bridge.py, libnmstate/nm/common.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/testlib/env.py
Adding linux bridge options required by oVirt:
https://www.ovirt.org/documentation/admin-guide/appe-Custom_Network_Properties.html
New read only bridge options:
* `LinuxBridge.Options.HELLO_TIMER`
* `LinuxBridge.Options.GC_TIMER`
New read-writable bridge options:
* `LinuxBridge.Options.GROUP_ADDR`
* `LinuxBridge.Options.HASH_MAX`
* `LinuxBridge.Options.MULTICAST_LAST_MEMBER_COUNT`
* `LinuxBridge.Options.MULTICAST_LAST_MEMBER_INTERVAL`
* `LinuxBridge.Options.MULTICAST_MEMBERSHIP_INTERVAL`
* `LinuxBridge.Options.MULTICAST_QUERIER`
* `LinuxBridge.Options.MULTICAST_QUERIER_INTERVAL`
* `LinuxBridge.Options.MULTICAST_QUERY_USE_IFADDR`
* `LinuxBridge.Options.MULTICAST_QUERY_INTERVAL`
* `LinuxBridge.Options.MULTICAST_QUERY_RESPONSE_INTERVAL`
* `LinuxBridge.Options.MULTICAST_STARTUP_QUERY_COUNT`
* …
=> linux bridge: Add linux bridge options required by oVirt

doc/nmstatectl.8.in, libnmstate/ifaces/base_iface.py, libnmstate/ifaces/bond.py, libnmstate/ifaces/ifaces.py, libnmstate/ifaces/ovs.py, libnmstate/net_state.py, libnmstate/netapplier.py, libnmstate/nm/applier.py, libnmstate/nm/connection.py, libnmstate/nm/plugin.py, libnmstate/plugin.py, libnmstate/plugins/nmstate_plugin_ovsdb.py, nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py, tests/integration/profile_test.py, tests/integration/vlan_test.py, tests/lib/netapplier_test.py
This patch is introducing non persisntent state support by the keyword argument
save_to_disk when using libnmstate API apply() and edit() operations. By
the default save_to_disk is True.
All the changes done to the interfaces when using non persistent state
will be wiped out after rebooting the system.
In addition, this patch is introducing nmstatectl --memory-only support.
By the default, it is disabled so the argument is needed in order to use
non persistent states.
=> libnmstate: Implement non persistent state support

tests/integration/lldp_test.py
Got failure when running pytest in 'tests/integration' folder stating
`tests/integration/test_captures/lldp.pcap` not found.
Use absolute path for the LLDP capture file will fix this problem.
=> test lldp: Allowing running test from any folder

tests/integration/dynamic_ip_test.py, tests/integration/iface_admin_state_test.py, tests/integration/route_test.py, tests/integration/vxlan_test.py, tests/lib/nm/route_test.py
This patch is updating xfails, adding `strict=True` and fixing wrong reasons.
=> tests: update outdated xfails

tests/integration/ovs_test.py, tests/integration/testlib/ovslib.py
Add two tier1 test case:
* `test_create_internal_port_with_explict_mtu`
* `test_change_mtu_of_existing_internal_port`
=> test: Add OVS internal interface MTU modification test

tests/integration/conftest.py
The pytest-4.6.9 will complain unregister markers:
```
/usr/lib/python3.7/site-packages/_pytest/mark/structures.py:335:
PytestUnknownMarkWarning: Unknown pytest.mark.tier1 - is this a typo?
You can register custom marks to avoid this warning - for details, see
https://docs.pytest.org/en/latest/mark.html
```
To suppress that warning message, use `pytest_configure()` to register
the markers.
=> test: Register pytest marker

libnmstate/ifaces/base_iface.py, libnmstate/iplib.py, libnmstate/route.py, libnmstate/route_rule.py, tests/lib/route_rule_test.py
Canonicalize these IP addresses:
* `InterfaceIP.ADDRESS_IP`
* `Route.DESTINATION`
* `Route.NEXT_HOP_ADDRESS`
* `RouteRule.IP_FROM`
* `RouteRule.IP_TO`
Introduced two functions to `libnmstate/iplib.py`:
* `canonicalize_ip_network()` returns address with prefix
* `canonicalize_ip_address()` returns address without prefix
Unit test cases added.
=> ip: canonicalize IP address

tests/integration/ovs_test.py, tests/integration/testlib/ovslib.py
Add two tier1 test case:
* `test_create_internal_port_with_explict_mtu`
* `test_change_mtu_of_existing_internal_port`
=> [nmstate-0.3] test: Add OVS internal interface MTU modification test

libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/dynamic_ip_test.py, tests/integration/nm/ipv4_test.py
This patch is adding support for `table_id` on IPv4 and IPv6. `table_id`
is setting `NM.SettingIPConfig.route-table` which decides in which table
the route will be configured.
=> nm.ipv4, nm.ipv6: add auto-route-table-id support for IPv4 and IPv6

libnmstate/ifaces/base_iface.py, libnmstate/iplib.py, libnmstate/route.py, libnmstate/route_rule.py, tests/lib/route_rule_test.py
Canonicalize these IP addresses:
* `InterfaceIP.ADDRESS_IP`
* `Route.DESTINATION`
* `Route.NEXT_HOP_ADDRESS`
* `RouteRule.IP_FROM`
* `RouteRule.IP_TO`
Introduced two functions to `libnmstate/iplib.py`:
* `canonicalize_ip_network()` returns address with prefix
* `canonicalize_ip_address()` returns address without prefix
Unit test cases added.
=> [nmstate-0.3] ip: canonicalize IP address

libnmstate/ifaces/base_iface.py, libnmstate/ifaces/ifaces.py, libnmstate/ifaces/ovs.py, libnmstate/plugins/nmstate_plugin_ovsdb.py, tests/lib/ifaces/ovs_iface_test.py
In order to follow the property naming, it makes sense to rename
"iface_type" property to "type".
=> base_iface: rename iface_type property to type

tests/integration/dynamic_ip_test.py, tests/integration/iface_admin_state_test.py, tests/integration/route_test.py, tests/integration/vxlan_test.py, tests/lib/nm/route_test.py
This patch is updating xfails, adding `strict=True` and wrong reasons.
=> [nmstate-0.3] tests: update outdated xfails

libnmstate/nm/plugin.py, libnmstate/validator.py
The `validate_interface_capabilities()` is invoking `is_ovs_running()`
on every interface. Fixed by using `set()` for interface types for
duplicate types and also caching ovs daemon status.
The `NetworkManagerPlugin.get_interfaces()` is invoking
`is_ovs_running()` on every interface. Fixed by caching ovs daemon
status.
=> ovs: Eliminate the repeat call of is_ovs_running()

libnmstate/ifaces/base_iface.py, libnmstate/ifaces/ifaces.py, tests/lib/ifaces/vlan_iface_test.py, tests/lib/ifaces/vxlan_iface_test.py
fixes #1047 
A new validator is added that verifies that the
MTU of VLAN is less than or equal to MTU of base iface
Signed-off-by: Adwait Thattey <coderdude1999@gmail.com>
=> Validate vlan mtu not greater than base iface

libnmstate/ifaces/ifaces.py, tests/lib/ifaces_test.py
If the desired state contains an interface with unknown type Nmstate
will raise a `NmstateValueError` exception because it is invalid. In
addition, after merging the desired and current state Nmstate will
ignore unknown type interfaces from merged state.
This issue was generating the following error:
```
File "/usr/local/bin/nmstatectl", line 11, in <module>
load_entry_point('nmstate==0.4.0', 'console_scripts', 'nmstatectl')()
File "/usr/local/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 67, in main
return args.func(args)
File "/usr/local/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 225, in edit
new_state, verify_change=args.verify, save_to_disk=args.save_to_disk
File …
```
=> ifaces: validate unknown type ifaces in desired and current state

libnmstate/nm/plugin.py, libnmstate/validator.py
The `validate_interface_capabilities()` is invoking `is_ovs_running()`
on every interface. Fixed by using `set()` for interface types for
duplicate types and also caching ovs daemon status.
The `NetworkManagerPlugin.get_interfaces()` is invoking
`is_ovs_running()` on every interface. Fixed by caching ovs daemon
status.
=> [nmstate-0.3] ovs: Eliminate the repeat call of is_ovs_running()

libnmstate/ifaces/base_iface.py, libnmstate/ifaces/ifaces.py, libnmstate/ifaces/ovs.py, libnmstate/plugins/nmstate_plugin_ovsdb.py, tests/lib/ifaces/ovs_iface_test.py, tests/lib/ifaces/vlan_iface_test.py, tests/lib/ifaces/vxlan_iface_test.py
A new validator is added that verifies that the
MTU of VLAN/VXLAN is not more than MTU of base iface
If base iface MTU doesn't exist, set as vlan MTU
Multiple tests are added to check if appropriate errors are thrown
=> [nmstate-0.3] vlan: validate mtu not greater than base iface

libnmstate/ifaces/ifaces.py, tests/lib/ifaces_test.py
After merging the desired and current state Nmstate will
ignore unknown type interfaces that are up.
This issue was generating the following error:
```
File "/usr/local/bin/nmstatectl", line 11, in <module>
load_entry_point('nmstate==0.4.0', 'console_scripts', 'nmstatectl')()
File "/usr/local/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 67, in main
return args.func(args)
File "/usr/local/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 225, in edit
new_state, verify_change=args.verify, save_to_disk=args.save_to_disk
File "/usr/local/lib/python3.6/site-packages/libnmstate/netapplier.py", line 71, in apply
_apply_ifaces_state(plugins, net_state, verify_change, save_to_disk)
File …
```
=> [nmstate-0.3] ifaces: ignore unknown type ifaces from current and desired state

nmstatectl/nmstatectl.py, tests/integration/nmstatectl_test.py
Old code return on first state file, but the test case
`test_set_command_with_two_states` indicate it should support multiple
state files.
Fixed by only return when failure when iterating state files.
Test case updated to reveal this problem.
=> nmstatectl: Fix the support of multiple state files

libnmstate/nm/device.py
Only invoke `NM.Device.reapply_async()` on activated device.
=> nm/device: Only invoke reapply on activated device

libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/nm/plugin.py, libnmstate/nm/profile.py, tests/integration/nm/ipv4_test.py, tests/lib/nm/ipv4_test.py, tests/lib/nm/ipv6_test.py
Previously we are using start up config(config saved to disk) for DHCP
status, this patch we changed to use running/effective config.
The applied profile are retrieved from
`NM.Device.get_applied_connection_async()` asynchronously.
The new file `libnmstate/nm/profile.py` will provides
`get_all_applied_configs()` in the sync/blocked way.
The running config are refreshed on every `get_interfaces()` call.
=> nm ip: Use running config for DHCP status

nmstatectl/nmstatectl.py, tests/integration/nmstatectl_test.py
Old code return on first state file, but the test case
`test_set_command_with_two_states` indicate it should support multiple
state files.
Fixed by only return when failure when iterating state files.
Test case updated to reveal this problem.
=> [nmstate-0.3] nmstatectl: Fix the support of multiple state files

libnmstate/nm/device.py
Only invoke `NM.Device.reapply_async()` on activated device.
=> [nmstate-0.3] nm/device: Only invoke reapply on activated device

libnmstate/dns.py, tests/integration/dns_test.py, tests/lib/dns_test.py
Current code raise NmstateVerificationError when user not providing
the full state:
`{DNS.SERVER: [], DNS.SEARCH: []}`
Now supporting remove static DNS config via:
* `{}`
* `{DNS.SERVER: []}`
* `{DNS.SEARCH: []}`
* `{DNS.SERVER: [], DNS.SEARCH: []}`
Test case updated for this.
=> dns: Fix remove dns config

libnmstate/dns.py, tests/integration/dns_test.py, tests/lib/dns_test.py
Current code raise NmstateVerificationError when user not providing
the full state:
`DNS.CONFIG: {DNS.SERVER: [], DNS.SEARCH: []}`
Now supporting remove static DNS config via:
* `DNS.CONFIG: {}`
* `DNS.CONFIG: {DNS.SERVER: []}`
* `DNS.CONFIG: {DNS.SEARCH: []}`
* `DNS.CONFIG: {DNS.SERVER: [], DNS.SEARCH: []}`
Test case updated for this.
=> [nmstate-0.3] dns: Fix remove dns config

libnmstate/prettystate.py, tests/integration/linux_bridge_test.py, tests/integration/nmstatectl_test.py, tests/integration/ovs_test.py, tests/lib/pretty_state.py
For OVS bond port, we would like the `name` been shown before other
properties.
To achieve that, we sort the dict keys and honoring the priority list which
means keys in `PRIORITY_LIST` will be shown before others.
Currently the `PRIORITY_LIST` is `("name", "type", "state", "enabled", "dns", "routes", "route-rules", "interfaces")`
Test cases added.
=> pretty state: Dumping state in the sorted order with priority

libnmstate/prettystate.py, tests/integration/linux_bridge_test.py, tests/integration/nmstatectl_test.py, tests/integration/ovs_test.py, tests/lib/pretty_state.py
For OVS bond port, we would like the `name` been shown before other
properties.
To achieve that, we sort the dict keys and honoring the priority list which
means keys in `PRIORITY_LIST` will be shown before others.
Currently the `PRIORITY_LIST` is:
`("name", "type", "state", "enabled", "dns", "route-rules", "routes",
"interfaces")`
Test cases added.
=> [nmstate-0.3] pretty state: Dumping state in the sorted order with priority

tests/integration/lldp_test.py
Delete `_get_lldp_test` function, instead use an assertion that checks the number of neighbors.
=> tests: add assertion that only one neighbor is reported

libnmstate/nm/applier.py, tests/integration/bond_test.py
The `iface.original_dict` is not original desire state when
`iface.is_desired == False` but the unmerged state when `BaseIface` is
created.
The case nm applier create the wire setting(especially MAC address) when
bond worker interface not included in desire state which then blocking
those worker interface been used in new mac restriced bond mode.
Integration test case created:
* Create bond in mode 4(802.3ad/LACP), there both slave will hold the
same MAC address.
* Remove bond.
* Create bond in mode 5(balance-tlb) where bond worker interface
should not different.
=> [Regression] nm: Only create ethernet section when desired

libnmstate/nm/applier.py, tests/integration/bond_test.py
The `iface.original_dict` is not original desire state when
`iface.is_desired == False` but the unmerged state when `BaseIface` is
created.
The case nm applier create the wire setting(especially MAC address) when
bond worker interface not included in desire state which then blocking
those worker interface been used in new mac restriced bond mode.
Integration test case created:
* Create bond in mode 4(802.3ad/LACP), there both slave will hold the
same MAC address.
* Remove bond.
* Create bond in mode 5(balance-tlb) where bond worker interface
should not different.
=> [nmstate-0.3] nm: Only create ethernet section when desired

automation/run-tests.sh, automation/tests-container-utils.sh
Some CI gating platforms need to install dependencies using pip3.
=> automation: extend --customize argument for no container support

libnmstate/nm/checkpoint.py
The log always says:
Checkpoint None created for all devices
We are using `self._dbus_path` before assigned.
=> nm/checkpoint: Fix the logging of checkpoint creation

tests/integration/ovs_test.py
Due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1857123 ,
nmcli might(1% chance) still show the deleted ovs port profile.
=> test: Mark test_ovs_remove_port as xfail

automation/run-tests.sh, automation/tests-container-utils.sh, automation/tests-machine-utils.sh, tests/integration/lldp_test.py
This backport is needed in order to enable CI gating for Fedora packages.
=> [nmstate-0.3] Backport run tests out of containers

libnmstate/error.py, libnmstate/ifaces/ifaces.py, libnmstate/ifaces/linux_bridge.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/testlib/env.py
The linux kernel bridge option use `clock_t_to_jiffies()` and
`clock_t_to_jiffies()` when showing/setting to/from user input value.
Above two functions will lose precision when kernel HZ is configured as
250(Ubuntu 18.04/20.04 is), which lead to `NmstateVerificationError` when
trying to set `multicast_startup_query_interval` of linux bridge to
3125 which been rounded to 3124 by kernel.
Will raise `NmstateKernelIntergerRounded` at verification stage when
integer is rounded for linux bridge option.
Changed old test case to get it pass on Travis CI(Ubuntu host).
Added new test case for this use case.
=> linux bridge: Workaround for 250 HZ kernel

libnmstate/error.py, libnmstate/ifaces/ifaces.py, libnmstate/ifaces/linux_bridge.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/testlib/env.py
The linux kernel bridge option use `clock_t_to_jiffies()` and
`clock_t_to_jiffies()` when showing/setting to/from user input value.
Above two functions will lose precision when kernel HZ is configured as
250(Ubuntu 18.04/20.04 is), which lead to `NmstateVerificationError` when
trying to set `multicast_startup_query_interval` of linux bridge to
3125 which been rounded to 3124 by kernel.
Will raise `NmstateKernelIntegerRoundedError` at verification stage when
integer is rounded for linux bridge option.
Changed old test case to get it pass on Travis CI(Ubuntu host).
Added new test case for this use case.
=> [nmstate-0.3] linux bridge: Workaround for 250 HZ kernel

libnmstate/ifaces/ifaces.py, tests/integration/linux_bridge_test.py
Current code will raise NmstateValueError on overbooks subordinate even
the old main interface is marked as absent.
=> iface: Allowing moving subordinate from absent interface

automation/run-tests.sh, tests/integration/dynamic_ip_test.py, tests/integration/lldp_test.py, tests/integration/testlib/veth.py
Put the veth peer into separate net namespace, to
NetworkManager will not impact test results by trying to managing
the veth peer.
=> test: Isolate veth peer into separate net namespace

libnmstate/ifaces/ifaces.py, tests/integration/linux_bridge_test.py
Current code will raise NmstateValueError on overbooks subordinate even
the old main interface is marked as absent.
=> [nmstate-0.3] iface: Allowing moving subordinate from absent interface

libnmstate/ifaces/base_iface.py, tests/lib/ifaces/base_iface_test.py
When user include only interface name in desire state, we should
treat it as state:up instead of merging from current state:down.
Test case added.
=> state: Don't merge state:down if not defined in desire state

libnmstate/nm/applier.py, tests/integration/linux_bridge_test.py
When replacing NM unmanaged linux bridge port with new,
the unmanaged interface is not taken over by NM which lead to
old ports co-exist with new ports after verification stage.
To support that:
1. Create NM connection even the interface is DOWN as unmanaged
interface is shown as DOWN by NM.
2. Mark the interface as managed by NM.
3. Activate the profile for unmanaged interface before other actions.
So the configure could be applied.
Add test case for replacing unmanaged linux bridge ports.
=> nm bridge: Support replacing unmanaged ports

libnmstate/ifaces/base_iface.py, tests/lib/ifaces/base_iface_test.py
When user include only interface name in desire state, we should
treat it as state:up instead of merging from current state:down.
Test case added.
=> [nmstate-0.3] state: Don't merge state:down if not defined in desire state

automation/run-tests.sh, tests/integration/dynamic_ip_test.py, tests/integration/lldp_test.py, tests/integration/testlib/veth.py
Put the veth peer into separate net namespace, to NetworkManager will not
impact test results by trying to managing the veth peer.
=> [nmstate-0.3] test: Isolate veth peer into separate net namespace

libnmstate/nm/applier.py, tests/integration/linux_bridge_test.py
When replacing NM unmanaged linux bridge port with new,
the unmanaged interface is not taken over by NM which lead to
old ports co-exist with new ports after verification stage.
To support that:
1. Create NM connection even the interface is DOWN as unmanaged
interface is shown as DOWN by NM.
2. Mark the interface as managed by NM.
3. Activate the profile for unmanaged interface before other actions.
So the configure could be applied.
Add test case for replacing unmanaged linux bridge ports.
=> [nmstate-0.3] nm bridge: Support replacing unmanaged ports

libnmstate/nm/wired.py, tests/integration/ovs_test.py
If an interface contains an MTU with value 0, Nmstate should not report
it because it is an special interface like OVS patch port interfaces.
Added a test case for this.
=> nm.wired: do not report MTU if it is 0

libnmstate/nm/wired.py, tests/integration/ovs_test.py
If an interface contains an MTU with value 0, Nmstate should not report
it because it is an special interface like OVS patch port interfaces.
Added a test case for this.
=> [nmstate-0.3] nm.wired: do not report MTU if it is 0

libnmstate/nm/applier.py, tests/integration/ovs_test.py
Due to limitation of NetworkManager 1.26, nmstate cannot support
`save_to_disk=False`(ask, memory only) state for OVS interfaces.
Raise NmstateNotSupportedError if NetworkManager version is older than
1.28 and has OVS interface in desire state with `save_to_disk=False`.
=> nm ovs: Raise NmstateNotSupportedError for save_to_disk=False

libnmstate/nm/applier.py, tests/integration/ovs_test.py
Due to limitation of NetworkManager 1.26, nmstate cannot support
`save_to_disk=False`(ask, memory only) state for OVS interfaces.
Raise NmstateNotSupportedError if NetworkManager version is older than
1.28 and has OVS interface in desire state with `save_to_disk=False`.
=> [nmstate-0.3] nm ovs: Raise NmstateNotSupportedError for save_to_disk=False

libnmstate/nm/applier.py, tests/integration/nm/iproute_config_test.py
When user create bond with subordinate interfaces using non-NM
tools(iproute), the NetworkManager will mark the subordinates as
managed externally.
When the desire state only contains the main interface, nmstate
noticing the slave list is unchanged, so only activate the main
interface, then NM remove the subordinate from their main interface.
To workaround that, mark subordinate interfaces as changed when they are
managed by NM as externally.
=> nm: Mark external subordinate as changed

libnmstate/nm/applier.py, tests/integration/nm/iproute_config_test.py
When user create bond with subordinate interfaces using non-NM
tools(iproute), the NetworkManager will mark the subordinates as
managed externally.
When the desire state only contains the main interface, nmstate
noticing the slave list is unchanged, so only activate the main
interface, then NM remove the subordinate from their main interface.
To workaround that, mark subordinate interfaces as changed when they are
managed by NM as externally.
=> [nmstate-0.3] nm: Mark external subordinate as changed

libnmstate/ifaces/ifaces.py, libnmstate/nm/applier.py, libnmstate/nm/device.py, tests/integration/linux_bridge_test.py
Since we remove unknown type interface before sending to apply, we should
also remove unknown type interface before verifying.
=> state: Remove unmanaged interface before verifying

libnmstate/ifaces/ifaces.py, libnmstate/nm/applier.py, libnmstate/nm/device.py, tests/integration/linux_bridge_test.py
Since we remove unknown type interface before sending to apply, we should
also remove unknown type interface before verifying.
=> [nmstate-0.3] state: Remove unmanaged interface before verifying

libnmstate/nm/applier.py, libnmstate/nm/connection.py, tests/integration/nm/profile_test.py
For changed/desired interface, NM should remove all its inactive
profiles so that it could update and activate the same one.
=> nm profile: Remove inactivate profile of desired interface

libnmstate/nm/applier.py, libnmstate/nm/connection.py, tests/integration/nm/profile_test.py
For changed/desired interface, NM should remove all its inactive
profiles so that it could update and activate the same one.
=> [nmstate-0.3] nm profile: Remove inactivate profile of desired interface

packaging/Dockerfile.centos-stream-nmstate-dev
The CentOS stream is shipping NM 1.26 now, no need to use
NM 1.26 copr repo any more.
=> CI: Remove NM copr repo from CentOS stream image

libnmstate/ifaces/ifaces.py, tests/integration/ovs_test.py
When adding OVS bond/link aggregation interface to existing OVS bridge,
nmstate will fail with error:
> self._ifaces[slave_name].mark_as_changed()
E KeyError: 'bond1'
This is because ovs bond interface does not require a interface entry in
desire state.
Fixed by check before adding dict.
=> ovs: Fix bug when adding bond to existing bridge

libnmstate/ifaces/ifaces.py, tests/integration/ovs_test.py
When adding OVS bond/link aggregation interface to existing OVS bridge,
nmstate will fail with error:
> self._ifaces[slave_name].mark_as_changed()
E KeyError: 'bond1'
This is because ovs bond interface does not require a interface entry in
desire state.
Fixed by check before adding dict.
=> [nmstate-0.3] ovs: Fix bug when adding bond to existing bridge

libnmstate/nm/applier.py, libnmstate/nm/connection.py, tests/integration/nm/profile_test.py
When converting memory-only profile to persistent using simple desire
state with `state: up` only, the memory only profile will not be
converted to persistent.
This is caused by `nm/applier.py` skip profile creation if desire state
is only `state: up`.
The fix is checking whether current profile's persistent state is equal
to desired.
=> nm: Fix converting memory-only profile to persistent

libnmstate/nm/applier.py, libnmstate/nm/connection.py, tests/integration/nm/profile_test.py
When converting memory-only profile to persistent using simple desire
state with `state: up` only, the memory only profile will not be
converted to persistent.
This is caused by `nm/applier.py` skip profile creation if desire state
is only `state: up`.
The fix is checking whether current profile's persistent state is equal
to desired.
=> [nmstate-0.3] nm: Fix converting memory-only profile to persistent

tox.ini
The tox will try to compile pygobject which does not required for
pylint.
Remove the dependency install for pylint.
=> tox: Fix pylint test

tox.ini
The tox will try to compile pygobject which does not required for
pylint.
Remove the dependency install for pylint.
=> [nmstate-0.3] tox: Fix pylint test
