nmstate/nmstate

libnmstate/schemas/interfaces.json, tests/lib/schema_validation_test.py
This PR is dependent on PR#5 (https://github.com/nmstate/nmstate/pull/5)
=> Add interface schema common and ethernet properties

libnmstate/netinfo.py, libnmstate/nmclient.py, nmstatectl/nmstatectl.py, tests/ctl/compat.py, tests/lib/compat.py, tests/lib/netinfo_test.py, tox.ini
List the network devices with basic properties.
=> Device list (nmstatectl show)

tests/lib/nm/__init__.py, tests/lib/nm/applier_test.py, tests/lib/nm/bond_test.py, tests/lib/nm/connection_test.py, tests/lib/nm/device_test.py, tests/lib/nm/ipv4_test.py, tests/lib/nm/ipv6_test.py, tests/lib/nm/translator_test.py
Cover the nm provider (nm.* modules) with unit tests.
=> Utest nm provider

libnmstate/nm/applier.py, libnmstate/nm/ipv4.py, tests/lib/nm/ipv4_test.py
=> Ipv4 set support for static addresses

README.md
- show how to install just for the local user
- Use `--upgrade` to upgrade nmstate if it is already installed
=> Update pip installation instructions

nmstatectl/nmstatectl.py
This makes it easier to create a partial state to change.
=> Allow to limit state to specified interfaces

README.md, libnmstate/netapplier.py, libnmstate/netinfo.py, libnmstate/nm/__init__.py, libnmstate/nm/applier.py, libnmstate/nm/ovs.py, libnmstate/nm/translator.py, libnmstate/schemas/interfaces.json, tests/lib/netapplier_test.py, tests/lib/nm/applier_test.py, tests/lib/nm/ovs_test.py, tests/lib/nm/translator_test.py
OVS bridges are now reported with their supported properties and
connected ports/intefaces.
Note: OVS bonds and internal interfaces are not supported yet.
=> libnmstate: Support ovs-bridge

libnmstate/nm/applier.py
For OVS birdges, the admin state handler needs to process all the bridge
slaves (ports and interface devices) by changing their admin state as
well.
The order is also important, especially when activating the devices: The
port ones need to be activated first and only then the interfaces.
The scenario in which this has been found to matter: Moving a slave from
one birdge to another (without removing it from the old one).
=> nm/applier: OVS slaves need special admin state handling

libnmstate/nm/applier.py, libnmstate/nm/bond.py
Remove the slaves profiles when removing the bond master.
This PR is based on #47
=> Bond slaves cleanup

libnmstate/netapplier.py, libnmstate/nm/__init__.py, libnmstate/nm/checkpoint.py
Use NM checkpoint feature to implement transactions.
Based on #47
=> Transaction support

tests/ctl/nmstatectl_test.py
These are the tests from #25 that need further review.
=> Extra tests

libnmstate/netinfo.py, libnmstate/nm/__init__.py, libnmstate/nm/applier.py, libnmstate/nm/user.py, tests/lib/nm/user_test.py
This contains commits from #57
=> Support setting and getting a decription

README.md
Add the recently added Ethernet properties.
=> README: Update state example

nmstatectl/nmstatectl.py
=> nmstatectl: Use _filter_state() to filter state

nmstatectl/nmstatectl.py
This is another split from #73
=> nmstatectl: Verify state by default

README.md, nmstatectl/nmstatectl.py, tests/integration/nmstatectl_edit_test.py
Use EDITOR variable to open an editor with the current state and apply
it after the editor is closed.
=> nmstatectl: Add edit command to edit state

nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py, tests/integration/nmstatectl_show_test.py
This changes
nmstatectl show --only eth0
to
nmstatectl show eth0
This is another split from #73
=> nmstatectl: Convert --only to an argument

automation/Dockerfile, automation/run-integration-tests.sh
Fix the docker container and its run to stabilize network availability and NM loading.
=> Docker container stabilization

libnmstate/netapplier.py, libnmstate/nm/nmclient.py, tests/integration/iface_admin_state_test.py
=> Execute all actions in mainloop

tests/integration/testlib/assertlib.py, tests/integration/testlib/statelib.py
=> Refactor testlib

README.developer.md, commit-template.txt
For consistency I'm adding some basic guidelines.
These are taken from oVirt VDSM project.
=> readme: Add basic coding-guidelines and commit template

tests/integration/static_ip_address_test.py
The test resultshave been also confirmed using "ip address" to exist
on the kernel .
=> tests integ: Add two ifases with same ipv4 address

libnmstate/netapplier.py, tests/integration/iface_admin_state_test.py, tests/integration/testlib/assertlib.py, tests/integration/testlib/statelib.py
=> Ignore absent ifaces from dstate

tests/integration/bond_test.py
=> Bond base integration tests (creation and removal)

libnmstate/nm/device.py, libnmstate/validator.py, tests/integration/bond_test.py, tests/lib/nm/device_test.py
=> Bond removal fix

nmstatectl/nmstatectl.py
Signed-off-by: Sveta Haas <sveta.haas@gmail.com>
=> nmstatectl: Fix no-verify help message

automation/Dockerfile
Adding NM fix for BZ#1642625.
It should be removed when the fix is available for Centos.
=> automation: Update docker image with NM fix

tests/integration/bond_test.py
Add bond without slaves
Signed-off-by: Sveta Haas <sveta.haas@gmail.com>
=> bond tests:Add bond without slaves

tests/integration/static_ip_address_test.py
the tests are added:
- Remove IPv6 static test - failed
- Add static ipv6 with min state
- Edit static ipv6 and prefix
- Add ifaces with same static ipv6 in one transaction
- Add ifaces with same static ipv6 to existing
Signed-off-by: Sveta Haas <sveta.haas@gmail.com>
=> IPv6 tests: added new IPv6 static tests

libnmstate/netinfo.py, libnmstate/nm/applier.py, libnmstate/nm/translator.py, libnmstate/nm/vlan.py, tests/integration/vlan_test.py, tests/lib/nm/translator_test.py
=> Vlan: Support the VLAN interface type in libnmstate

libnmstate/netapplier.py, libnmstate/nm/device.py, libnmstate/nm/nmclient.py
=> Nm wait for con activation

README.developer.md
=> Developer README: Add valgrind example

setup.py
=> Setup: Update release to 0.0.3

libnmstate/nm/device.py, libnmstate/nm/nmclient.py, tests/lib/nm/device_test.py
Bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1642625
Patches are provided by Thomas Haller, I just add `Signed-off-by` line and do some word wrapping.
=> Workaround for libnm callback GCancellable bug 

packaging/make_rpm.sh
=> RPM building: Remove duplicate code

automation/Dockerfile
=> Test Docker: Install OVS dependencies

examples/vlan101_eth1_absent.yml, examples/vlan101_eth1_down.yml, examples/vlan101_eth1_up.yml, tests/integration/testlib/assertlib.py, tests/integration/vlan_test.py
=> Integration tests: Test downing a vlan interface

examples/linuxbrige_eth1_absent.yml, examples/linuxbrige_eth1_up.yml, libnmstate/appliers/__init__.py, libnmstate/appliers/linux_bridge.py, libnmstate/netapplier.py, libnmstate/netinfo.py, libnmstate/nm/applier.py, libnmstate/nm/bridge.py, libnmstate/nm/translator.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/examples_test.py, tests/integration/nm/linux_bridge_test.py, tests/lib/nm/translator_test.py
Support Linux bridge in nmstate
=> Linux bridge

MANIFEST.in
=> MANIFEST: Add missing pattern to recursive-include

libnmstate/nm/bridge.py
=> nm.bridge: Set only specified port options

README.md
=> README: Add Copr GIT build status

packaging/nmstate.py2.spec, packaging/nmstate.py3.spec
=> rpm: Include examples

tests/integration/nmstatectl_test.py, tests/integration/testlib/cmd.py
Configuring a static IPv4 address on an interface.
=> tests: Add an nmstatectl integration test for 'set'

libnmstate/netinfo.py, tests/integration/bond_test.py, tests/integration/examples_test.py, tests/integration/nmstatectl_test.py, tests/integration/testlib/cmd.py, tests/integration/vlan_test.py
* Integration test: Fix python 3 split() TypeError
* Integration test: Fix vlan test for ordering
* Integration test: Fix python3 float TypeError
* Integration test: Fix vlan rollback test
* Integration test: Fix bond rollback test
=> Misc integration test fixes

tests/integration/nmstatectl_test.py
=> nmstatectl test assert_rc refactoring

README.md
=> README: Add contact information (email and Jira)

libnmstate/netapplier.py, libnmstate/nm/connection.py, libnmstate/nm/device.py, libnmstate/nm/nmclient.py, tests/lib/netapplier_test.py, tests/lib/nm/connection_test.py, tests/lib/nm/device_test.py
Enable autoconnect on profile creation.
=> Enable autoconnect

nmstatectl/nmstatectl.py, tests/integration/examples_test.py, tests/integration/nmstatectl_test.py, tests/integration/testlib/examplelib.py
=> nmstatectl: Allow to set multiple states

README.developer.md
This is primarily based on Gris' notes.
=> Developer docs: Add notes to do a release

automation/run-integration-tests.sh
This ensures that the files are removed in the right path.
=> Automation: Remove nmstate RPMs in docker

.travis.yml, tox.ini
Signed-off-by: Edward Haas <edwardh@redhat.com>
=> coveralls: Remove explicit dependencies and make coveralls optional

README.md
=> README: Document RHEL 7.6 development environment

automation/README.md
=> Automation: Mention automated docker image updates

libnmstate/nm/ovs.py, libnmstate/schema.py, tests/integration/nm/ovs_test.py, tests/lib/netapplier_test.py
Dependent on #268 
Note, this PR consist of only one commit, review the other ones through the dependent PR.
=> Schema ovs port type constant

automation/run-integration-tests.sh, libnmstate/nm/device.py, libnmstate/nm/ovs.py, libnmstate/schema.py, tests/integration/nm/ovs_test.py
=> OVS internal interface: NM provider

libnmstate/netapplier.py, libnmstate/schema.py
Add new content and refactor a bit the constants.
=> schema constants: Update the constant list

libnmstate/netapplier.py, tests/integration/testlib/statelib.py
Sort the bridge ports for OVS and Linux bridges.
=> verify: Sort bridge ports by name

libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/lib/schema_validation_test.py
The routing information will be at the top level of network state information.
=> schema: Add support of IP routing

libnmstate/nm/wired.py, libnmstate/schema.py, libnmstate/state.py, tests/integration/bond_test.py, tests/lib/nm/wired_test.py
Dependent on https://nmstate.atlassian.net/browse/NMSTATE-166
=> mac-address: Support interface mac-address

automation/Dockerfile.fedora, automation/run-tests.sh, packaging/nmstate.py2.spec, packaging/nmstate.py3.spec, requirements.txt, setup.py
* Add `dbus-python` as requirements.
* Fix `ipaddress` requirement in old(<20.5, for example, RHEL 7) setuptools.
=> Packaging fix for dbus and ipaddress requirements.

tests/integration/dhcp_test.py
The test case 'test_dhcp_for_bond_with_ip_address_and_slave' will
randomly fail with error:
```
connection.py              183 WARNING  Connection unavailable on
connection_id bond99, retrying
nmclient.py                190 WARNING  NM main-loop timed out.
```
It is caused by bond slave interface not activated before bond master
which leave master with no slave, the master bond99 will has no link
carrier which lead to IPv4 DHCP timeout.
To workaround this issue, just activate bond99 profile with no IPv4
address and ignore verification on link state. After all profiles got
created, changed bond99 to DHCP.
=> Integration test: Fix bond dhcp test case

automation/run-tests.sh
=> automation: Remove unecessary PYTHON_SITE_PATH_CMD

automation/run-tests.sh
Rebuild CI image if 'packaging' or 'automation' folder changed in git
since origin/master branch.
Fix: https://nmstate.atlassian.net/browse/NMSTATE-171
=> Rebuild CI image if related folder changed

libnmstate/iplib.py, libnmstate/nm/route.py
The gateway property got ignored in previous code for config state.
Depend on PR #327
=> nm.route: Include gateway in config state

libnmstate/netapplier.py, libnmstate/nm/checkpoint.py, nmstatectl/nmstatectl.py
=> checkpoints: Properly report missing permissions

libnmstate/netapplier.py, libnmstate/netinfo.py, libnmstate/validator.py, tests/lib/schema_validation_test.py, tests/lib/validator_test.py
Refactor the validator entry point input to accept the desired and
current state objects.
=> netapplier, validator: Refactor validator module

tests/integration/conftest.py
The ethX fixtures prepare the base interfaces per test by initializing
their configuration (performing a down-up action).
The existing flow has been initializing the interfaces before a test is
executed with no action taken when it ends. This causes in some
scenarios [1] leftovers from tests, affecting the following tests.
In order to resolve the post test leftovers, the test fixtures have been
adjusted to setup the interface at the test setup and to remove them
(set them `down`) at the test teardown.
In order to treat the initial state of the tests session execution,
where the interfaces may have an unknown state/configuration, a session
scoped fixture is used to initialize them (by setting them `down`).
1. Defining a bond/bridge with a slave/port.
---
This change is [<img …
=> tests integ: Refactor fixture setup of ethX interfaces

libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/nm/route.py, tests/lib/nm/route_test.py
Only add single gateway due to limitation of NetworkManager:
https://bugzilla.redhat.com/show_bug.cgi?id=1707396
Test cases included.
~~Depend on PR #352~~
=> libnmstate.nm: Support changing gateway

tests/integration/nm/bond_test.py, tests/integration/nm/testlib.py
tests, nm.testlib: Introduce mainloop_run decorator
Start using the decorator in the nm.bond_test integration module.
=> Integ tests nm mainloop

libnmstate/nm/wired.py, libnmstate/schema.py, libnmstate/state.py, tests/lib/nm/wired_test.py
=> Schema ethernet constants

libnmstate/state.py, tests/lib/state_test.py
Add `State.config_iface_routes` property to get order indexed config routes.
=> State: Provide access to config routes

libnmstate/state.py, tests/lib/state_test.py
New function `State.merge_route_config(other)` with support of adding routes only.
=> Adding `State.merge_route_config()`

libnmstate/state.py, tests/lib/state_test.py
Contains two patches:
* Validate route in `State.merge_route_config()`.
* Verify route via `State.verify_routes()`.
=> state: Add route verification

libnmstate/state.py, tests/integration/route_test.py, tests/lib/state_test.py
Adding `Route.STATE: Route.STATE_ABSENT` to specific route entry will
remove its matching routes.
If any property missing in the absent route entry, it will be treat as
wildcard match.
Example is included at 'examples/eth1_del_route.yml'.
=> Add support of route removal

packaging/make_rpm.sh, packaging/make_srpm.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/372)
=> packaging: Auto detect python version and make output useful for debugging

README.md
To be able to make it easier to install Nmstate on RHEL 8, I documented the necessary steps. Hope it is good enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/351)
=> README: Mention packages for RHEL 8

tests/integration/nm/ipv4_test.py, tests/integration/testlib/iproutelib.py
=> Reapply ip monitor check

tests/integration/vlan_test.py
Test that a VLAN interface uses the same MAC address
as that of its base interface.
=>     tests integ: Test VLAN iface uses base iface's MAC

libnmstate/state.py, tests/lib/state_test.py
Copy running state DNS configuration is not defined in desired state.
=> state: Support merge DNS configuration

libnmstate/nm/dns.py
Introduce `nm.dns.get_iface_dns_metadata()` to get current DNS metadata
of interfaces.
This is needed for preserving current DNS configure when no DNS changes
is made in desire state.
Test case is not included as it require DNS editing.
Will include test cases in DNS editing PR.
=> nm/dns: Retrieve current DNS metadata of interfaces

automation/run-tests.sh
Adjust the run-tests script and execute the build and tests in a temporary folder inside the container.
This keeps the source folder clean with no side effect files leftovers.
Depends on #405
=> Keep source folder clean during tests by relocating the files

libnmstate/state.py, tests/lib/state_test.py
The RouteEntry object represents a route entry.
Adjust RouteEntry to become a bit more generic, decoupling it from the
knowledge on how it is used.
The route state (absent) is now consistently not taking part of any equality,
hashing or matching operations. It is left to the caller to determine
which entries to operate on.
The implementation of `__lt__` enables sorting logic to be embedded in
the object.
To support an easy detection of absent routes, a helper property has
been added (`absent`).
Depends on #406
=> state: Generalize and optimize RouteEntry

libnmstate/state.py
=> State indexing as methods

libnmstate/state.py
=> State transparent config routes

tests/lib/state_test.py
=> Tests state route helpers

libnmstate/metadata.py, libnmstate/nm/__init__.py, libnmstate/state.py, tests/lib/state_test.py
=> State route index with object

libnmstate/validator.py, tests/lib/validator_test.py
=> Validator route

libnmstate/nm/applier.py, tests/integration/conftest.py, tests/integration/linux_bridge_test.py, tests/lib/nm/applier_test.py
Integrate modify into nmstate main setup flow.
Depends on #378
=> Modify integrated

tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py
Instead of using hardcoded port names, extract them from the provided fixtures (portX-up).
Depends on #415
=> Test integ get port name from fixture

tests/integration/nm/linux_bridge_test.py
Introduce a test at the nm subpackage which adds a port to an existing bridge using the `modify` operation. Showing that the bridge link has not been affected.
Note that this PR also includes a refactoring of the test module as a pre-step, allowing the addition of new tests.
Depends on #416
=> Test integ nm bridge add port

libnmstate/nm/device.py
nm.device: Exclude ipv6 changes from reapply
If ipv6 is changed, fallback from reapply to activate.
Ref: https://bugzilla.redhat.com/1734470
=> Exclude ipv6 changes from reapply

libnmstate/netapplier.py, tests/integration/conftest.py, tests/integration/dhcp_test.py, tests/integration/ethernet_mtu_test.py, tests/integration/static_ip_address_test.py, tests/integration/testlib/ifacelib.py
Fix several issues related to IPv6 in both the production code and integration tests.
=> Fix ipv6 related issues

setup.py
Fixes:https://github.com/nmstate/nmstate/issues/465
=> licensing: update license in setup.py

tests/integration/bond_test.py
Signed-off-by: Nandan Kulkarni nakulkar@redhat.com
=> tests integ: VLAN over a slave of a Bond

tests/integration/bond_test.py
Check whether a linux bridge can be successfully
defined over a bond.
=> tests integ: Linux Bridge over a bond

tests/integration/bond_test.py
=> tests integ: VLAN over bond interface

libnmstate/nm/active_connection.py, libnmstate/nm/connection.py
When master is activating, the `AutoconnectSlaves:Yes` will
activate the slaves, this will deactivate slave first.
There is a small chance(less than 1/1000), the
`waitfor_active_connection_async()` fails as the cached active
connection is disconnected.
The root cause is the active connection been replaced and marked as
DEACTIVATED with reason device disconnected by the following activate calls.
The fix is to get current active connection from NM.Device, if that is
not the cached one, use the new one for tracking 'state-change' signals.
=> nm: Fix race problem on slave been deactivated by master

tests/integration/dhcp_test.py
=> Test dhcp over bridge

libnmstate/nm/applier.py
Refactor the nm/applier module to use the schema constants. 
Depends on: #489
=> Use constants on applier

tests/integration/route_test.py
As https://bugzilla.redhat.com/show_bug.cgi?id=1748389 stated,
Currently nmstate will remove routes next hop to interface chose for
saving DNS config which is not listed in desired state.
The test case is added to demonstrate this use case and marked as xfail.
=> Integration test: Add test for preserving default gateway

libnmstate/schemas/operational-state.yaml
There is no code is handling for unknown interface state.
=> schema: Remove invalid interface state -- unknown

tests/integration/ethernet_mtu_test.py
Define two VLAN/s over a shared base interface and edit their MTU.
The transaction fails and therfore marked as xfail.
Ref: https://bugzilla.redhat.com/1751079
=> tests, integ: Test MTU change with two VLAN/s

README.md
See https://lgtm.com/projects/g/nmstate/nmstate/ for more information.
=> readme: Add code quality badge from lgtm.com

README.md
Add `LIMITATIONS.md` to hold the limitations.
=> Doc: Add limitation file

tests/integration/ovs_test.py, tests/integration/testlib/ovslib.py
Introduce helper functions to the module and streamline its format.
This will be helpful in a follow-up patch introducing OVS bonding.
Signed-off-by: Petr Horacek <phoracek@redhat.com>
=> clean-up OVS integration test

.travis.yml
Cleanup travis integration tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/526)
=> Cleanup travis tasks

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/530)
=> Fix CONTRIBUTING issue/clarify black usage

.travis.yml
Replace the test on NetworkManager 1.18 with 1.20.
=> test: Test against NetworkManager 1.20.

tests/integration/linux_bridge_test.py
To verify #516
Signed-off-by: Quique Llorente <ellorent@redhat.com>
=> Add rollback test for linux-bridge

.gitignore, MANIFEST.in, doc/nmstatectl.8.in, packaging/nmstate.py2.spec, packaging/nmstate.py3.spec, setup.py
Add the initial manual page for nmstatectl.
=> doc: Create nmstatectl man page

packaging/README.release.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/538)
=> packaging: Clarify post-release version bump

README.md
Use new public mailing list: <nmstate-devel@lists.fedorahosted.org>
=> README: Change mailing list

tests/integration/testlib/assertlib.py
=> tests, integ: fix minor typo in assertlib

libnmstate/netapplier.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, libnmstate/validator.py, tests/lib/schema_validation_test.py, tests/lib/validator_test.py
Signed-off-by: Quique Llorente <ellorent@redhat.com>
=> Add vxlan schema

README.md
In addition, notify that the nmstatectl manual page is available.
=> README: add link to the libnmstate python API

automation/run-tests.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/566)
=> run-tests: Show NetworkManager version

packaging/Dockerfile.centos8-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, packaging/docker_sys_config.sh
Use NetworkManager-config-server instead of self-generated
NetworkManager config files.
=> test container: Use NetworkManager-config-server

tests/integration/dynamic_ip_test.py
Use polling(check every second) on DHCP/Autoconf states with
timeout 20 seconds.
=> test dhcp: Use polling on DHCP/Autoconf state

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/537)
=> README: Clarify COPR distribution versions

.travis.yml
The commit messages need some polishing. Primarily I want to check if the CI likes this change, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/568)
=> Add CentOS 8 CI image to travis as optional image

libnmstate/nm/device.py
nm device: Mark device as managed before activate
=> nm device: Mark device as managed before activate

.lgtm.yml, .travis.yml, automation/README.md, automation/run-tests.sh, tox.ini
Removing the travis python 2 job will provide more resources for the other jobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/579)
=> Python2 test cleanup

tests/integration/dynamic_ip_test.py, tests/integration/testlib/ifacelib.py, tests/lib/metadata_test.py, tox.ini
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/578)
=> tox/misc: Update to new black version

tests/integration/conftest.py
Mention NetworkManager RPM and Operating System in pytest header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/581)
=> automation: Enhance pytest header

packaging/nmstate.py3.spec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/575)
=> Update spec file

tests/integration/vlan_test.py
If we modify a VLAN interface MTU then we need to reapply the state. If
we do not reapply the state, the rest of the VLAN interfaces based on
the same interface get their MTU restored by default.
Ref: https://bugzilla.redhat.com/1751695
=> netapplier: VLAN MTU change workaround

libnmstate/nm/applier.py, libnmstate/nm/device.py, tests/integration/interface_common_test.py
Virtual devices that are owned by nmstate should be removed.
=> NM, applier: Explicitly remove any virutal device

examples/bond_linuxbridge_vlan_absent.yml, examples/bond_linuxbridge_vlan_up.yml, tests/integration/examples_test.py
Add a real-life complex example to ensure it is working and to use it
for demos in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/595)
=> Examples: Add combined bond/linuxbridge/vlan example

libnmstate/nm/applier.py, libnmstate/nm/sriov.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/sriov_test.py, tests/lib/schema_validation_test.py
=> schema: add SR-IOV basic schema

libnmstate/iplib.py, libnmstate/nm/ipv4.py, libnmstate/nm/ipv6.py, libnmstate/nm/route.py, tests/integration/nm/route_rule_test.py, tests/integration/testlib/iprule.py
NM does not support run time routing rule query yet.
=> nm: Add support of routing rule

libnmstate/nm/bridge.py, libnmstate/schema.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/testlib/bridgelib.py, tests/lib/schema_deprecation_test.py
This is a follow-up on #608
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/612)
=> Schema constants hierarchy stp

libnmstate/nm/applier.py, libnmstate/nm/team.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/team_test.py, tests/lib/schema_validation_test.py
=> schema: Add team interface schema

libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/testlib/ovslib.py, tests/lib/schema_validation_test.py
Signed-off-by: Petr Horacek <phoracek@redhat.com>
=> schema: add OVS link aggregation

packaging/README.release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/629)
=> Update release README

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/628)
=> README: Update Copr repos

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/632)
=> README: Fix URL to nmstate-0.1 status image

libnmstate/nm/device.py
=> nm.device: remove unused _ipv6_has_changed helper

libnmstate/nm/device.py
The minimum NetworkManager version supported is 1.20 so this patch drops
MTU reapply workaround support because it only applies for versions
lower than 1.18.
=> nm.device: drop MTU reapply workaround support

.coveragerc, automation/run-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/634)
=> Travis coverage

automation/README.md, automation/run-tests.sh, tox.ini
This also removes the outdated tox env mentioned in #285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nmstate/nmstate/640)
=> Cleanup tox config

libnmstate/nm/active_connection.py, libnmstate/nm/connection.py, libnmstate/nm/nmclient.py, tests/integration/ovs_test.py, tests/lib/nm/active_connection_test.py
=> nm.connection: report missing NM plugin before device activation

.travis.yml
=> travis: Add python3.8 unit tests to CI

libnmstate/nm/wired.py, tests/integration/nm/ovs_test.py
In some device types (e.g. ovs-interface type) NM does not provide the mac
address from the kernel.
For such cases, use sysfs as a fallback method to read the data.
=> nm, wired: Read mac-address from sysfs when missing from NM

tests/lib/metadata_linux_bridge_test.py
=> tests, metadata: Add Linux Bridge metadata unit tests

tests/integration/bond_test.py
These are uncontroversial changes from #649 / #679
=> Cleanup bond tests

libnmstate/nm/device.py
This should remove two errors we are seeing with the NM 1.22 and master branch for the bond tests:
- `nm-device-error-quark: This device is not a software device or is not realized (5)` 
- `error=nm-client-error-quark: Object is no longer in the client cache (0)`
It appears to be a race condition, sometimes the test just passes, sometimes it warns about using `set_managed` and sometimes one of those errors are triggered.
I ran the new test 100 times as per @cathay4t wishes.
One issue that I found is that the old error handling code was not covered by any tests. I did not manage to figure out how to properly add a test for it as well because of the special mainloop approach in Nmstate. I envision the test to be something like:
Setup:
- create a bond interface
- get the NMDevice for the …
=> Better interface deletion check

CONTRIBUTING.md
=> contributing: add a link to automation documentation 

README.md
This section includes a link to the CONTRIBUTING.md guide.
=> README: add contributing section

libnmstate/nm/sriov.py
=> nm.sriov: get total-vfs property from sysfs

CHANGELOG
=> CHANGELOG: update change log for 0.2.1 release

tests/integration/ovs_test.py
=> tests: set a vlan as an ovs-bridge slave

README.md
=> README: add nmstate-0.2 Copr link and status

libnmstate/nm/sriov.py
This is a workaround to get the SR-IOV VFs configuration from runtime.
We are currently parsing these values from the output of "ip link show
<device>" command.
Ref: https://bugzilla.redhat.com/1777520
=> nm.sriov: get SR-IOV VFs configuration from runtime

libnmstate/nm/active_connection.py, tests/integration/dynamic_ip_test.py
When DHCPv4 enabled with static IPv6, the verification stage will fail
due to the missing of static IPv6 configurations.
This is caused by we stop waiting once reach IP_CONFIG state where
static IP is not applied yet.
To fix this problem, nmstate should wait on fully activated when static
IP enabled.
=> nm ipv4 ipv6: Fix DHCPv4 with static IPv6

automation/run-tests.sh, libnmstate/netinfo.py, libnmstate/nm/applier.py, libnmstate/nm/connection.py, libnmstate/nm/team.py, libnmstate/nm/translator.py, packaging/Dockerfile.centos8-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, packaging/nmstate.spec, tests/integration/conftest.py, tests/integration/team_test.py, tests/lib/nm/translator_test.py
=> nm.team: Team interface basic implementation

.github/stale.yml
=> GitHub: Add stale workflow

packaging/Dockerfile.centos8-nmstate-dev, packaging/nmstate.spec
Update the CentOS container test image to use NM 1.22.
=> packaging: Update test container image to use NM 1.22

tests/integration/nm/wired_test.py
Please, do not review this yet. Thanks!
=> Add xfail to mtu change with reapply 

CHANGELOG
=> CHANGELOG: update change log for 0.2.2 release

libnmstate/nm/applier.py
This reverts commit b3eed505b4970f4cad88d04eee7e0e1e0ed7631a.
as bug https://bugzilla.redhat.com/show_bug.cgi?id=1797478 confirmed as an false alarm.
=> Revert "nm, applier, ovs: Detect OVS bridge ports workaround"

tests/integration/conftest.py, tests/integration/ovs_test.py, tests/integration/team_test.py, tests/integration/testlib/cmdlib.py, tests/integration/testlib/nmplugin.py
=> tests, integ: fix missing plugin tests

tests/integration/ovs_test.py
Signed-off-by: Quique Llorente <ellorent@redhat.com>
=> test ovs-bridge + ovs-interface with same name

CHANGELOG
=> CHANGELOG: update change log for 0.2.4 release

.github/stale.yml
=> GitHub/stale: Fix typo

tests/integration/nm/ovs_test.py
Ref: https://github.com/nmstate/nmstate/issues/802
=> integ, ovs: add xfail to test_bridge_with_internal_interface

tests/integration/nm/bond_test.py, tests/lib/metadata_test.py, tests/lib/netapplier_test.py, tests/lib/netinfo_test.py, tests/lib/nm/applier_test.py, tests/lib/nm/bond_test.py, tests/lib/nm/ovs_test.py, tests/lib/nm/translator_test.py, tests/lib/schema_validation_test.py, tests/lib/state_test.py, tests/lib/validator_test.py
Signed-off-by: Elvira García Ruiz <elviragr@riseup.net>
=> tests: Use schema constants in unit and integration tests

tests/integration/mem_leak_test.py
=> Integration tests: Fix typo in test name

automation/run-tests.sh
=> automation: Only rebuild requested container image

.travis.yml
=> Travis disable fedora jobs

examples/team0_absent.yml, examples/team0_with_slaves.yml, tests/integration/examples_test.py
=> examples, team: add team interface examples

CHANGELOG
=> CHANGELOG: update change log for 0.2.5 release

tests/integration/vlan_test.py
The missing clean up in these tests were causing that
tests/integration/timeout_test.py was failing after running
tests/integration/vlan_test.py.
=> integ: fix missing clean up in vlan integration tests

libnmstate/state.py, tests/integration/dynamic_ip_test.py
When switching from static IP to DHCP/Autoconf, a failure will
occur:
* current static routes will be merged into desired state.
* Static route require static IP address configured.
The fix would be remove routes next hop to DHCP/Autoconf interface.
As we discard static IP address when DHCP/Autoconf enabled, nmstate
does not support static routes along with DHCP/Autoconf.
Test cases included.
=> route: Discard routes next hop to DHCP interface

CHANGELOG
=> CHANGELOG: Update change log for 0.2.6 release

README.md
=> README: Add nmstate-0.2-git Copr repository

libnmstate/nm/bond.py, libnmstate/validator.py, tests/integration/bond_test.py
The linux kernel document suggest no to use miimon with ARP monitoring:
ARP monitoring should not be used in conjunction with miimon.
Hence nmstate will raise NmstateValueError when both miimon and
arp_interval is bigger than zero.
Fix the NM bug on setting 'arp_internal=0' with 'miimon>0':
https://bugzilla.redhat.com/show_bug.cgi?id=1806549
=> nm bond: Support switch between miimon and arp_interval

examples/eth0_with_sriov.yml, tests/integration/examples_test.py
=> examples: add sr-iov example yaml

tests/integration/dynamic_ip_test.py
When switching from DHCP without DHCP server to static IPV6(IPv4
disabled), the nmstate will fail with verification failure showing IPv6
is still disabled.
The keys to reproduce the problem:
* Dummy cannot work. Need to be veth.
* Need to be newly created profile with DHCPv6 enable.
Modifying existing profile to enable DHCPv6 cannot trigger this
problem.
Add test case as xfail to track this problem in CI.
=> test: Add test case for know failure on switching from DHCP to static

.travis.yml
=> travis: Use NM-1.22-git Copr repository for integration tests

CHANGELOG
=> CHANGELOG: update changelog for 0.2.7 release

.travis.yml
=> travis: use quay.io repository in travis

tests/integration/bond_test.py
The bond or bridge will take its first slave's MAC address, hence
NetworkManager by default will activate the slaves in the order of its
interface name.
Nmstate should always produce consistent MAC address regardless the
slave order in desired state.
New integration test case has been included for this case.
=> test: MAC address should be consistent with different slave order.

tests/integration/bond_test.py
Adding these two bond test case to tier1:
* `test_change_2_slaves_bond_mode_from_1_to_5`
* `test_set_miimon_100_on_existing_bond`
=> test: Add two bond test cases to tier1

tests/integration/bond_test.py
The linux bond should keep the MAC address even if the slaves are being
reordered, removed, added or replaced when fail_over_mac is 0.
=> integ: add MAC behaviour tests for linux bonds

CHANGELOG
=> CHANGELOG: Update change log for 0.2.8 release

nmstatectl/nmstatectl.py, tests/integration/nmstatectl_test.py
Added ```--version``` option and ```nmstatectl version```. Wrote integration tests.
=> Add --version and nmstatectl version

.travis.yml, automation/run-tests.sh
=> Backport vdsm tests

.travis.yml, README.md, automation/run-tests.sh, packaging/build-container.sh
This is backporting: #894 and #887
=> Backport container and travis changes.

libnmstate/netapplier.py, libnmstate/nm/nmclient.py
This is backporting: #886 #870
=> Backport verification retry

libnmstate/nm/applier.py, libnmstate/nm/bridge.py, libnmstate/validator.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py
Activate port vlan functionality in nmstate.
Depends on: #882 
Depends on: #888 
Depends on: #892 
This is part of the split from PR #576 .
=> Activate port vlan functionality

examples/linuxbrige_eth1_up_port_vlan.yml, tests/integration/examples_test.py
Depends on: #882
Depends on: #888
Depends on: #892
Depends on: #893 
This is the final part of the split from PR #576 .
=> Add port vlan example

libnmstate/nm/sriov.py
=> [nmstate-0.2] nm.sriov: fix typo in sr-iov device capabilities

libnmstate/nm/bridge.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py
=> [nmstate-0.2] nm.bridge: get ports from sysfs 

libnmstate/state.py, tests/integration/team_test.py
=> team: Sort team ports before verifying

CHANGELOG
=> CHANGELOG: Update change log for 0.2.9 release

tests/integration/ovs_test.py, tests/integration/testlib/ovslib.py
The test is checking whether NM connection proxy port profile got
deleted along OVS interface. The code checking `ovs-vsctl` does not
reflect that as `ovs-vsctl` does not keep empty OVS port.
Changing to use `nmcli` to check the OVS proxy port profile.
=> test ovs: Fix `test_ovs_remove_port`

nmstatectl/nmstatectl.py, tests/ctl/nmstatectl_test.py
Signed-off-by: SudhanAruna <sudhan.aruna.97@gmail.com>
Added Route Rule filter 
For Issue #935
=> nmstatectl: allow route rule filtering by interface

examples/linuxbrige_eth1_up_port_vlan.yml, libnmstate/nm/applier.py, libnmstate/nm/bridge.py, libnmstate/nm/bridge_port_vlan.py, libnmstate/state.py, tests/integration/examples_test.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/testlib/bridgelib.py, tests/integration/testlib/statelib.py, tests/lib/nm/bridge_port_vlan_test.py, tests/lib/schema_validation_test.py, tests/lib/state_test.py, tests/lib/testlib/__init__.py, tests/lib/testlib/bridgelib.py, tests/lib/validator_test.py
This must be approved by @maiqueb
=> [nmstate-0.2] Backport vlan filtering

.travis.yml
Tier1 and slow test cases with NetworkManager-master must pass and tier2
test cases are optional.
=> travis: run tier1 and slow test cases as required for NM-master

README.md, doc/nmstatectl.8.in, libnmstate/validator.py
=> validator: Raises warning if interfaces exceeds 1000 in single desire state

libnmstate/nm/applier.py
In the preparation of simultaneous actions proposed in PR:
https://github.com/nmstate/nmstate/pull/1016
The device deletion should be split and grouped as:
* Profile deactivation.
* Profile deletion.
* Virtual device deletion.
=> nm applier: Split device deletion

libnmstate/nm/context.py, libnmstate/nm/mainloop.py
=> nm mainloop: Fix typo in debug message.

CHANGELOG
=> CHANGELOG: Update change log for 0.3.0 release

README.install.md, libnmstate/netapplier.py, libnmstate/nm/checkpoint.py, libnmstate/nm/connection.py, packaging/Dockerfile.centos8-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, requirements.txt, tests/integration/nm/checkpoint.py, tests/integration/nmstatectl_test.py
=> nm.checkpoint: drop dependency on python-dbus

libnmstate/nm/checkpoint.py, libnmstate/nm/connection.py
On slow server[1], test case `test_disable_static_ipv6_and_rollback` is
constant failing.
The root cause:
The `profile.import_by_device(nm_dev)` does not actually import the
profile as there is no `NM.ActiveConnection` at that time.
Hence the follow up `profile.wait_dev_activation()` does nothing as
`profile._nm_dev` is None.
To fix that, don't use `import_by_device()` but set the
`profile.nmdevice` directly. Also change the wait code to be OK to run
with `profile.profile` as None as in this case we don't care about which
profile is activating.
Also removed the check on `DEACTIVATING` as device might also in
`NM_DEVICE_STATE_DISCONNECTED` state, we should keep waiting as long as
device got `NEW_ACTIVATION`.
=> nm/connection: Wait on rollback

CHANGELOG
=> CHANGELOG: Update changelog for 0.3.1 release

libnmstate/nm/plugin.py
Added in libnmstate/nm/plugin.py changes that decodes and check the
version mismatch when the plugin class is instantiated.
=> nm.plugin: Checking libnm/NM version mismatch

libnmstate/error.py, libnmstate/netapplier.py, libnmstate/nm/plugin.py, libnmstate/nmstate.py, libnmstate/plugin.py, libnmstate/plugins/__init__.py, libnmstate/plugins/nmstate_plugin_ovsdb.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/plugin_test.py, tests/lib/netapplier_test.py, tests/lib/netinfo_test.py
The `libnmstate/nmstate.py` will search `plugins` folder or
NMSTATE_PLUGIN_DIR folder and load it.
The newly add ovs plugin is doing nothing.
New error `NmstatePluginError` for bug in plugin.
The plugins are using `plugin.priority` to:
* For querying, higher priority plugin will override information from
lower ones on the same interface.
* For applying, higher priority plugin will make changes __after__
lower ones.
New interface type: `InterfaceType.OTHER` allowing plugin to use this
type in their plugin in free format.
Integration test cases included.
=> plugin: Introduce plugin design

examples/ovsbridge_patch_create.yml, examples/ovsbridge_patch_delete.yml, libnmstate/ifaces/base_iface.py, libnmstate/ifaces/ifaces.py, libnmstate/ifaces/ovs.py, libnmstate/nm/applier.py, libnmstate/nm/ovs.py, libnmstate/nm/plugin.py, libnmstate/schema.py, libnmstate/schemas/operational-state.yaml, tests/integration/examples_test.py, tests/integration/nm/ovs_test.py, tests/integration/ovs_test.py, tests/integration/testlib/env.py, tests/integration/testlib/ovslib.py, tests/lib/schema_validation_test.py
I am doing manual testing on this. I will let you know once done. Thanks!
=> nm.ovs: OVS Patch support

CHANGELOG
- Support third party plugin written in Python.
- Support LLDP.
- New OVS DB plugin for modifying OVS interface `external_ids`.
- Expanded the support of linux bridge options.
- Support applying desire state which only valid till next reboot.
- Support OVS patch port.
=> CHANGELOG: Update changelog for 0.3.2 release

README.md
=> README: Add the nmstate-0.3 builds

libnmstate/nm/checkpoint.py
The NM async actions might invoke the callback function before the
async action been registered in NmContext fast queue or slow queue.
This lead to timeout on waiting async action to be finished.
Also removed useless try-except around NM async call.
=> nm/checkpoint: Register async action before invoke the async action

libnmstate/nm/checkpoint.py
The NM async actions might invoke the callback function before the
async action been registered in NmContext fast queue or slow queue.
This lead to timeout on waiting async action to be finished.
Also removed useless try-except around NM async call.
=> [nmstate-0.3] nm/checkpoint: Register async action before invoke the async action

.github/ISSUE_TEMPLATE/bug_report.md
Created template to help users report bugs.
=> template: Add bug template

automation/run-tests.sh, examples/dns_edit_eth1.yml, examples/eth1_add_route.yml, examples/eth1_del_all_routes.yml, examples/eth1_with_sriov.yml, examples/linuxbrige_eth1_up_port_vlan.yml, examples/ovsbridge_patch_create.yml, examples/ovsbridge_patch_delete.yml, examples/team0_absent.yml, examples/team0_with_slaves.yml, libnmstate/schemas/operational-state.yaml, tox.ini
resolves #1155 
Fix existing errors and warnings thrown by yamllint
Add Yamllint to CI
=> lint: add yamllint to CI

libnmstate/nm/ovs.py, tests/integration/ovs_test.py, tests/integration/testlib/statelib.py
=> nm/ovs: Sort the OVS interface and OVS bond ports.

libnmstate/nm/ovs.py, tests/integration/ovs_test.py, tests/integration/testlib/statelib.py
=> [nmstate-0.3] nm/ovs: Sort the OVS interface and OVS bond ports.

tests/integration/nm/linux_bridge_test.py
Add a interaction test case to reproduce bug:
https://bugzilla.redhat.com/1816517
The NM unmanaged worker interface should lose IP address after been
assigned to linux bridge.
Resolves: #959
=> test nm: linux bridge worker interface should lose IP address

tests/integration/nm/linux_bridge_test.py
Add a interaction test case to reproduce bug:
https://bugzilla.redhat.com/1816517
The NM unmanaged worker interface should lose IP address after been
assigned to linux bridge.
=> [nmstate-0.3] test nm: linux bridge worker interface should lose IP address

CHANGELOG
=> [nmstate-0.3] CHANGELOG: Update changelog for 0.3.3 release

tests/integration/linux_bridge_test.py, tests/lib/ifaces/ip_state_test.py
=> tests: remove debugging letfovers from tests

CONTRIBUTING.md
=> CONTRIBUTING: fix information about tracking issues in Nmstate

automation/run-tests.sh, automation/tests-container-utils.sh, automation/tests-machine-utils.sh, tests/integration/lldp_test.py
This PR needs some more work but I would like to get some feedback. It is working on my Fedora 32 VM but some tests are failing. I need to investigate if it is related to something missing in the script or anything else.
In addition, I need to add documentation for the run-test-system.sh script.
Thanks!
=> automation: allow to run the tests out of the container

.travis.yml, automation/run-tests.sh, automation/tests-container-utils.sh
=> travis: add job testing tier1 tests with openvswitch2.13

automation/tests-container-utils.sh
=> automation: fix --debug-shell argument

README.md
Signed-off-by: Rafael G. Ruiz <llerrak@hotmail.com>
=> Remove Jira references from README.md

.travis.yml, libnmstate/nm/bridge.py, libnmstate/nm/common.py, packaging/Dockerfile.centos8-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, packaging/nmstate.spec, tests/integration/examples_test.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/ovs_test.py, tests/integration/testlib/env.py
Also removed the NM version check out in integration test cases.
=> nm: Increase the minimum NetworkManager to 1.26.0

libnmstate/nm/connection.py
Some SR-IOV parameters could be not supported by the device driver.
Nmstate must return a proper error message instead of a generic one.
```
libnmstate.error.NmstateLibnmError: Activate profile: eno1 failed:
reason=The device=eno1 does not support one or more of the SR-IOV parameters set.
```
Ref: https://bugzilla.redhat.com/1819588
=> sriov: raise proper exception when SR-IOV parameter is not supported

libnmstate/ifaces/ifaces.py
Currently will sync child state with parent which stop child been
removed.
Expanded the verification stage to check virtual interface been removed
when desire state is down or absent.
Once verification stage expanded, existing integration test case will
catch this failure, no new test case is required.
=> [Regression] Ifaces: allowing child been removed

packaging/nmstate.spec
-Modify nmstate.spec
Signed-off-by: Rafael G. Ruiz <llerrak@hotmail.com>
=> Packaging: adjust dependecy requirements #1203

.travis.yml, libnmstate/nm/bridge.py, libnmstate/nm/common.py, packaging/Dockerfile.centos8-nmstate-dev, packaging/Dockerfile.fedora-nmstate-dev, packaging/nmstate.spec, tests/integration/examples_test.py, tests/integration/linux_bridge_test.py, tests/integration/nm/linux_bridge_test.py, tests/integration/ovs_test.py, tests/integration/testlib/env.py
NetworkManager 1.26 contains bug fixes needed by Nmstate.
Removed the NM version check code in integration test cases.
=> [nmstate-0.3] nm: Increase the minimum NetworkManager to 1.26.0

.travis.yml, automation/run-tests.sh, automation/tests-container-utils.sh, packaging/Dockerfile.centos-stream-nmstate-dev, packaging/build-container.sh
=> Integrate CentOS-stream into CI

libnmstate/ifaces/ifaces.py
Currently will sync child state with parent which stop child been
removed.
Expanded the verification stage to check virtual interface been removed
when desire state is down or absent.
Once verification stage expanded, existing integration test case will
catch this failure, no new test case is required.
=> [nmstate-0.3] Ifaces: allowing child been removed

libnmstate/nm/connection.py
Some SR-IOV parameters could be not supported by the device driver.
Nmstate must return a proper error message instead of a generic one.
```
libnmstate.error.NmstateLibnmError: Activate profile: eno1 failed:
reason=The device=eno1 does not support one or more of the SR-IOV parameters
set.
```
Ref: https://bugzilla.redhat.com/1819588
=> [nmstate-0.3] sriov: raise proper exception when SR-IOV parameter is not supported

tests/integration/ovs_test.py
Due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1857123 ,
nmcli might(1% chance) still show the deleted ovs port profile.
=> [nmstate-0.3] test: Mark test_ovs_remove_port as xfail

CHANGELOG
=> CHANGELOG: Update changelog for 0.3.4 release

libnmstate/plugins/nmstate_plugin_ovsdb.py, tests/integration/ovs_test.py
For newly created OVS internal interface with customer external_ids,
the ovsdb plugin will remove the NM external_ids `NM.connection.uuid`.
The fix is read the current `NM.connection.uuid` before applying
configure and merge it with desired state.
Integration test case updated to cover this usage.
=> ovsdb: Preserve the NM external_ids of newly created interface

libnmstate/plugins/nmstate_plugin_ovsdb.py, tests/integration/ovs_test.py
For newly created OVS internal interface with customer external_ids,
the ovsdb plugin will remove the NM external_ids `NM.connection.uuid`.
The fix is read the current `NM.connection.uuid` before applying
configure and merge it with original desired state.
Integration test cases added.
=> [nmstate-0.3] ovsdb: Preserve the NM external_ids

tests/integration/linux_bridge_test.py, tests/integration/testlib/env.py
=> tests: add test changing multicast-snooping from false to true

tests/integration/linux_bridge_test.py, tests/integration/testlib/env.py
In addition, sorted out the imports.
=> [nmstate-0.3] tests: add test changing multicast-snooping from false to true
